### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by dukedave** [alexkappa/terraform-provider-auth0#101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform 0.12 support.
Per [here](https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-providers):

> We have updated the provider SDK to support both the old and new protocols at once, to allow upgrading to newer provider versions while remaining on Terraform v0.11.

### New or Affected Resource(s)

N/A

### Potential Terraform Configuration

N/A

### References

N/A

**Comment by etiennetremel** [comment]
https://github.com/alexkappa/terraform-provider-auth0/pull/103 was merged into master and introduce Terraform 0.12 support. See v0.2.0 release note: https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.2.0

**Comment by alexkappa** [comment]
As @etiennetremel mentioned this has been merged as part of #103. Sorry for the late reply, I must have missed this in my inbox
