### ISSUE TITLE
Support for Credentials Per Workspace

### ISSUE THREAD

**Issue by mguthrie88** [alexkappa/terraform-provider-auth0#109]
We use several different environments for our infrastructure, and we use terraform workspaces to separate environment context. It would be great to be able to switch auth0 credential sets according to the terraform workspace that we're in, much like we can do with the AWS provider. Right now we have to run a wrapper shell script around terraform because we need to set the environment variables accordingly for each workspace, and we want to avoid hard-coding secret key into our codebase.

**Comment by alexkappa** [comment]
@mguthrie88 I'm not sure I understand the issue. Do you mean similar to how aws does with [shared credentials files](https://www.terraform.io/docs/providers/aws/index.html#shared-credentials-file)?

**Comment by alexkappa** [comment]
@mguthrie88 I feel that the aws credentials example is more integral to the [aws cli tool](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html), not the terraform provider necessarily.

Feel free to submit a feature request with https://github.com/go-auth0/auth0 though.
