### ISSUE TITLE
app_metadata, user_metadata not passed to auth0 correctly

### ISSUE THREAD

**Issue by tkeber** [alexkappa/terraform-provider-auth0#110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14

### Affected Resource(s)

* auth0_user

### Terraform Configuration Files

```hcl
provider "auth0" {}

resource "auth0_user" "user" {
  connection_name = "Username-Password-Authentication"
  username = "test"
  user_id = "12345"
  email = "test@test.com"
  password = "passpass$12$12"
  nickname = "testnick"
  user_metadata = "{\"bar\":{\"baz\":\"qux\"},\"foo\":\"bar\"}"
  app_metadata  = "{\"bar\":{\"baz\":\"qux\"},\"foo\":\"bar\"}"
}
```

### Expected Behavior

terraform state holds app_metadata and user_metadata and is in sync with actual state on auth0

### Actual Behavior

terraform state holds app_metadata and user_metadata but is not in sync with auth0:
- app_metadata, user_metadata is not passed to auth0
- existing app_metadata, user_metadata on auth0 is ignored

### Steps to Reproduce

1. `terraform apply`
2. Inspect actual configuration on auth0 (e.g. with web console, different API client)

### Fix

this is fixed in https://github.com/tkeber/terraform-provider-auth0/tree/v0.2.0-metadata

**Comment by alexkappa** [comment]
Closing this since it has been fixed in #131.
