### ISSUE TITLE
Must import social provider before running TF

### ISSUE THREAD

**Issue by kunickiaj** [alexkappa/terraform-provider-auth0#116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.6

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "google" {
  name     = "google-oauth2"
  strategy = "google-oauth2"
  options {
    client_id     = var.auth0_google_client_id
    client_secret = var.auth0_google_client_secret

  }
  enabled_clients = [
    auth0_client.my_client.id
  ]
}
```

### Expected Behavior

Configure the google-oauth2 social connection.

### Actual Behavior

Error that the connection already exists. Able to import the connection by finding the connection ID using the REST API.

It seems that all Social connections already exist, and before you can configure them with the auth0 provider you must import them into the state. After importing, they work correctly.

Is there a workaround to having to manually import into state?

### Steps to Reproduce

1. `terraform apply`

**Comment by ceralena** [comment]
In my experience, this is standard behaviour for terraform providers. It's not a great UX, but personally I'd be a) surprised, and b) slightly alarmed if this provider just did an import under the hood. Just my 2 cents.

**Comment by kunickiaj** [comment]
I agree with that--It's a weird case for TF though, because these connections always exist by default and can never be created by the provider.

**Comment by alexkappa** [comment]
I agree with @ceralena, I don't think the provider should be doing any importing assumptions. Perhaps documenting this would be out best course of action.
