### ISSUE TITLE
State is modified on update of user resource despite receiving a 400 from the API.

### ISSUE THREAD

**Issue by rsalmond** [alexkappa/terraform-provider-auth0#119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform12 version
Terraform v0.12.6
+ provider.auth0 (unversioned)

Not sure why it says unversioned. Built from master.

### Affected Resource(s)

* auth0_user

### Terraform Configuration Files

```hcl
resource "auth0_user" "user" {
  connection_name = "Username-Password-Authentication"
  nickname = "rsatesting"
  email = "rob+testing@gmail.com"
  email_verified = true
  password = "<password>"
  app_metadata = "{\"groups\": [\"project:platform-admin\", \"foo:bar\"]}"
}
```

### Debug Output

https://gist.github.com/rsalmond/48c98eb8790bf68a08804e8372b9f5b3

### Expected Behavior

After receiving an error from the Auth0 API the local state should not have been modified.

### Actual Behavior

Local state matches what is in the HCL, but not what is in Auth0.

### Steps to Reproduce

1. `terraform apply` the above HCL which succeeds.
2. `terraform state show auth0_user.user` view the state and note the presence of the foobar group in the app metadata.
3. Modify the HCL removing ~the foobar group~ `@` sign from the user email address.
4. `terraform apply` the updated HCL. 
5. Assuming it fails check the state again and note the foobar claim is gone.

### Important Factoids

I suspect the root cause of the 400 error I'm seeing in my environment is an Auth0 rule run amok. You may have to adjust your request to force another type of failure, but I believe the state modification in the face of an error to be reproducible without the rules we have in place.

**Comment by rsalmond** [comment]
Just did a quick test and confirmed you can replicate this by taking the `@` sign out of the email address for the 2nd apply. The request will return a 400 and the state will be updated.

**Comment by rsalmond** [comment]
Since I can't remove the label I'll just add that I can still repro this issue and am happy to provide any debugging info that might help sort it out.

**Comment by alexkappa** [comment]
@rsalmond thanks for the heads-up. I'll try to reproduce and get back to you soon. Sorry for the noise, I'm trying to organise / prioritize issues.

**Comment by alexkappa** [comment]
@rsalmond I am not able to reproduce this issue. Executing the steps as per your bug report I do not receive any 4xx error.

See: https://gist.github.com/alexkappa/5dc5e1450c544a8f1ad51a4de94258ac

**Comment by alexkappa** [comment]
*Update*: I am able to reproduce after following your suggestion to send a bad email.

After some debugging and digging in terraform documentation it seems to be expected behavior with terraform. 

> If the Update callback returns with or without an error, the full state is saved. If the ID becomes blank, the resource is destroyed (even within an update, though this shouldn't happen except in error scenarios).

– [Error Handling & Partial State](https://www.terraform.io/docs/extend/writing-custom-providers.html#error-handling-amp-partial-state)

**Comment by rsalmond** [comment]
Huh! Well in that case I am in your debt, today I learned something new about Terraform. Sorry for the wild goose chase and thanks for digging into this @alexkappa!

**Comment by alexkappa** [comment]
No worries at all @rsalmond!
