### ISSUE TITLE
Missing dependency "git.apache.org/thrift.git"

### ISSUE THREAD

**Issue by jfromaniello** [alexkappa/terraform-provider-auth0#123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```0.12.7```

### Expected Behavior

It should compile.

### Actual Behavior

It can't download "apache thrift":
```
» make build
==> Checking that code complies with gofmt requirements...
go install
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/jose/.gocode/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out
go: error loading module requirements
make: *** [build] Error 1
```

### Steps to Reproduce

1. clean your `$GOPATH/pkg/mod/`
2. clone the repository
3. run `make build` or `go mod download`

### Important Factoids

I read in this issue that the project was moved to github. https://github.com/jenkins-x/jx/issues/3320

I don't have much experience in GO and I can't determine what is the dependency using Apache Thrift.

**Comment by jfromaniello** [comment]
There is a possible solution in this issue:

https://github.com/hashicorp/terraform/issues/22664

**Comment by alexkappa** [comment]
The mentioned issue threads seem to have addressed the issue outside of the scope of this repo. Closing.
