### ISSUE TITLE
universal login settings are not supported

### ISSUE THREAD

**Issue by ceralena** [alexkappa/terraform-provider-auth0#124]
**NB**: we're more than happy to implement this and open a PR, but we thought we'd open a feature request first for any feedback or discussion.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the Auth0 management UI, there's a `Universal Login` section:

https://manage.auth0.com/dashboard/us/$myTenantName/login_settings

You can do things like:

* enable or disable Universal Login
* decide whether to use the "classic" or "new" Universal Login Experience
* set a Primary Color and Page Background Color

For our use case, these are the only settings we can't currently manage through the provider.

### New or Affected Resource(s)

Either an addition to this resource:

```
auth0_tenant
```

Or a new resource named something like:

```
auth0_tenant_universal_login
```

Unfortunately, I can't actually find anything relevant in the Auth0 Management API documentation. If that's the reason it's not supported, then fair enough!

### Potential Terraform Configuration

```hcl
resource "auth0_tenant" "my-tenant" {
  // we've set the following params via the web UI
  //
  //flags = {
  //  universal_login = true,
  //  new_universal_login_experience_enabled = true
  //}
  //universal_login = {
  //  colors = {
  //    primary = "#00D8FF"
  //    page_background = "#001736"
  //  }
  //}
}
```

### References

* https://auth0.com/docs/api/management/v2

**Comment by alexkappa** [comment]
Hi @ceralena, thanks for submitting a request.

I believe Auth0 offers these settings as part of [Prompts](https://auth0.com/docs/api/management/v2#!/Prompts/patch_prompts) and [Branding](https://auth0.com/docs/api/management/v2#!/Branding/patch_branding) resources. In which case we could also follow suit and create two new terraform resources.

It would be great if you are able to contribute these new features, and I'm happy to guide if needed. We'll need to create a PR in the [SDK](/go-auth0/auth0) repo first to add support for these resources. Happily, branding was contributed by @laurentdutheil in [PR#61](https://github.com/go-auth0/auth0/pull/61) so we'll only need to implement the Prompts resource.

The linked PR on go-auth0/auth0 is a great guideline for contributing Prompts if you would like to do that.

Best,
Alex

**Comment by ceralena** [comment]
Thanks for the prompt response. I'll have a look at all that and see what we can come up with. Thanks!

**Comment by bishtawi** [comment]
I tackled this in https://github.com/alexkappa/terraform-provider-auth0/pull/133

From the debugging I did, the Auth0 management dashboard modifies the tenant attributes and doesnt use Prompts or Branding at all.

**Comment by alexkappa** [comment]
I just merged in https://github.com/alexkappa/terraform-provider-auth0/pull/133 which adds support for `flags` and `universal_login` settings (thanks to @bishtawi).

Feel free to test it with the [v0.3.1](https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.3.1) release.

**Comment by franklouwers** [comment]
Hi,

Any plans to support more settings than just the theme?

Eg custom prompts as described in https://auth0.com/docs/universal-login/new-experience/text-customization-new-universal-login ?
