### ISSUE TITLE
Password Dictionary option broken on Connection resource

### ISSUE THREAD

**Issue by bishtawi** [alexkappa/terraform-provider-auth0#127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.8

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "database" {
  name                 = "database"
  strategy             = "auth0"
  is_domain_connection = false

  enabled_clients = [
    auth0_client.application.name
  ]

  options {
    brute_force_protection         = true
    disable_signup                 = false
    enabled_database_customization = false
    import_mode                    = false
    requires_username              = false
    password_policy                = "good"
    password_history {
      enable = true
      size   = 5
    }
    password_no_personal_info {
      enable = true
    }
    password_dictionary = {     # <--- This right here is broken
      enable = true
    }
  }
}
```

### Expected Behavior

Auth0 Connection resource is successfully created with the Password Dictionary feature enabled.

### Actual Behavior

Crash, `password_dictionary.enable` is sent to auth0 as a string instead of a bool:

```
...
          + password_dictionary            = {
              + "enable" = "true"          # <---- This is the downside of using map, the boolean is now a string
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "dev"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

auth0_connection.database: Creating...

Error: 400 Bad Request: Payload validation error: 'Expected type boolean but found type string' on property options.password_dictionary.enable.

  on auth0.tf line 57, in resource "auth0_connection" "database":
  57: resource "auth0_connection" "database" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by alexkappa** [comment]
Closing as done. Once again, thanks for helping out Stephen!
