### ISSUE TITLE
New release >v0.2.0

### ISSUE THREAD

**Issue by edify42** [alexkappa/terraform-provider-auth0#136]
Hi @alexkappa 

Any chance you can build and publish a new release? I'm guessing the CI isn't in a running state to publish the release automatically after merges to master?

**Comment by edify42** [comment]
Hey @alexkappa - Any update on this?

**Comment by alexkappa** [comment]
Hi Ted, I've just released v0.2.1 with the latest merged features and fixes. Thanks for your patience
