### ISSUE TITLE
auth0_rule_config import unexpected "update in-place"

### ISSUE THREAD

**Issue by scottx611x** [alexkappa/terraform-provider-auth0#142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.12
+ provider.auth0 v0.2.1
```

The issue is still prevalent with the most up-to-date setup as well:
```
Terraform v0.12.16
+ provider.auth0 v0.2.2
```

### Affected Resource(s)

* auth0_rule_config

### Terraform Configuration Files

```hcl

provider "auth0" {
  version       = "~> 0.2.1"
  domain        = "https://<domain>/api/v2/"
  client_id     = "<client_id>"
  client_secret = "<client_secret>"
}

resource "auth0_rule_config" "test" {
  key   = "TEST"
  value = "TEST"
}
```

### Debug Output

`terraform_import` : https://gist.github.com/scottx611x/7153ac110a6c03078534a1b5509ab8c6
`terraform_plan` :  https://gist.github.com/scottx611x/f7b5a9afaa557e4579d745dc00776f56

### Panic Output

N/A

### Expected Behavior

After a `terraform import` I would imagine a subsequent `terraform plan` to be a no-op assuming the provided `auth0_rule_config` value was identical to what exists in auth0

### Actual Behavior
The subsequent `terraform plan` wants to update-in-place even when the locally set value and the value in auth0 match exactly.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # auth0_rule_config.test will be updated in-place
  ~ resource "auth0_rule_config" "test" {
        id    = "TEST"
        key   = "TEST"
      + value = (sensitive value)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. Create a rule config in auth0 (I went with key "TEST" value "TEST")
1. Stub out an `auth0_rule_config` resource with the aforementioned key/value
1. `terraform import auth0_rule_config.test TEST`
1. `terraform plan`

### Important Factoids

A `terraform apply` (with the update-in-place from above) produces a clean slate and subsequent plans are no-ops

### References

N/A

**Comment by alexkappa** [comment]
@scottx611x the Auth0 API doesn't return rule values. It's a write-only for security reasons and there is no way for this provider to import into the value property without it.

https://auth0.com/docs/api/management/v2/#!/Rules_Configs/get_rules_configs

**Comment by scottx611x** [comment]
@alexkappa great thanks for the clarification 👍
