### ISSUE TITLE
Missing ability to set many of the options for the github connection

### ISSUE THREAD

**Issue by wr0ngway** [alexkappa/terraform-provider-auth0#143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.17
Auth0 plugin v0.2.2

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "auth0_connection" "github" {
  name     = "github"
  strategy = "github"

    options {
     // Doesn't seem to be support for setting these in the auth0 provider
     //
      email = true
      read_org = true
      profile = true
      read_user = true
      scope = [
        "user:email",
        "read:org",
        "read:user"
      ]
    }
}

```

### Expected Behavior

It sets the options

### Actual Behavior

```
Error: Unsupported argument

  on auth0.tf line 110, in resource "auth0_connection" "github":
 110:       email = true

An argument named "email" is not expected here.


Error: Unsupported argument

  on auth0.tf line 111, in resource "auth0_connection" "github":
 111:       read_org = true

An argument named "read_org" is not expected here.


Error: Unsupported argument

  on auth0.tf line 112, in resource "auth0_connection" "github":
 112:       profile = true

An argument named "profile" is not expected here.


Error: Unsupported argument

  on auth0.tf line 113, in resource "auth0_connection" "github":
 113:       read_user = true

An argument named "read_user" is not expected here.


Error: Unsupported argument

  on auth0.tf line 114, in resource "auth0_connection" "github":
 114:       scope = [

An argument named "scope" is not expected here.

Terraform exited with non-zero exit code: 1
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If I fetch the connection using the REST api, I see the full set of options that I should be able to set:
```
{
  "id": "REDACTED",
  "options": {
    "client_id": "REDACTED",
    "client_secret": "REDACTED",
    "email": true,
    "read_org": true,
    "profile": true,
    "read_user": true,
    "follow": false,
    "public_repo": false,
    "repo": false,
    "repo_deployment": false,
    "repo_status": false,
    "delete_repo": false,
    "notifications": false,
    "gist": false,
    "read_repo_hook": false,
    "write_repo_hook": false,
    "admin_repo_hook": false,
    "write_org": false,
    "admin_org": false,
    "read_public_key": false,
    "write_public_key": false,
    "admin_public_key": false,
    "scope": [
      "user:email",
      "read:org",
      "read:user"
    ]
  },
  "strategy": "github",
  "name": "github",
  "is_domain_connection": false,
  "enabled_clients": [],
  "realms": [
    "github"
  ]
```
I also tried shoving them into the configuration hash within options, but while terraform was able to execute it, it didn't affect the matching settings on the connection resource in auth0, so I'm guessing thats not what it is for.

**Comment by wr0ngway** [comment]
I think this may be a limitation with the auth0 api.  That is, I was also unable to set these properties using their api directly with curl:
```
> curl -sS --request PATCH --url' 'https://mydomain.auth0.com/api/v2/connections/conID --header 'authorization: Bearer myauthtoken --data '{"options":{"email":true}}'
{"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Additional properties not allowed: {\"options\":{\"email\":true}}'.","errorCode":"invalid_body"}
>
```

For reference the update command doesn't list these options in the body in the example:
https://auth0.com/docs/api/management/v2/#!/Connections/patch_connections_by_id

Yet when I set them manually and fetch the connection, they do show up, so I could just be missing something.

**Comment by wr0ngway** [comment]
Actually, I take that back - I was able to update using their api - was missing `--header "content-type: application/json"` in the curl command above.  So the issue stands, the API allows setting these options, but this provider doesn't support it yet

**Comment by alexkappa** [comment]
@wr0ngway, some of these options are indeed not supported. I mostly based the implementation of both the SDK and this provider on the Auth0 API [docs](https://auth0.com/docs/api/management/v2/#!/Connections/patch_connections_by_id) and it seems to be undocumented.

I suspect some of what you want to set is prefixed with `ext_*` as there is some overlap there. Or we should implement the properties like the response you posted. Auth0 not documenting this makes things pretty difficult.

**Comment by nirvdrum** [comment]
Does anyone happen to know if these options were added? Or did stalebot just unhelpfully close the issue?
