### ISSUE TITLE
Can't pass client_id to auth0_connection configuration without corruption

### ISSUE THREAD

**Issue by garthk** [alexkappa/terraform-provider-auth0#151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.17
+ provider.auth0 (unversioned)
+ provider.aws v2.41.0
+ provider.external v1.2.0
+ provider.local v1.4.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* `auth0_client`
* `auth0_connection`

### Terraform Configuration Files

Given the misfortune of having to migrate credentials from one Auth0 connection to another:

```hcl
resource "auth0_client" "custom_auth_db" {
  # ...
}

resource "auth0_connection" "custom_auth_db" {
  name     = local.custom_auth_db_name
  strategy = "auth0"
  options {
    custom_scripts = {
      login    = file("${path.module}/files/login.js")
      get_user = file("${path.module}/files/get_user.js")
    }
    configuration = {
      ENVIRONMENT           = var.environment
      AUTH0_CLIENT_ID       = auth0_client.custom_auth_db.client_id
      AUTH0_CLIENT_SECRET   = auth0_client.custom_auth_db.client_secret
      # ...
  }
  # ...
}
```

… we're getting `configuration.AUTH0_CLIENT_ID` set to what looks like a bcrypt digest `2.0$9e95…$6d32…$3c73…`, _not_ the value shown in `terraform state pull` output for `client_id`:

```json
{
  "version": 4,
  "terraform_version": "0.12.17",
  "serial": 639,
  "lineage": "50dfabda-acf9-4d6e-8db9-7e26e3f99eb9",
  "resources": [
    {
      "module": "module.auth0",
      "mode": "managed",
      "type": "auth0_client",
      "name": "custom_auth_db",
      "provider": "module.auth0.provider.auth0",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "addons": [],
            "allowed_logout_urls": [],
            "allowed_origins": [],
            "app_type": "regular_web",
            "callbacks": [],
            "client_id": "VGhlIGNvcnJlY3QgdmFsdWUuLi4uLi4K",
            "...": "..."
          }
        }
      ]
    },
    {
      "module": "module.auth0",
      "mode": "managed",
      "type": "auth0_connection",
      "name": "custom_auth_db",
      "provider": "module.auth0.provider.auth0",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "options": [
              {
                "configuration": {
                  "ENVIRONMENT": "2.0$929b…$8b4f…$0824…",
                  "API": "2.0$8a57…$0a16…$eee6…",
                  "AUTH0_CLIENT_ID": "2.0$5f6e…$7a02…$231d…",
                  "...": "..."
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
```

We're also seeing `client_secret` mangled. No other values in `configuration` arrive mangled in the Auth0 execution environment, however. `ENVIRONMENT`, for example, arrives intact despite `resources[1].instances[0].attributes.options[0].configuration.ENVIRONMENT` being encrypted.

I've tried shoving another Base64-ish value into `configuration`. It, too, arrived intact.

### Debug Output

I regret I lack the time to sanitise the debug output. If you could point to specific entries I could pull out, I could sanitise and provide just those. Please advise.

### Panic Output

None.

### Expected Behavior

An `auth0_connection` resource should be able to supply `options.configuration.AUTH0_CLIENT_ID` by reference to the `client_id` of an `auth0_client` resource.

### Actual Behavior

* All `options.configuration` values are encrypted in the state file
* Those obtained by reference through `auth0_client.custom_auth_db` aren't decrypted at the other end

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None I can think of.

### References

None I could find.

**Comment by garthk** [comment]
Workaround: after using `auth0_client.custom_auth_db.client_id` in the `value` of an `output` without much trouble, I figured I could:

```hcl
resource "auth0_connection" "custom_auth_db" {
  name     = local.custom_auth_db_name
  strategy = "auth0"
  options {
    custom_scripts = {
      login    = file("${path.module}/files/login.js")
      get_user = file("${path.module}/files/get_user.js")
    }
    configuration = {
      ENVIRONMENT           = var.environment
      AUTH0_CLIENT_BASE64 = jsonencode({
        id     = auth0_client.custom_auth_db.client_id
        secret = auth0_client.custom_auth_db.client_secret
      })
      # ...
  }
  # ...
}
```

… which gave me a `configuration.AUTH0_CLIENT_BASE64` I could `JSON.parse` at the other end.

**Comment by alexkappa** [comment]
Hi @garthk, I am afraid the values are encrypted by auth0 sever side as is done by rule configurations. I was not aware of this particular behavior to be honest.

I can take a closer look, but if its the case, there's not much this provider (or the sdk) can do.

**Comment by garthk** [comment]
The values in the state above at `resources[1].instances[0].attributes.options[0].configuration` came from Auth0 rather than the `options.configuration` of the `auth0_connection.custom_auth_db` resource?
