### ISSUE TITLE
Rotation of Client Secrets in auth0_client

### ISSUE THREAD

**Issue by vidarw** [alexkappa/terraform-provider-auth0#152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Thanks for creating a useful and promising library. I was wondering if there is a way or you could add a function to rotate the client secret without destroying the client resource?

As a potential solution I thought about using the terraform random function and manually set the client_secret field in the auth0_client resource (results in `Error: "client_secret": this field cannot be set`). The idea was to taint the randomly generated password string and thereby force an update of the client_secret field.

Any suggetions and solutions regarding secret rotation is highly appreaciated.

### New or Affected Resource(s)

* auth0_client

### Potential Terraform Configuration

```hcl
resource "auth0_client" "my_client" {
  name     = "my_client"
  app_type = "non_interactive"

  client_secret = var.my_random_secret

  grant_types = [
    "authorization_code",
    "implicit",
    "refresh_token",
    "client_credentials"
  ]

  is_first_party                      = true
  is_token_endpoint_ip_header_trusted = false
  oidc_conformant                     = true
}
```

### References

* #0000

**Comment by alexkappa** [comment]
Hi @vidarw, thanks for submitting this. Its an interesting idea, definitely worth looking into.

As you have already discovered directly setting the client secret is not supported by the auth0 api. But rotating the secret is.

Perhaps, we could have user settable field (e.g. client_secret_version), which when changed can trigger a secret rotation, updating the client_secret attribute.

The value of this field could be a number, string, perhaps even a date? Not sure at the moment.

But I’d like to see what other providers do in such cases.

What do you think?

**Comment by vidarw** [comment]
Maybe implement it in a similar matter to the `null_resource` trigger? My impression is that it is a stored string value and it triggers a refresh if the string value changes. https://www.terraform.io/docs/providers/null/resource.html

Another option is to have a bool `rotate_client_secret`. This allows for easy use of different operational logic (modulo, specifict conditions, etc.).

The name must be properly documented so we don't confuse anyone as a secret rotation is non-reversable. Using the term `version` might be in the danger zone as it might imply that you can revert something. Best i can think of at the moment is `client_secret_rotation_trigger`.

**Comment by alexkappa** [comment]
> Maybe implement it in a similar matter to the null_resource trigger?

This seems spot on, thanks for pointing it out. Only difference I think is that `null_resource` takes the shotgun approach and forces a new resource upon changing the `triggers` attribute. We will want to do our secret rotation instead.

They also define the `triggers` to be a map. I suppose it can be used to add metadata to each trigger. Not sure if we should take the same approach, maybe it's a good idea.

> Using the term version might be in the danger zone

You are totally right about that, version is not a good name. Lets go with `client_secret_rotation_trigger` as you suggested.

I'll give it a go unless you are up for it.
