### ISSUE TITLE
Error: missing expected [

### ISSUE THREAD

**Issue by garthk** [alexkappa/terraform-provider-auth0#157]
After rebuilding `terraform-provider-auth0` when our cache expired over the holiday season, `terraform plan` fails with:

> Error: missing expected [

Bisecting from 8cceead to f3bab1e yields:

> 654f282a5953a75a825f6df827ac2c8169d443d6 is the first bad commit

… which was 2019-09-12, so I guess we'd had it cached for a while. Checking the diff…

```diff
diff --git auth0/resource_auth0_connection.go auth0/resource_auth0_connection.go
index 3754db2..576888c 100644
--- auth0/resource_auth0_connection.go
+++ auth0/resource_auth0_connection.go
@@ -101,9 +101,22 @@ func newConnection() *schema.Resource {
                                                        },
                                                },
                                                "password_dictionary": {
-                                                       Type:     schema.TypeMap,
-                                                       Elem:     &schema.Schema{Type: schema.TypeString},
+                                                       Type:     schema.TypeList,
                                                        Optional: true,
+                                                       MaxItems: 1,
+                                                       Elem: &schema.Resource{
+                                                               Schema: map[string]*schema.Schema{
+                                                                       "enable": {
+                                                                               Type:     schema.TypeBool,
+                                                                               Optional: true,
+                                                                       },
+                                                                       "dictionary": {
+                                                                               Type:     schema.TypeSet,
+                                                                               Elem:     &schema.Schema{Type: schema.TypeString},
+                                                                               Optional: true,
+                                                                       },
+                                                               },
+                                                       },
                                                },
                                                "api_enable_users": {
                                                        Type:     schema.TypeBool,
@@ -409,6 +422,8 @@ func buildConnection(d *schema.ResourceData) *management.Connection {
                c.Options = &management.ConnectionOptions{
                        Validation:                   Map(MapData(m), "validation"),
                        PasswordPolicy:               String(MapData(m), "password_policy"),
+                       PasswordHistory:              Map(MapData(m), "password_history"),
+                       PasswordNoPersonalInfo:       Map(MapData(m), "password_no_personal_info"),
                        PasswordDictionary:           Map(MapData(m), "password_dictionary"),
                        APIEnableUsers:               Bool(MapData(m), "api_enable_users"),
                        BasicProfile:                 Bool(MapData(m), "basic_profile"),
```

We're not using `password_dictionary`, but there is one in our state. `terraform state pull | gron | grep password_dictionary` yields:

> ```json.resources[55].instances[0].attributes.options[0].password_dictionary = {};```

Do you have a state migration for `password_dictionary`?

Perhaps relevant: hashicorp/terraform-plugin-sdk#253.

**Comment by garthk** [comment]
Workaround:

* `terraform state pull > state.json`
* Look for `"type": "auth0_connection"`
* Scroll down to look through the contents of any `.instances[].attributes.options[]` object
* Delete any line in that object containing only `"password_dictionary": {}`
* Scroll to the top
* Increment your `"serial"` number
* `terraform state push state.json`

My diff looked like this:

```diff
--- state-145.json	2020-01-07 11:29:26.000000000 +1100
+++ state-146.json	2020-01-07 11:31:10.000000000 +1100
@@ -1,7 +1,7 @@
 {
   "version": 4,
   "terraform_version": "0.12.18",
-  "serial": 145,
+  "serial": 146,
   "lineage": "09003dfa-4555-4ecd-3b8c-61463ba02121",
   "outputs": {
     "ecs_lb_public_dns_name": {
@@ -2153,7 +2153,6 @@
                 "max_groups_to_retrieve": "",
                 "messaging_service_sid": "",
                 "name": "",
-                "password_dictionary": {},
                 "password_history": [
                   {
                     "enable": true,
```

**Comment by alexkappa** [comment]
Hi @garthk sorry for the inconvenience. I was not aware of state migrations, but I'll have a look in the case we can be more careful when breaking backwards compatibility in the future. Thanks.

**Comment by nirvdrum** [comment]
@garthk Thanks for the solution! We were on 0.3.1 and just ended up having problems because 0.5.1 is now available in the Terraform registry, so team members were picking up a new version inadvertently. We have multiple environments, managed with [atmos](https://github.com/simplygenius/atmos), so updating everything is going to be a bit painful. But, at least now I know what's going on and how to fix it.

**Comment by kevinohara80** [comment]
Ouch, we just hit this one hard. Any plans to implement the state migration @alexkappa?

**Comment by maroux** [comment]
Hit this as well on 0.8.0. For me it was the type change of `auth0_connection.totp` in 86a18632c05906c2fa494e4e99bdb961f703cea4. Removing `totp` from state file as specified in the workaround worked - however I really don't like messing with state files manually.

**Comment by ClementineOldfield** [comment]
Just a PSA for anyone using the above workaround, make sure to delete or gitignore the state.json file as it contains sensitive data
