### ISSUE TITLE
Feature Request: Install, activate and/or configure extensions

### ISSUE THREAD

**Issue by stefangreim** [alexkappa/terraform-provider-auth0#158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are using the _Custom Social Connections_ Auth0 Extension which is a webtask app. I understand that webtask apps are not in scope. But is it somehow possible to install, activate or at least configure Auth0 extensions via Terraform? As far as I can see/understand in the traffic, the normal connections api is used to configure the custom social connection. However, this configuration cannot be done via Terraform.

### New or Affected Resource(s)

* auth0_extension

### References

https://auth0.com/docs/extensions/custom-social-extensions

**Comment by victorb** [comment]
This would be great to have supported by terraform-provider-auth0. Also using the `custom-social-extension`, together with `Real-time Webtask Logs` and `Auth0 Authentication API webhooks`, which has to be manually copy-pasted right now.

**Comment by alexkappa** [comment]
I am afraid this provider cannot offer such functionality. There is no public facing API that I know of that can manipulate these extensions. 

Some inspection of the console when enabling extensions via the dashboard, it seems to use a sandbox domain (https://sandbox8-eu.it.auth0.com/api/webtask), which I don't even know how to authenticate with.

If/when Auth0 makes these resources available from the Auth0 Management API then we can add it to the provider, but until then theres nothing we can do here.

**Comment by victorb** [comment]
@alexkappa Thanks for the answer. Sad to hear that... Hope it'll change.

Hey @jpadilla, @glennblock, @panga, @albertoperdomo, @twistedstream, @eugeniop and @kmaida

Any idea if there is plans on adding a management API for managing the extensions? Seems there is none currently and it's hard to build reusable and lasting configuration on top of Auth0 with Terraform without this.

**Comment by stefangreim** [comment]
@alexkappa Thanks for the answer. Understandable. If it is possible in the near future, I would very much appreciate this feature. Looking forward...
