### ISSUE TITLE
Allow use_scope_descriptions_for_consent flat in auth0_tenant

### ISSUE THREAD

**Issue by fetilla** [alexkappa/terraform-provider-auth0#167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

First of all, thanks for this awesome library. I am missing the following, the resource auth0_tenant, in the flag argument, is not allowed to indicate: "use_scope_descriptions_for_consent": true

### New or Affected Resource(s)

* auth0_tenant

### References

* https://auth0.com/docs/scopes/current/guides/customize-consent-prompt

**Comment by alexkappa** [comment]
Hi @fetilla, I've added it in and will release on monday as tf goes back to work. Thanks for submitting this.
