### ISSUE TITLE
auth0_connector fails to create because of missing script property

### ISSUE THREAD

**Issue by erikburgess** [alexkappa/terraform-provider-auth0#169]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.19
+ provider.auth0 v0.5.1

### Affected Resource(s)

auth0_connection

### Terraform Configuration Files

```hcl
"provider" "auth0" {}

"resource" "auth0_connection" "configure-example-oauth2-connector" {
  "count" = 1

  "name" = "example-oauth2"

  "options" = {
    "client_id" = ""

    "client_secret" = ""

    "configuration" = {
      "authorizationURL" = "https://auth.example.com/as/authorization.oauth2"

      "scope" = "openid, profile, email"

      "tokenURL" = "https://auth.example.com/as/token.oauth2"
    }

    "custom_scripts" = {
      "fetchUserProfile" = "function(accessToken, ctx, cb) { request.get('''https://sso.example.com/idp/userinfo.openid''', { headers: { '''Authorization''': '''Bearer ''' + accessToken } }, function(e, r, b) { if (e) return cb(e); if (r.statusCode !== 200 ) return cb(new Error('''StatusCode: ''' + r.statusCode)); var profile = JSON.parse(b).account; profile.user_id = profile.uuid; cb(null, profile); });}"
    }
  }

  "strategy" = "oauth2"
}

"terraform" "backend" "s3" {
  "bucket" = ""

  "dynamodb_table" = ""

  "encrypt" = true

  "key" = ""

  "region" = "us-east-2"
}

"terraform" "required_providers" {
  "auth0" = "= v0.5.1"
}
```

### Expected Behavior

An oauth2 connector is created

### Actual Behavior

Creating the connector fails with an error about a missing field

Error: 400 Bad Request: Payload validation error: 'Missing required property: scripts' on property options.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

[]( https://github.com/terraform-providers/terraform-provider-auth0/blob/master/auth0/resource_auth0_connection.go#L57) does not support “scripts” which it should. [based on](https://auth0.com/docs/connections/social/oauth2) , custom_scripts later is translated to customScripts which match the [API doc](https://auth0.com/docs/api/management/v2/#!/Connections/post_connections): , but the [sample page] (https://auth0.com/docs/connections/social/oauth2) shows that one should use “scripts”

### References

Example from auth0 docs
```bash
curl --request POST \
  --url https://youraccount.auth0.com/api/v2/connections \
  --header 'authorization: Bearer ABCD' \
  --data '{ "name": "digitalocean", "strategy": "oauth2", "options": { "client_id", "YOUR-DIGITAL-OCEAN-CLIENT-ID", "client_secret": "YOUR-DIGITAL-OCEAN-CLIENT-SECRET", "authorizationURL": "https://cloud.digitalocean.com/v1/oauth/authorize", "tokenURL": "https://cloud.digitalocean.com/v1/oauth/token", "scope": ["read"], "scripts": { "fetchUserProfile": "function(accessToken, ctx, cb) { request.get('\''https://api.digitalocean.com/v2/account'\'', { headers: { '\''Authorization'\'': '\''Bearer '\'' + accessToken } }, function(e, r, b) { if (e) return cb(e); if (r.statusCode !== 200 ) return cb(new Error('\''StatusCode: '\'' + r.statusCode)); var profile = JSON.parse(b).account; profile.user_id = profile.uuid; cb(null, profile); });}'
```

* #0000

**Comment by alexkappa** [comment]
@dmiller9911 any thoughts on how we might tackle this? Seems like there are more than one way to define scripts in the API. 

Is there a plan internally to unify over a single one of these fields? Any idea why they are different?

**Comment by rene00** [comment]
Hi 👋 I believe we should be using `scripts` when defining `fetchUserProfile` as shown in the examples with in the oauth2 [documentation](https://auth0.com/docs/connections/social/oauth2).

`customScripts` should be used for DB connections. From the Connections API [docs](https://auth0.com/docs/api/management/v2/#!/Connections/post_connections):
> customScripts object (optional) A map of scripts used to integrate with a custom database.

An example of properties `customScripts` supports can be found [here](https://github.com/auth0/auth0-deploy-cli/blob/master/examples/yaml/tenant.yaml#L39-L46).

The following terraform config works for me using terraform 0.13.5:

```hcl
provider "auth0" {
  version = "= 0.16.1"
}

resource "auth0_connection" "my-connection" {
  name = "Example-Connection"
  strategy = "oauth2"
  options {
    client_id = ""
    client_secret = ""
    configuration = {
      authorizationURL = "https://auth.example.com/as/authorization.oauth2"
      scope = "openid, profile, email"
      tokenURL = "https://auth.example.com/as/token.oauth2"
    }
    scripts = {
      fetchUserProfile = "function(accessToken, ctx, cb) { request.get('''https://sso.example.com/idp/userinfo.openid''', { headers: { '''Authorization''': '''Bearer ''' + accessToken } }, function(e, r, b) { if (e) return cb(e); if (r.statusCode !== 200 ) return cb(new Error('''StatusCode: ''' + r.statusCode)); var profile = JSON.parse(b).account; profile.user_id = profile.uuid; cb(null, profile); });}"
    }
  }
}
```

**Comment by epintos** [comment]
This works for me if I want to create a custom connection for Slack

```terraform
options {
    client_id              = "asd"
    client_secret          = "asd"
    authorization_endpoint = "https://slack.com/oauth/authorize"
    scopes                 = ["identity.basic, identity.email, identity.avatar, identity.team"]
    token_endpoint         = "https://slack.com/api/oauth.access"
    scripts = {
      fetchUserProfile = "function....."
    }
  }
```

**Comment by sergiught** [comment]
As both @rene00 and @epintos describe above this seems to work and the issue was due to incorrect usage @erikburgess. I'm going to close this down because of this but in case of need please feel free to reopen.
