### ISSUE TITLE
Support for Hooks

### ISSUE THREAD

**Issue by daviddunkley** [alexkappa/terraform-provider-auth0#173]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would add to other comments you are awesome @alexkappa for maintaining this Provider and a god-send for my company. Terraform/Auth0 should give you better recognition.

I am sure you have it in your sights but I thought it would be useful for you/someone to measure the demand.

Auth0 has, finally, added support for [Hooks](https://auth0.com/docs/api/management/v2#!/Hooks) into the Management API. So obviously it makes sense to add it to the terraform provider.
We use Hooks heavily to add Custom Claims into our Client Credential tokens and currently, we have to copy and paste the code in the Auth0 Management Portal.

### New or Affected Resource(s)

* auth0_hook (doesn't exist yet)

### References

* https://auth0.com/docs/api/management/v2#!/Hooks

**Comment by alexkappa** [comment]
Hi David, thank you for your kind words :) If this project is valuable to you/your company please consider [sponsoring](https://github.com/sponsors/alexkappa) to help support the projects maintenance.

Hooks have been contributed to the project recently by @yinzara and await release. 

As the project is transitioning to https://github.com/terraform-providers/terraform-provider-auth0/ to be listed as an official provider, please be patient while we work through some moving pains.
