### ISSUE TITLE
Support samlp Connections

### ISSUE THREAD

**Issue by sarcasmboy** [alexkappa/terraform-provider-auth0#174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Auth0 provider doesn't appear to support `auth0_connection` resources with `strategy = "samlp"`

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

```hcl
resource "auth0_connection" "samlp" {
  name     = "samlp-connection"
  strategy = "samlp"

  options {
    signSAMLRequest    = true
    signatureAlgorithm = ...
    digestAlgorithm    = ...
    fieldsMap = {
      ...
    }
    idpinitiated = {
      ...
    }

    signInEndpoint = "https//..."
    signingCert    = ...
  }
}

```

### References

The documentation doesn't cover samlp connections very well, but it seems like the api can be reverse engineered by inspecting the requests with in the Auth0 management app.

* https://auth0.com/docs/api/management/v2#!/Connections/post_connections

**Comment by alexkappa** [comment]
Hi @sarcasmboy, to support SAML connections we'll need to implement options for it in the SDK first, as done in go-auth0/auth0/pull/104.

Then we are able to support it in the provider. Are you up for making a PR?
