### ISSUE TITLE
Be able to configure the auth0_connection to use when create a new auth0_client

### ISSUE THREAD

**Issue by drazul** [alexkappa/terraform-provider-auth0#178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have several applications in my tenant each one using different set of database connections for login.

I would like to have a way to configure which connections each  application will use.

By default Auht0 configure a new application to use all enabled connections in the tenant.

### New or Affected Resource(s)

* auth0_client

### Potential Terraform Configuration

```hcl
resource "auth0_client" "my_client" {
  name = "Application - Acceptance Test"
  description = "Test Applications Long Description"
  app_type = "spa"
  options =  {
    auth0_connections = [
      "my_database_connection"
    ]
  }
}
```

Note: I write the new key inside an options block because this option is not supported with non_interactive app type.

**Comment by yinzara** [comment]
This is unfortunately an aspect of how the Auth0 APIs work.  Clients don't have applications, applications have clients.  For you to add this client to a specific application, you would have to use an "auth0_connection" element and specify the 'enabled_clients' attribute as this client.

I know that's not the answer you were hoping for.  

The only other option would be to develop a new resource type that's something like "auth0_connection_enabled_client" that was really a meta resource for ensuring that a specific client is included in the list of enabled clients for a connection.    This would be similar to the google_project_iam_member (and related named resources) from the google cloud provider.

However doing this would class with the existing "enabled_clients" attribute of a connection (though I'd argue is actually more useful).
