### ISSUE TITLE
Crash on 0.7.0

### ISSUE THREAD

**Issue by maroux** [alexkappa/terraform-provider-auth0#181]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
→ tf version
Terraform v0.12.23
+ provider.auth0 v0.7.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* auth0_tenant
(I think?)

### Terraform Configuration Files

```hcl
resource "auth0_tenant" "tenant" {
  friendly_name = "My Company"
  picture_url   = "http://example.com/image.jpg"
  support_email = "support@example.com"
  support_url   = "https://example.com/contact/"

  enabled_locales = ["en"]

  flags {
    change_pwd_flow_v1                     = false
    disable_clickjack_protection_headers   = true
    enable_apis_section                    = false
    enable_client_connections              = false
    enable_custom_domain_in_emails         = false
    enable_dynamic_client_registration     = false
    enable_legacy_logs_search_v2           = false
    enable_pipeline2                       = false
    enable_public_signup_user_exists_error = true
    universal_login                        = true
  }

  universal_login {
    colors {
      page_background = "#000000"
      primary         = "#3370AC"
    }
  }

  session_lifetime = 0
  sandbox_version  = "8"

  lifecycle {
    # provider fails to ignore default HTML set by Auth0 and reports changes to "change_password.0.html"
    ignore_changes = [change_password]
  }
}
```

### Panic Output

https://gist.github.com/maroux/4f5917a54b6387f95dd2157af4ee7268

### Expected Behavior

- `terraform plan` should show changes

### Actual Behavior

- `terraform plan` crashed

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

1. Works fine on 0.5.2 - upgrading to 0.7.0 leads to this crash.

**Comment by alexkappa** [comment]
Hi @maroux I think I understand what the issue is. Thanks for reporting this. I'll work on a fix soon

**Comment by alexkappa** [comment]
@maroux thank you again for filing this issue. The v0.8.0 release should have you covered.

**Comment by maroux** [comment]
awesome, thank you for quick turnaround!
