### ISSUE TITLE
auth0_role doesn't support more than 50 granted permissions

### ISSUE THREAD

**Issue by sharkyze** [alexkappa/terraform-provider-auth0#188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```bash
Terraform v0.12.24
+ provider.auth0 v0.8.1
+ provider.aws v2.55.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* auth0_role

### Terraform Configuration Files

```hcl
resource "auth0_role" "admin" {
  name = "Admin Role - ${local.commodity}-${local.platform} - Managed by Terraform"

  dynamic "permissions" {
    for_each = var.webserver_common_permissions

    content {
      resource_server_identifier = auth0_resource_server.webserver.identifier
      name                       = permissions.value.value
    }
  }
}
```

### Expected Behavior
The provider should be able to retrieve all permissions granted by a role and not only the first 50 permissions.

### Actual Behavior
The provider fetches only the 50 first permissions granted by a role

### Steps to Reproduce

1. Add a new role with more than 50 permissions
2. Run `terraform apply`
3. Run `terraform apply` again

### Important Factoids
I fixed this issue locally by increasing the number of results per page on this line: https://github.com/alexkappa/terraform-provider-auth0/blob/3ab65a88037ab13f1044ff4740f7d0479ce43ab6/auth0/resource_auth0_role.go#L107

This works in our case because we have 97 permissions for the role causing the issue. This won't work for roles with more than 100 permissions.

I would be happy to send a PR to fix this if someone can help me figure out how to do pagination for the method `api.Role.Permissions` in https://github.com/go-auth0/auth0 without introducing breaking changes to the return type.

In meantime could I send a PR increasing the pagination to 100 results per page as a quick fix ?

**Comment by alexkappa** [comment]
Hi @sharkyze, thanks for reporting this. Seems like we should have used pagination when listing user roles.

Looks like the management API supports it so we should be good to go:

https://auth0.com/docs/api/management/v2#!/Users/get_user_roles

**Comment by sharkyze** [comment]
Hey @alexkappa, thank you for your getting back to me. I just saw you opened a PR for this on https://github.com/go-auth0/auth0.

Please let me know if you want me to send in the changes for this repository after you've merged your PR.

**Comment by alexkappa** [comment]
Hi @sharkyze, did you already work on making changes for this provider? The PR was merged. I haven't read your comment earlier so I worked on GH-206. My apologies if there was overlap.

**Comment by sharkyze** [comment]
Hey @alexkappa, no worries, thank you for the fix
