### ISSUE TITLE
Universal login page not working as expected

### ISSUE THREAD

**Issue by icadariu-talend** [alexkappa/terraform-provider-auth0#189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- 0.12.20

### Affected Resource(s)

* auth0_client

### Terraform Configuration Files

```hcl
resource "auth0_client" "global_client" {
  name                 = "Apps"
  description          = "Global Application"
  is_first_party       = true
  custom_login_page_on = true
  custom_login_page    = data.aws_s3_bucket_object.login_page.body
}
```

### Debug Output

- both plan and apply seems to work, i even see the page from the s3 bucket in the tfstate file under  `custom_login_page`

### Expected Behavior

- I would have expected that the Login Page from <https://mypage.auth0.com/dashboard/example_tenant/login_page> to be enabled and to see my `custom_login_page`.
![image](https://user-images.githubusercontent.com/46490120/77954291-b55fb800-72ce-11ea-9414-104fdf0335ad.png)

### Actual Behavior

- as you can see from the screenshot, Login page is disabled.

### Steps to Reproduce

1. `terraform apply`

### References

* Am I missing some parameters in order to configure this resource?

**Comment by alexkappa** [comment]
Hi @icadariu-talend, perhaps you need to use the `auth0_global_client` instead.

**Comment by icadariu-talend** [comment]
@alexkappa  I can try, but I didn't saw that resource in the list of resouces:
![image](https://user-images.githubusercontent.com/46490120/78012120-d06d0f00-7344-11ea-998f-e27875475e65.png)

**Comment by alexkappa** [comment]
Indeed, we missed it in the docs. We'll make sure to add it there.

**Comment by alexkappa** [comment]
Created #190 to track this.

**Comment by icadariu-talend** [comment]
@alexkappa  What is the purpose of these parameters under https://www.terraform.io/docs/providers/auth0/r/client.html 

```
custom_login_page_on - (Optional) Boolean. Indicates whether or not a custom login page is to be used.
custom_login_page - (Optional) String. Content of the custom login page.
custom_login_page_preview - (Optional) String. 
```

I guess the should be removed since we should deal with them inside `auth0_global_client`, or I am getting it wrong ?

**Comment by alexkappa** [comment]
This provider essentially mirrors the Auth0 Management API. Auth0 however creates a "global" client which is exactly the same as every other client, except its treated differently internally. Universal login is one example of how its treated differently.

Through a PR contributed to this provider recently, a special resource `auth0_global_client` has been created to affect this pre-generated client. As it behaves exactly the same way as this provider is concerned, their schema are also defined in the same way.

Perhaps under certain configuration, these parameters take effect with user generated clients. Or perhaps Auth0 might plan to use them somehow in the future. As I am not able to anticipate how this fields will be used, I'd rather keep them as is, and delegate what their usefulness to the management API and its documentation.

See: https://auth0.com/docs/api/management/v2#!/Clients/post_clients
