### ISSUE TITLE
Setting rule_id on an auth0_rule throws a 400

### ISSUE THREAD

**Issue by robertlagrant** [alexkappa/terraform-provider-auth0#193]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 0.12.24

### Auth0 Proovider Version

0.8

### Affected Resource(s)

* auth0_role

### Terraform Configuration Files

```hcl
resource "auth0_role" "custom_role" {
  role_id     = "custom-role"
  name        = "Custom Role"
  description = "An Auth0 Core Auth Role"

  permissions {
    name                       = "read:entity"
    resource_server_identifier = auth0_resource_server.entity_api.identifier
  }
}
```

### Expected Behavior

Rule is created or updated with rule_id as its id.

### Actual Behavior

On a create of a new rule, Terraform appears to plan the correct work.

On an update of an existing rule that has a generated ID, Terraform appears to correctly detect that the `role_id` is what is changing, from the current generated `id` value in Auth0 to the new value supplied.

However, in either case a 400 validation is thrown from the Auth0 API:

`Additional properties not allowed: id`

### Steps to Reproduce

Introduce a new rule in Terraform, OR modify an existing rule.

1. `terraform apply`

**Comment by alexkappa** [comment]
@robertlagrant seems like the behaviour of the Auth0 API doesn't allow setting an id post creation. Perhaps the right thing for this provider to do is force a new resource if the `role_id` has changed?

**Comment by robertlagrant** [comment]
@alexkappa I tried creating a new one :-) However, in both the create and the update cases, the same thing occurs.

**Comment by alexkappa** [comment]
I suppose this means we can’t set the rule_id field... I have to do some investigation and I’m away from my laptop. I can have a look next week.

**Comment by alexkappa** [comment]
Okay, apparently setting the id is not possible in [creating or updating](https://auth0.com/docs/api/management/v2#!/Roles/post_roles). I'll remove it.

I was thinking of marking it as deprecated but since it wouldn't have worked anyway, I will just remove it altogether.
