### ISSUE TITLE
Changes in configuration(on auth0_connection resource) are not detected

### ISSUE THREAD

**Issue by icadariu-talend** [alexkappa/terraform-provider-auth0#195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* 0.12.20

### Affected Resource(s)

* auth0_connection
* auth0 provider version: 0.6.0

### Terraform Configuration Files

```hcl
resource "auth0_connection" "my_connection" {
  name = "Example-Connection"
  strategy = "auth0"
  options {
    password_policy = "excellent"
    password_history {
      enable = true
      size = 3
    }
    brute_force_protection = "true"
    enabled_database_customization = "true"
    custom_scripts = {
      get_user = <<EOF
function getByEmail (email, callback) {
  return callback(new Error("Whoops!"))
}
EOF
    }

    configuration = {
      foo = "bar"
      bar = "baz"
    }
  }
}
```
### Expected Behavior

* in case  of changes in `configuration` block, `terraform plan/apply` won't detect any change.

### Steps to Reproduce

1. `terraform apply`

**Comment by icadariu-talend** [comment]
@alexkappa  I've see same behavior on other resources too, for example `auth0_rule`. 

Anything changed there is not detected by plan/apply. Any suggestion on a workaround?

**Comment by icadariu-talend** [comment]
@alexkappa  Any updates on this? Or does anyone has a solution how to push updates done on the `configuration` block ?

**Comment by alexkappa** [comment]
Hi @icadariu-talend, could you tell me what the changes were specifically within the configuration block? Could you upload a config that I can replicate in a gist (e.g. the config you create and the config you update)?

**Comment by alexkappa** [comment]
Also, which version are you running? `v0.9.3` seems to update the state correctly for me.

**Note**: there is a known bug/limitation where emptying a map will not trigger an update. This happens if you have created a `configuration` map previously but removed it or defined it as `{}`.

The go json package will not marshal an empty map so the update won't happen. I'll see if I can link an issue.

**Comment by icadariu-talend** [comment]
So right now I have tested using `auth0 provider version: 0.6.0` as for the resouce to test, you can use the one from above.  

For example changing these value will not trigger any update on `terraform plan/apply`

```sh
    configuration = {
      foo = "bar123"
      bar = "baz123"
    }

```

**Comment by alexkappa** [comment]
Could you try with the latest version and let me know if it works for you?

**Comment by icadariu-talend** [comment]
Yes, right now it's not possible for us to upgrade, but I will give it a try asap. Thank you!
