### ISSUE TITLE
auth0_client can not be created with missing or empty jwt_configuration.scopes object.

### ISSUE THREAD

**Issue by stefangreim** [alexkappa/terraform-provider-auth0#196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
terraform0.12.24; terraform-provider-auth0_v0.8.1

### Affected Resource(s)

* auth0_client

### Terraform Configuration Files

```hcl
resource "auth0_client" "this" {
  name = "${var.name}-${var.tenant_name}"
  description = "https://${aws_route53_record.tenant.fqdn}"
  app_type = "spa"

  token_endpoint_auth_method = "none"

  callbacks = ["https://${aws_route53_record.tenant.fqdn}/oauth2/idpresponse"]
  web_origins = ["https://${aws_route53_record.tenant.fqdn}"]
  allowed_origins = ["https://${aws_route53_record.tenant.fqdn}"]

  oidc_conformant = true

  jwt_configuration {
    lifetime_in_seconds = 36000
    secret_encoded = false
    alg = "RS256"
    scopes = {}
  }

  grant_types = [ "implicit", "authorization_code", "refresh_token" ]
}
```

### Panic Output

```
 Error: 400 Bad Request: Payload validation error: 'Expected type object but found type null' on property jwt_configuration.scopes (Configuration related to id token claims for the client).
   on auth0.tf line 18, in resource "auth0_client" "this":
   18: resource "auth0_client" "this" {
```

### Expected Behavior

The auth0_client resource can be created with no or empty scope element in jwt_configuration.

### Actual Behavior

The terraform apply results in the error above.
Earlier versions of the provider (tested with v0.5.2) were able to create the resource correctly. The current provider is not able to create the resource if the scope element in jwt_configuration is empty or missing. If you create the auth0_client with a dummy scope you can provide an empty scope object on update.

### Steps to Reproduce

1. Use the configuration above.
2. `terraform apply`

**Comment by fotos** [comment]
Stumbled upon the same problem. 💥 

I want to terraform a client without any `jwtConfiguration.scopes`.

The `Auth0` API currently allows the creation of a client with the following payload:

```
{
	"name": "Test",
	"description": "Test SPA",
	"logo_uri": "",
	"callbacks": [
		"http://localhost:3000"
	],
	"allowed_origins": [
		"http://localhost:3000"
	],
	"web_origins": [
		"http://localhost:3000"
	],
	"client_aliases": [],
	"allowed_clients": [],
	"allowed_logout_urls": [
		"http://localhost:3000"
	],
	"grant_types": [
		"implicit",
		"authorization_code",
		"refresh_token"
	],
	"token_endpoint_auth_method": "none",
	"app_type": "spa",
	"is_first_party": true,
	"oidc_conformant": true,
	"sso": false,
	"cross_origin_auth": false,
	"sso_disabled": false,
	"custom_login_page_on": true,
	"initiate_login_uri": "",
	"jwt_configuration": {
		"alg": "RS256",
		"lifetime_in_seconds": 36000
	}
}
```

The `scopes` need to be `null` otherwise I'm getting errors from `/authorize` when trying to implement `passwordless` authentication.

It seems that the management API does not offer a way to update a client and remove the `scopes` from the `jwt_configuration` object therefore the workaround of creating a dummy scopes and making it empty again does not work.

I think, if there are no scopes defined, the `scopes` key needs to be missing completely?

## Terraform configuration

```
resource "auth0_client" "auth" {
  name        = "Auth"

  app_type = "spa"

  is_first_party             = true
  token_endpoint_auth_method = "none"

  custom_login_page = true

  callbacks                   = local.auth_callbacks
  allowed_logout_urls  = local.auth_allowed_logout_urls
  allowed_origins         = local.auth_allowed_origins
  web_origins               = local.auth_web_origins

  grant_types = [
    "implicit",
    "authorization_code",
    "refresh_token"
  ]

  oidc_conformant = true

  jwt_configuration {
    alg                 = "RS256"
    lifetime_in_seconds = 36000
  }
}
```

## Versions

```
$ terraform version
Terraform v0.12.24
+ provider.auth0 v0.8.2
```

**Comment by alexkappa** [comment]
Thank you for reporting this @stefangreim @fotos. I will have a look very soon.

Cheers,
Alex

**Comment by alexkappa** [comment]
I believe the issue has been addressed in the linked PR. Release to follow shortly (0.9.1).

Keep in mind there is a long standing bug where clearing slice/map values are not handled correctly and will result in errors due to diff not matching expectations. This was not addressed here.

**Comment by fotos** [comment]
Just had a chance to test it. Now it works! 🙌

Thanks a lot @alexkappa! 🙏
