### ISSUE TITLE
Changes in auth0_connection configuration are not applied correctly

### ISSUE THREAD

**Issue by maroux** [alexkappa/terraform-provider-auth0#200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.23
+ provider.auth0 v0.5.2
+ provider.template v2.1.2
```

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "global_db" {
  name     = local.global_db_connection_name
  strategy = "auth0"

  is_domain_connection = false

  options {
    password_policy = "good"

    brute_force_protection         = true
    enabled_database_customization = true
    disable_signup                 = false
    import_mode                    = false
    requires_username              = false

    custom_scripts = {
      login    = file("${path.module}/db_scripts/login.js")
      create   = file("${path.module}/db_scripts/create.js")
      get_user = file("${path.module}/db_scripts/getUser.js")
    }

    configuration = {
      DB_CERT        = var.db_cert
      DB_CERT_KEY    = var.db_cert_key
      DB_HOSTNAME    = var.db_hostname
      DB_NAME        = var.db_name
      DB_PASSWORD    = var.db_password
      DB_SERVER_CERT = var.db_server_cert
      DB_USER        = var.db_user
    }
  }
}

```

### Expected Behavior

When no changes are done to configuration, it shouldn't be changed.

### Actual Behavior

Even if no changes are done to the configuration, some values get clobbered with plaintext containing encrypted text instead. This is evidenced by Auth0 logs failing with things like
```
password authentication failed for user \"2.0$fbebd8e....\"
```

### Steps to Reproduce

1. `terraform apply`

**Comment by maroux** [comment]
I suspect this is a problem with Auth0 API rather than the plugin.

**Comment by alexkappa** [comment]
@maroux, the configuration variables are encrypted by auth0 server side (irreversibly) for security reasons. Therefore this provider is not able to read back the plaintext values from the API.

Although I don't believe this is a bug (it's really a feature), the provider doesn't seem to do the right thing always. I'll see if this can be improved somehow. Suggestions or attempts welcomed! :)

**Comment by maroux** [comment]
I believe there are 2 solutions. You could store two values for every configuration value. One value would store plaintext specified at creation time. Another would store the encrypted value returned by the API. When updating you'd use the plaintext value, and when determining `hasChange` you'd use the encrypted value. (I'm not entirely sure how import works in this case - perhaps it won't be importable if there are secret values?)

Another solution is to simply never update configuration values if they are encrypted (just check prefix). This lets users specify new values but not delete them. Import works fine in this case since all existing secrets would simply be ignored by the updates.

As it stands currently, the resource is unusable if you have secret configuration values. I've had to write a companion bash script that would "fix" the secret values after the resource updates it.

**Comment by alexkappa** [comment]
> You could store two values for every configuration value.
An example of this would be useful in order to validate this approach. Do you know of any other providers that do this?

> I'm not entirely sure how import works in this case.
The import won't work in either case as the value coming back from the API is encrypted, therefore we would never have the plaintext value.

> Another solution is to simply never update configuration values if they are encrypted.
We are doing this actually with a `DiffSuppressFunc`. 

```
func(k, old, new string, d *schema.ResourceData) bool {
	return strings.HasPrefix(old, "2.0$") || new == old
}
``` 
Perhaps it doesn't cover all cases?

Anyway, to make some sense of this we need some tests that trigger this behaviour. Then we can see how to implement a fix.

**Comment by alexkappa** [comment]
@maroux did you happen to import this resource initially?

I've added a test that verifies this behavior but I wasn't able to reproduce. See the tests here:
https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_connection_test.go#L596-L655

**Comment by maroux** [comment]
Hi @alexkappa No, this resource was created using Terraform. Oddly some config values are unaffected - I suspect this may be a config value size issue? Can you try with a longer config value - for example we have an ssl cert / private key in there..

**Comment by maroux** [comment]
`DiffSuppressFunc` simply suppresses diff in Terraform. The plugin still tries to [write](https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_connection.go#L437) all configuration values instead of not passing that key at all.

**Comment by alexkappa** [comment]
> Can you try with a longer config value - for example we have an ssl cert / private key in there..

Tests pass with larger values as well as using the keys from your example.

```
configuration = {
	DB_CERT        = file("path/to/cert.pem") # ~55kb
	DB_CERT_KEY    = file("path/to/key.pem")
	DB_HOSTNAME    = "my_hostname"
	DB_NAME        = "my_name"
	DB_PASSWORD    = "my_password"
	DB_SERVER_CERT = "my_server_cert"
	DB_USER        = "my_user"
}
```

If you are able to provide an example that triggers this behavior I can look into it further. Otherwise, I can't reproduce the issue.

**Comment by maroux** [comment]
Hm I just tried and could reproduce it easily:
Steps:
1. Commented out my bash script that makes PATCH connection API call
2. Made this change to one of the scripts:
```
  	for (const key of ['BCRYPT_ROUNDS', 'DB_CERT', 'DB_CERT_KEY', 'DB_HOSTNAME', 'DB_NAME', 'DB_PASSWORD', 'DB_SERVER_CERT', 'DB_USER', 'PEPPER']) {
      if (configuration[key].startsWith("2.0$")) {
		    return callback(Error("invalid value for configuration: '" + key + "', value: '" + configuration[key] + "'"));
      }
    }
```
3. Applied terraform
4. Hit "Try" in the script in Dashboard:
```
"invalid value for configuration: 'BCRYPT_ROUNDS', value: '2.0$4a8d56837978b...'"
```
5. Fix that value using UI
6. Hit "Try" again:
```
"invalid value for configuration: 'DB_CERT', value: '2.0$6a9bc2241f95...'"
```

I'm not sure if your test includes verifying the plaintext value in custom script in the dashboard?

I'm also not sure how to share this case with you - are you able to create a tenant and provide me access such that I can try to apply changes to it using Terraform?

**Comment by alexkappa** [comment]
Hi @maroux higher up in the comments I’ve linked to the additional tests I’ve added to the provider in order to verify this issue. 

Also inspected the calls to the Auth0 API and all POST/PATCH requests include the plaintext values, not the mangled/encrypted values. 

Using TF_LOG=1 and AUTH0_DEBUG=1 terraform will print more information on what it’s doing. Could you upload that in a gist?

**Comment by maroux** [comment]
Ah I see this in the logs:
```
2020/04/19 20:44:49 [WARN] Provider "registry.terraform.io/-/auth0" produced an unexpected new value for module.tenant_play.auth0_connection.global_db, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .options[0].configuration: inconsistent values for sensitive attribute
```

Here's the [full gist](https://gist.github.com/maroux/5419b617ec8af9ad7c2521117c72a7fe).

**Comment by maroux** [comment]
Observations: All the config values hashes changed in the PATCH call even though none of the values changed. Only some of the values got clobbered incorrectly.

**Comment by maroux** [comment]
Test linked [earlier](https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_connection_test.go#L596-L655) seems to indicate that the state file contains plaintext values? However that doesn't appear to be true for me.. Additionally, the test doesn't verify the plaintext value stored by Auth0 - I'm not even sure how how automated test could verify that 😕

**Comment by alexkappa** [comment]
@maroux in the gist, I can only see the PATCH request. If the value in your terraform state has been clobbered at some point, whatever happens afterwards will not reverse the values.

I've created a PR for this, just to make sure no value is ever read back from the API when it comes to configuration. So the value from the terraform configuration should always be what's in the state. This means however we cannot detect drift (it wasn't possible anyway) and we also cannot import configuration parameters.

Either way, I believe you will need to recreate your configuration as the values in the state are now clobbered. They have to get back to their original plaintext form.

**Comment by maroux** [comment]
Gotcha. Would manually mucking with state file fix it?

**Comment by maroux** [comment]
Update: mucking around with state file doesn't fix it. I guess I'll have to wait for this update to be released and upgrade provider version.

**Comment by alexkappa** [comment]
Ok, 0.9.2 was released yesterday. This should never read configuration values back.
