### ISSUE TITLE
Payload validation error: 'Missing required property: value' on property scopes[8]

### ISSUE THREAD

**Issue by dancrumb** [alexkappa/terraform-provider-auth0#203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.12.24

### Affected Resource(s)

* auth0_resource_server

### Terraform Configuration Files

```hcl
locals {
  scopes = {
    "appointment:read"   = "Read Appointments"
    "appointment:update" = "Update Appointments"
    "patient:search"     = "Search Patients"
    "file:upload"        = "Upload files"
    "file:download"      = "Download files"
    "medicalHome:update" = "Modify Medical Home information"
    "addendum:create"    = "Upload files"
    "admin:access"       = "Access Admin functions"
    "provider:create"    = "Create a Provider account"
  }
}

resource auth0_resource_server "ahana_api" {
  name                                            = "Ahana API"
  identifier                                      = "https://ahanapediatrics.com/api"
  token_lifetime                                  = 300
  skip_consent_for_verifiable_first_party_clients = true
  allow_offline_access                            = false
  signing_alg                                     = "RS256"

  dynamic scopes {
    for_each = local.scopes
    content {
      value       = scopes.key
      description = scopes.value
    }
  }
}
```

### Debug Output

Plan and Apply logs here: https://gist.github.com/dancrumb/7dc7a6a0974b7d903e34466fd77accc0

### Expected Behavior

API resource should have been updated

### Actual Behavior

Got error:
```
Error: 400 Bad Request: Payload validation error: 'Missing required property: value' on property scopes[8].

  on auth0.tf line 100, in resource "auth0_resource_server" "ahana_api":
 100: resource auth0_resource_server "ahana_api" [4m{
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nope

**Comment by alexkappa** [comment]
Hi Dan, which version of the provider are you using (use `terraform version` to find out)?

Could you run a minimal example with just the offending configuration and upload the logs in a gist? Leave other resources out such as aws. 

Use `TF_LOG=DEBUG AUTH0_DEBUG=1 terraform apply` to get the most output to help me debug.

**Comment by dancrumb** [comment]
Hey Alex,

Unfortunately, I'm using the Terraform cloud app, so I can't run those easily. It'll take a little time to set up an SSCCE.

I can say I have the Auth0 provider set up thus, If that helps:

```
provider "auth0" {
  domain        = var.auth0_domain
  client_id     = var.auth0_mgmt_client_id
  client_secret = var.auth0_mgmt_client_secret
  version       = ">=0.7"
}
```

**Comment by dancrumb** [comment]
OK - I updated the gist with the stripped down config and the logs.

I was able to create the new API in my first pass through. 

It appears the bug only occurs when trying to update the API with a new scope.

**Comment by alexkappa** [comment]
Hi Dan, your issue seems to be related to #197. Could you try using the latest version 0.9.0?

**Comment by dancrumb** [comment]
I'll try it out today and get back to you

**Comment by dancrumb** [comment]
Yup - that fixed it! 

Thanks
