### ISSUE TITLE
Modification of Hook causes triggerId error

### ISSUE THREAD

**Issue by nitrag** [alexkappa/terraform-provider-auth0#209]
Problem:
Cannot modify Hook.

Error:
`Additional properties not allowed: triggerId`

I didn't have my version fixed. It was set to '~> 0.8', however 0.9.2 was initialized. I don't see that release in GitHub release section - was this supposed to be released?

```
- Downloading plugin for provider "auth0" (terraform-providers/auth0) 0.9.2...
....
  # module.auth0.auth0_hook.update_app_scope will be updated in-place
  ~ resource "auth0_hook" "update_app_scope" {
        enabled    = true
        id         = "auth-0-hook-update-app-scope"
        name       = "auth-0-hook-update-app-scope"
      ~ script     = <<~EOT
          my codes
        EOT
        trigger_id = "credentials-exchange"
    }
...
Error: 400 Bad Request: Payload validation error: 'Additional properties not allowed: triggerId'.

  on 04-Auth0/hooks.tf line 1, in resource "auth0_hook" "update_app_scope":
   1: resource "auth0_hook" "update_app_scope" {
```

I hardcoded version to 0.8.2 and modification was successful.

**Comment by alexkappa** [comment]
Hi @nitrag, thanks for submitting this issue. I've been able to reproduce it and I'm working on a fix. Will update soon.

**Comment by alexkappa** [comment]
@nitrag look out for the upcoming 0.9.3 release [here](https://releases.hashicorp.com/terraform-provider-auth0/).
