### ISSUE TITLE
Attachment Resources, e.g. auth0_role_permission_attachment and auth0_user_role_attachment

### ISSUE THREAD

**Issue by WilliamABradley** [alexkappa/terraform-provider-auth0#213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This allows you to re-use existing roles and attach permissions to them. This is helpful if you have roles in a Tenant, and multiple applications, that you want to attach permissions to the Role.

Attaching a Role to an existing User is also a useful resource.

### New or Affected Resource(s)

* auth0_role_permission_attachment 
* auth0_user_role_attachment

### Potential Terraform Configuration

```hcl
resource "auth0_role_permission_attachment" {
    role = "USER"
    resource_server_identifier = auth0_resource_server.audience.identifier
    permission = "VIEW:USER"
}

resource "auth0_user_role_attachment" {
    role = "USER"
    user_id = "12345"
}
```

### References

* Much like how the AWS Provider provides attachments: https://www.terraform.io/docs/providers/aws/r/iam_user_policy_attachment.html

**Comment by alexkappa** [comment]
Hi @WilliamABradley, we do support the creation of user roles and role permissions already in this provider. Have a look at this [example of a user role](https://github.com/alexkappa/terraform-provider-auth0/blob/master/example/user/main.tf), or this [example of role permissions](https://github.com/alexkappa/terraform-provider-auth0/blob/master/example/role/main.tf). 

Is there something you are not able to do with the provider as it is?

**Comment by WilliamABradley** [comment]
@alexkappa My use case is when a tenant has roles, and multiple environments (Dynamic amount). When Environments are created with Terraform, I want to associate the resource_server for that environment with the existing role.

Alternatively, I could prefix a Role for multiple environments, which I am doing now, however, there are some existing shared seed users that I would like to associate with my environment's role. So I would need to associate an existing user, with a new role.

This strategy of _attachment resources are common in AWS, as this kind of situation happens.

**Comment by alexkappa** [comment]
> When Environments are created with Terraform

What do you mean by this? As far as I can tell environments are not supported by this provider.

An environment is essentially labelling a tenant, right? So you have users/roles in various tenants?

> Alternatively, I could prefix a Role for multiple environments

I'm sorry but I don't follow. Are you able to share a minimal configuration as an example?

**Comment by WilliamABradley** [comment]
@alexkappa Sorry about that :)

What I meant by environment is in development environment, not a concept of Auth0, e.g. prod, staging, test, etc.

What I am trying to achieve is:

Say I have a tenant called: app-test-tenant,

Inside this tenant I want to create execute Terraform multiple times, to create multiple test environments inside.

So I set up some shared Auth0 Roles in the Auth0 Dashboard.

Then once the Tenant is set up, I will use a Terraform Module that I can pass in a variable named `environment`, and use that to create an `auth0_client`, `auth0_resource_server`, and then apply the permission scopes from the `auth0_resource_server` to the Auth0 Role I created previously.

That module can be run multiple times with a different environment variable, so that multiple environments can be created inside my Auth0 Tenant.

Does that make sense? If not, I can make up some psuedocode.

**Comment by alexkappa** [comment]
I think I understand now, thanks for clarifying.

To see if I get this right, you have a fixed set of roles, and you want to create clients / resource servers at will, while re-using the roles you have? Also creating some seed users for each of the created client / resource servers?

Since roles are global to the auth0 tenant and permissions are scoped to a resource server, you need a way to create "attachments" per client / resource server pair. Is that right?

**Comment by WilliamABradley** [comment]
Correct! 
Although some seed users are also be global to the auth0 Tenant, that covers the use case.

**Comment by alexkappa** [comment]
Ok, I see. It's a valid problem, which may come with a significant overhead to this provider. I'll have to think about the approach here, including possible migrations or allowing multiple ways of defining user -> role or role -> permission attachments.

This is what we have now:

```hcl
resource "auth0_role" "admin" {
	name = "admin"
	description = "Administrator"
}

resource "auth0_user" "user" {
  ...
  roles = [ auth0_role.admin.id ]
}
```

The `iam_policy_attachment` equivalent and more in-line with the auth0 sdk. This is 1 user to N roles:

```hcl
resource "auth0_role" "admin" {
  name = "admin"
  description = "Administrator"
}

resource "auth0_user" "user" {
  name = "Bob"
}

resource "auth0_user_roles" "user" {
  name = auth0_user.user.id
  roles = [ auth0_role.admin.id ]
}
```

The `iam_user_policy_attachment` which is what you suggest using each attachment to describe a single connection between a user <-> role (1 to 1):

```hcl
resource "auth0_role" "admin" {
  name = "admin"
  description = "Administrator"
}

resource "auth0_user" "user" {
  name = "Bob"
}

resource "auth0_user_role" "user" {
  name = auth0_user.user.id
  role = auth0_role.admin.id
}
```

The thing with this approach is the verbosity or overhead of defining a resource per pair. If we are able to support this, we should hopefully allow people to still be able to use the provider as they currently do. So managing this will be a challenge.

**Comment by WilliamABradley** [comment]
Looks good, to prevent over verbosity, you could use for_each.

```hcl
locals {
  admins =  ["Bob", "Bill"]
}

resource "auth0_user" "admins" {
  for_each = local.admins
  name = each.value
}

resource "auth0_user_role" "admin_role" {
  name = "ADMIN"
}

resource "auth0_user_role_attachment" "admins" {
  for_each = auth0_user.admins

  user_id = each.value.id
  role_id = auth0_user_role.admin_role.id
}
```

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/16 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
