### ISSUE TITLE
Changing the key of a "auth0_rule_config" doesn't update Auth0

### ISSUE THREAD

**Issue by multani** [alexkappa/terraform-provider-auth0#214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.24
+ provider.auth0 v0.9.3
```
### Affected Resource(s)

* auth0_rule_config

### Terraform Configuration Files
I tried to change my configuration from:

```hcl
resource auth0_rule_config "namespace" {
  key   = "ns"
  value = "http://example.com"
}
```
to:
```hcl
resource auth0_rule_config "namespace" {
  key   = "namespace"
  value = "http://example.com"
}
```

### Expected Behavior

This should change the previously configured `ns` rules configuration key to `namespace`.

### Actual Behavior

The key doesn't change.

### Steps to Reproduce

Once the key has been initially created, the Terraform configuration was changed as shown above: the `key` field was changed from `ns` to `namespace`.

Applying that modification produces:

```
Terraform will perform the following actions:

  # auth0_rule_config.namespace will be updated in-place
  ~ resource "auth0_rule_config" "namespace" {
        id    = "ns"
      ~ key   = "ns" -> "namespace"
        value = (sensitive value)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

auth0_rule_config.namespace: Modifying... [id=ns]
auth0_rule_config.namespace: Modifications complete after 0s [id=ns]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Subsequent plans always show:

```
  # auth0_rule_config.namespace will be updated in-place
  ~ resource "auth0_rule_config" "namespace" {
        id    = "ns"
      ~ key   = "ns" -> "namespace"
        value = (sensitive value)
    }
```

And the rules configuration still has the `ns` key in Auth0.

**Comment by alexkappa** [comment]
@multani I think this is a bug and we should fix it. As the management api doesn't accept changing a config key we should force a delete/create when changes occur on keys.

Will send a PR soon.
