### ISSUE TITLE
Setting up a facebook connection

### ISSUE THREAD

**Issue by stuartizon** [alexkappa/terraform-provider-auth0#217]
Do you have any docs about how to set up a facebook login connection with this provider? I've tried the following but it's not picking up the scopes or the app id:

```
resource "auth0_connection" "facebook" {
  name     = "facebook"
  strategy = "facebook"
  options {
    app_id = var.facebook_app_id
    configuration = {
      public_profile = true
      email = true
    }
  }
}
```

Is that the correct syntax?

**Comment by gagalago** [comment]
linked to https://github.com/alexkappa/terraform-provider-auth0/issues/219

**Comment by alexkappa** [comment]
Hi @stuartizon some providers were not implemented as I was deferring to the community to help me prioritize.

After a recent refactoring of the connection resource at go-auth0/auth0 I didn’t have a lot of time on my hands to fully finalize.

These providers would be fairly easy to support. If you feel adventurous feel free to submit a PR 🙂

**Comment by alexkappa** [comment]
@stuartizon the docs should be more comprehensive now with exact provider supported options. 

Feel free to check it out here: https://www.terraform.io/docs/providers/auth0/r/connection.html#facebook

**Comment by stuartizon** [comment]
Thanks so much. That's great!
