### ISSUE TITLE
 Lack of support for some connection providers options

### ISSUE THREAD

**Issue by relu** [alexkappa/terraform-provider-auth0#219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I noticed the connection options for certain providers are [commented out](https://github.com/terraform-providers/terraform-provider-auth0/blob/master/auth0/structure_auth0_connection.go#L10) in the  (interested in Facebook and Linkedin). I was wondering why that is the case and if there are plans to implement support for these.
I would be happy to work on this myself but would like to get some context before digging into it.

### New or Affected Resource(s)

* auth0_connection

**Comment by relu** [comment]
A suggestion for a future provider major version would be to deprecate the existing `auth0_connection` resource and replacing it with individual connection resources per connection type e.g. `auth0_connection_google`, `auth0_connection_facebook`, `auth0_connection_auth0` etc.
This approach would be a lot easier to manage considering the fact that most of these connection types have very different configuration options which would make the case for implementing different terraform schemas for each of them hence improving the clarity of the implementation and preventing state pollution.

**Comment by alexkappa** [comment]
Hi @relu, after a major refactoring of the connections object with the sdk, I just haven't had the time to match the parity with this provider. We can tackle these soon, unless you are feeling up for submitting a PR ;)

**Comment by alexkappa** [comment]
> I would be happy to work on this myself but would like to get some context before digging into it.

Excellent! Both of these providers are very similar (oauth2 based) so you should be able to find examples ready. Off the top of my head `google-oauth2` is similar.

What you'd need to do is add any additional fields to the schema, and fill in the appropriate flatteners/expanders inside the `structure_connection.go` file. There are more examples there.

Some attention needed with the `scope` field. Its best to use the sdk's `SetScopes` method. The `google-oauth2` option should have you covered. Also, see PR #216 and #215 code/reviews.

Ping me if there's anything I can help with!
