### ISSUE TITLE
auth0_tenant - creates a TF resource without creating an actual tenant

### ISSUE THREAD

**Issue by jsokol89** [alexkappa/terraform-provider-auth0#225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.auth0 v0.9.3

### Affected Resource(s)

* auth0_tenant

### Terraform Configuration Files

```
resource "auth0_tenant" "test-tenant-unique-string-123" {
  friendly_name = "Test Tenant 123"
  session_lifetime = 60
}
```

### Debug Output

https://gist.github.com/jsokol89/d28a8c3e693e631188f5ee1137343733

### Expected Behavior

New tenant _test-tenant-unique-string-123_ to be created.

### Actual Behavior

No tenant has been created.
I could still use the same tenant name to create a new tenant via Auth0 web app.
Once resource was manually created the TF resource was still unable to apply any modifications to the tenant (event though TF output was suggesting otherwise)

### Steps to Reproduce

1. Create a very basic tenant TF declaration as per above (with unique-enough name as the tenant name has to be globally unique)
2. Apply using your own client-id and client-secret
3. Verify if the new tenant has been created.

### Other concerns

1. When creating the tenant manually via the web app I'm asked to select a region (Australia/Europe/US) - this doesn't seem to be available within the terraform provider.
2. I assume the tenant name is determined by the resource name (as there is no other way to declare the name in the auth0_tenant documentation). This can cause significant issues for multi-tenant setups where tenant name would vary depending on TF config variables.

**Comment by alexkappa** [comment]
Hi @jsokol89 this provider can do what is available through the management API thus far, and creating tenants unfortunately is not supported.

The tenant resource, is a special kind of resource as far as this provider is concerned. As such, we treat tenants as existing resources. It can read/update your tenant but cannot create/delete.

**Comment by jsokol89** [comment]
Thanks for a prompt response @alexkappa
It all makes sense now and after splitting each tenant to use it's own client-id and client-secret the update part started to work. Cheers!
