### ISSUE TITLE
Document how to import resources

### ISSUE THREAD

**Issue by kvrhdn** [alexkappa/terraform-provider-auth0#230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation on [terraform.io/docs](https://www.terraform.io/docs/providers/auth0/index.html) does not mention anything about importing resources. But I found out by looking in the code that it is indeed supported.

Could we add documentation to clarify this? It was for instance not super clear to me at first that I had to import a resource by its ID (which I can't find in the Auth0 UI...) instead of by its name.

I would expect something similar to the AWS provider, for example: https://www.terraform.io/docs/providers/aws/r/db_instance.html#import

**Comment by guillermo-menjivar** [comment]
While this does not solve the issue on hand, I found using the management API as a means to find the ID of resources that I needed to import
https://auth0.com/docs/api/management/v2

**Comment by kvrhdn** [comment]
Oh, I didn't know about that! I used to grab it from the URL:
<img width="752" alt="Screenshot 2020-06-18 at 10 26 42" src="https://user-images.githubusercontent.com/7748404/84997255-9c88d500-b14e-11ea-9236-ab7f0d20c107.png">

**Comment by alexkappa** [comment]
Re-opening this issue as a lot of people seem to agree there is some work needed to clarify the docs. FWIW some resources are already documented, but we'll need to make sure its present for all resources.

**Comment by red8888** [comment]
any updates on this? Im not familiar enough with terraform code to see how to import these resources

**Comment by red8888** [comment]
![image](https://user-images.githubusercontent.com/6265399/119725411-e76e9a80-be3d-11eb-91eb-8e5d1b64caf2.png)

I can't see what the ID is I need for importing the auth0_client_grant resource from the code

**Comment by red8888** [comment]
when I do a state show I see the ID but im not sure where its coming from

```
# auth0_client_grant.my_client_grant:
resource "auth0_client_grant" "my_client_grant" {
    audience  = "https://api.example.com"
    client_id = "<CLIENT_ID>"
    id        = "cgr_eNOnJW0UNT9XpyKi" <= where is this coming from? 
    scope     = [
        "test:foo",
        "test:bar",
    ]
}
```

**Comment by red8888** [comment]
I can see the ID is computed and it appears to be not possible to import it

**Comment by SamuelGarratt** [comment]
@red8888 I managed to get around that by modifying the state file directly (not the best approach) by observing the id from the UI and updating the state file with it. 

I would not recommend setting the `id` field in terraform directly as that would be problematic if you use the same code for different environments.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/17 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
