### ISSUE TITLE
terraform plan reports "Error: a number is required"

### ISSUE THREAD

**Issue by dancrumb** [alexkappa/terraform-provider-auth0#234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Running on the Terraform Cloud
Version is v 0.12.24

### Affected Resource(s)

Nothing obvious was pointed to in the initial logs. Running with TF_LOG=TRACE implicates:

* auth0_connection.support-team

### Terraform Configuration Files

I'll provide a link shortly

### Debug Output

Running `terraform plan` results in the cryptic error: `Error: a number is required`.

The TRACE logs have this telling line:

```
2020/05/12 19:50:40 [TRACE] UpgradeResourceState: schema version of auth0_connection.support-team is still 0; calling provider "registry.terraform.io/-/auth0" for any other minor fixups
```

### Panic Output

none

### Expected Behavior

Plan should work with no errors or provide a useful error

### Actual Behavior

Plan returns a cryptic error

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing weird

**Comment by dancrumb** [comment]
Zip files, encrypted with the Hashicorp key are available at https://ahanapediatrics.box.com/s/02eelsiwciph0zo3il0s5l7s5825mx45

**Comment by alexkappa** [comment]
Hi Dan,

This issue seems to be due to a schema change I’ve introduced in v0.10.0. I
am working on this issue and should be able to have a fix by tomorrow.

My apologies for the inconvenience. For the time being, you can pin your
version to a previous release.

**Comment by incorrupt** [comment]
@dancrumb and others in the future who may have the same issue, I edited the tfstate manually fixing my issue (in my case I had to use `scopes` instead of `scope`).

To find out where the error is, run `TF_LOG=true terraform plan` and look towards the bottom where the error is happening.

**Comment by alexkappa** [comment]
Release [0.10.1](https://github.com/terraform-providers/terraform-provider-auth0/blob/master/CHANGELOG.md#0101-unreleased) should resolve this issue. If not, feel free to reopen the issue.

**Comment by dancrumb** [comment]
Looks good to me! Thanks, as ever!!
