### ISSUE TITLE
How can I work with the auto-created Google connection?

### ISSUE THREAD

**Issue by nirvdrum** [alexkappa/terraform-provider-auth0#235]
As far as I can tell, Auth0 auto-creates a Google connection named "google-oauth2" when then tenant is created. I'm trying to customize this connection with:

```terraform
resource "auth0_connection" "google-oauth2" {
  name = "google-oauth2"
  strategy = "google-oauth2"

  enabled_clients = [
    auth0_client.ctcaas_explorer.id,
    auth0_client.ctcaas_graph.id,
    auth0_client.ctcaas_ctweb.id,
    auth0_client.terraform.id
  ]
}
```
But, that tries to create a connection with the name "google-oauth2" and thus leads to the error:

```
Error: 409 Conflict: A connection with the same name already exists

  on auth0.tf line 317, in resource "auth0_connection" "google-oauth2":
 317: resource "auth0_connection" "google-oauth2" {
```

Is it possible to import or customize existing connections? I can always create a new one with a different name, but then I have the auto-created one just hanging around, adding confusion to anyone looking at the dashboard.

**Comment by alexkappa** [comment]
Hi @nirvdrum, you can use `terraform import` in order to import the connection into your terraform state.

You could run the following command:
```
terraform import auth0_connection. google-oauth2 <connection-id>
```

The connection id should look something like `con_a17f21fdb24d48a0`. I'll be adding this to the documentation soon as its not there at the moment.

If you instead want to create another google oauth2 connection, just use a unique name.

Thanks!
Alex

**Comment by nirvdrum** [comment]
Thanks. I figured that part out, but forgot to comment here. I ran into a separate problem when importing whereby the `allowed_audiences` value, which should be an array, coming back as `""` from the Auth0 API, and thus was unable to decode properly by the provider. I started going down the path of fixing it, but I don't really know Go all that well and writing a custom JSON unmarshal for that one field was beyond my current capabilities.

I've opted to write a script using the Auth0 API to delete any connections with an empty application list and then let the provider recreate the connection. This appears to work, although the Auth0 UI doesn't properly reflect all changes made through the provider/API.

**Comment by nirvdrum** [comment]
Just to note for anyone else, while you can create a second named _google-oauth2_ connection, it will not appear in the Auth0 UI under the _Connections -> Social_ list. You will see in on the _Connections_ tab for each application, but not from the master connections list. While all changes should be driven from Terraform, it's often useful to verify things by looking at the UI. For that reason, I recommend either importing the existing connection or deleting and recreating the existing connection with the exact same name (`google-oauth2`) or your Connections list is going to be fairly confusing.

**Comment by alexkappa** [comment]
Good point! I'll add a note to the docs mentioning this as well.
