### ISSUE TITLE
Unable to specify username requirements 

### ISSUE THREAD

**Issue by etwillbefine** [alexkappa/terraform-provider-auth0#238]
### Description

Im unable to configure my Auth0 Connection with username restrictions and even with the `requires_username` flag.

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

1. Issue (require a username at all)
```hcl
resource "auth0_connection" "conn" {
  strategy = "auth0"
  ...

  options {
    requires_username = true
  }
}
```

2. Issue (specify username validation)
```hcl
resource "auth0_connection" "conn" {
  strategy = "auth0"
  ...

  options {
    requires_username = true

    validation = {
       username = {
          min  = 3
          max = 20
       }
    }
  }
}
```

Terraform error:
> Inappropriate value for attribute "validation": element "username": string
required.

Using for example `jsonencode` for validation.username ends up in an Auth0 Api Error:
> Error: 400 Bad Request: Payload validation error: 'Expected type object,null but found type string' on property options.validation.username.

### Expected Behavior

- `requires_username` is correctly send to Auth0 API
- Username validation can be specified
- `validation` has the correct type description in [Terraform docs](https://www.terraform.io/docs/providers/auth0/r/connection.html) (validation says its a string)
  - Using string for validation ends up in a terraform error "Inappropriate value for attribute "validation": map of string required."

### Actual Behavior

In my connection "Requires username" is disabled. According to the [Auth0 API](https://auth0.com/docs/connections/references/options-mgmt-api) the `validation` flag is used to specify that a username is required. 

Terraform Provider and Auth0 API have a type mismatch in the `validation` option flag. I'm therefore unable to specify username requirements.

**Note:** I'll try to make some time free to fix this myself. If anyone else is quicker or has any concerns please let me know.

### Steps to Reproduce

1. Try configure username requirement and validation

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @etwillbefine thanks for reporting this issue. I believe you're right, seeing the schema definition we have validation specified incorrectly.

```
{
    Type:     schema.TypeMap,
    Elem:     &schema.Schema{Type: schema.TypeString},
    Optional: true,
}
```

It needs to be changed to a `Type: schema.TypeList` and `MaxItems: 1` with an accompanied schema for list elements.

Do you feel up for submitting a PR?

**Comment by etwillbefine** [comment]
Hey @alexkappa I opened a Pull Request (#258) to address the Issue. It is already some time ago and I'm not 100% sure what the desired config is. But basically I mirrored the original Auth0 API (`validation.requires_username` and `validation.username.[min|max]`. The Result is a Map for `validation` and `validation.username`.

**Comment by etwillbefine** [comment]
Waiting for Review on State Migration

**Comment by etwillbefine** [comment]
@alexkappa needs reopening
