### ISSUE TITLE
Output Signing Certificate from Client

### ISSUE THREAD

**Issue by djdiox** [alexkappa/terraform-provider-auth0#249]
### Description

In order to import the signing certificate, we need to get it from the auth0 client. and output it 

### New or Affected Resource(s)

Client

* auth0_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @djdiox, please read the issue template instructions and try to fill in as much information as possible about the problem. It would help me organize better and possibly get to a quicker resolution.
