### ISSUE TITLE
Support for creating and configuring log streams

### ISSUE THREAD

**Issue by davidski** [alexkappa/terraform-provider-auth0#250]
### Description

Support for managing log streams, utilizing the https://auth0.com/docs/api/management/v2/#!/Log_Streams api endpoints. I'm particularly interested in being able to configure auth0 logs forwarding to AWS EventBridge!

### New or Affected Resource(s)

* auth0_log_stream

### Potential Terraform Configuration

TBD

### References

* https://auth0.com/docs/api/management/v2/#!/Log_Streams/post_log_streams

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Great suggestion @davidski, I made an issue to the SDK to add support. With that in place we can implement it here.

**Comment by davidski** [comment]
May we keep this issue open while we wait for the SDK item to be addressed?
