### ISSUE TITLE
Imported existing verified custom domain is scheduled for replacement

### ISSUE THREAD

**Issue by MorrisonCole** [alexkappa/terraform-provider-auth0#252]
### Description

After importing an existing verified custom domain, it is scheduled for replacement.

### Terraform Version

```
Terraform v0.12.28
+ provider.auth0 v0.12.2
```

### Affected Resource(s)

* auth0_custom_domain

### Terraform Configuration Files

```hcl
resource "auth0_custom_domain" "default" {
  domain = "example.com"
  type = "auth0_managed_certs"
  verification_method = "txt"
}
```

### Expected Behavior

Resource should be unchanged.

### Actual Behavior

```
# auth0_custom_domain.example must be replaced
-/+ resource "auth0_custom_domain" "example" {
        domain = "example.com"
      ~ id = "cd_imported-id" -> (known after apply)
      ~ primary = true -> (known after apply)
      ~ status = "ready" -> (known after apply)
        type = "auth0_managed_certs"
      + verification = (known after apply)
      + verification_method = "txt" # forces replacement
    }
```

### Steps to Reproduce

1. Create a custom domain + verify manually
2. Import the domain by ID
2. `terraform plan`

### Debug Output

(Can provide privately if necessary).

### Important Factoids

Created this custom domain a long time ago, so perhaps have some kind of old data / missing fields or something? 🤔 

Response from Auth0 `GET /api/v2/custom-domains` is:
```
{
    "custom_domain_id": "cd_imported-id",
    "domain": "example.com",
    "primary": true,
    "status": "ready",
    "type": "auth0_managed_certs",
    "origin_domain_name": "example.com"
  }
```

### References

* [Auth0: Get Custom Domains](https://auth0.com/docs/api/management/v2?_ga=2.266366286.1909480175.1594548968-1978809400.1593386806#!/Custom_Domains/get_custom_domains)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by MorrisonCole** [comment]
I presume this bug still exists but I don't have the time to double-check right now... 🙏

**Comment by kpurdon** [comment]
@MorrisonCole did you ever find a resolution for this. I just hit it as well. cc @alexkappa

**Comment by MorrisonCole** [comment]
> @MorrisonCole did you ever find a resolution for this. I just hit it as well. cc @alexkappa

I think I just let Terraform apply the proposed changes since it was a development environment and nothing much to worry about. Can't remember clearly though - sorry!
