### ISSUE TITLE
Setting an auth0_client android sha256_cert_fingerprints parameter causes terraform to crash

### ISSUE THREAD

**Issue by rabidscorpio** [alexkappa/terraform-provider-auth0#253]
### Terraform Version
0.12.24

### Affected Resource(s)

* auth0_client

### Terraform Configuration Files

```hcl
resource "auth0_client" "app_android" {
  name                = "Android App"
  description         = "Android mobile application"
  app_type            = "native"
  oidc_conformant     = true

  mobile {
    android {
      app_package_name = "com.test.app"
      sha256_cert_fingerprints = ["F3:94:BD:F7:6E:EB:0B:CA:8A:8D:8D:C2:B7:65:DD:67:12:03:9D:F9:0F:3B:7C:EF:69:89:F4:57:9F:DF:6B:A3"]
    }
  }
}
```

### Expected Behavior
Terraform should create the client and set android app package name and fingerprint correctly.

### Actual Behavior
Terraform crashes:
```
Error: rpc error: code = Unavailable desc = transport is closing
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
I believe the cause can be traced to this commit: https://github.com/terraform-providers/terraform-provider-auth0/commit/feb1c432d58f9ade1c457f81dd1b72d1dd196839#diff-6ff50c2b9594f4e6bf572252c462b975R657

It appears there's a cut and paste error where attributes of a map are repeated twice. It actually looks like this should break iOS settings instead of android but testing different iOS settings produces the correct results.

Setting the `sha256_cert_fingerprints` for an android application causes terraform to crash, probably because this needs to be `Slice` instead of `String`: https://github.com/terraform-providers/terraform-provider-auth0/commit/feb1c432d58f9ade1c457f81dd1b72d1dd196839#diff-6ff50c2b9594f4e6bf572252c462b975R660

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rabidscorpio** [comment]
This is a pretty obvious cut and paste bug but I'm not entirely sure how to fix the `Slice` vs `String` problem and I don't want this issue to be closed. Can you take a look at this @alexkappa ?

**Comment by shufo** [comment]
Same problem here. I'd appreciate if it could be solved...this is only unmanaged attribute in my project.

**Comment by alexkappa** [comment]
Hi all, sorry for the delay here. Your investigation seems to be on point and it should give me enough to help fix this.

**Comment by rabidscorpio** [comment]
That second link where I mentioned that the attribute should be a `slice` and not a `string` (since you can pass in a list of shas), that line is here: https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_client.go#L706

I was linking to the now archived hashicorp repo by mistake.
