### ISSUE TITLE
Samlp addon when creating an auth0_client returns 400

### ISSUE THREAD

**Issue by mijdavis2** [alexkappa/terraform-provider-auth0#254]
### Description

With auth0 provider v0.12.2, samlp addon for "auth0_client" resource no longer works when mapping isn't defined.

### Terraform Version

tf = v0.12.6
auth0 provider = v0.12.2

### Affected Resource(s)

* auth0_client

### Terraform Configuration Files

```hcl
resource "auth0_client" "idp" {
  provider = auth0.idp
  name = "MyApp IDP"
  description = "MyApp IDP"
  app_type = "regular_web"
  callbacks = [
    "https://${var.env_name}.us.auth0.com/login/callback?connection=sso-idp",
    "https://${var.env_name}.us.auth0.com/login/callback",
    "https://${var.env_name}.us.auth0.com/login",
    "https://${var.env_name}.us.auth0.com/p/samlp/sso-idp",
  ]
  web_origins = [
    "https://${var.env_name}.us.auth0.com",
  ]

  addons {
    samlp {
      recipient = "https://${var.env_name}.us.auth0.com/login/callback?connection=sso-idp"
      audience = "urn:auth0:${var.env_name}:sso-idp"
      logout = {
          callback = "https://${var.env_name}.us.auth0.com/logout?connection=sso-idp"
      }
    }
  }
```

### Expected Behavior

Create auth0_client without errors

### Actual Behavior

```
module.auth0.auth0_client.idp: Creating...

Error: 400 Bad Request: Payload validation error: 'Expected type array but found type null' on property addons.samlp.nameIdentifierProbes. (also) Payload validation error: 'Expected type object but found type null' on property addons.samlp.mappings.

  on .terraform/modules/auth0/main.tf line 9, in resource "auth0_client" "idp":
   9: resource "auth0_client" "idp" {


[terragrunt] 2020/07/16 10:32:47 Hit multiple errors:
exit status 1
```

### Steps to Reproduce

1. `terraform apply`

### References

* #248 (I'm guessing this is the culprit)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xens** [comment]
I confirm the exact same issue on my end

**Comment by blawlor** [comment]
Any suggested workarounds in the absence of a fix at the moment?

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/20 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
