### ISSUE TITLE
multiple enabled_clients in a connection causes (un-needed) update

### ISSUE THREAD

**Issue by domg123** [alexkappa/terraform-provider-auth0#26]
With a connection with multiple clients, a terraform plan/apply, with no changes, will be seen as having changed.

i.e.  From a local test

  ~ module.dev-auth.auth0_connection.my_connection
      enabled_clients.0: "C6Xzd6lSkJ4DeZaQtOFzGWbkpLdXbFY4" => "vegazNS4zcnGbIC7Vc70RzXrIbIWV1wM"
      enabled_clients.2: "vegazNS4zcnGbIC7Vc70RzXrIbIWV1wM" => "C6Xzd6lSkJ4DeZaQtOFzGWbkpLdXbFY4"

It seems likely this is due to ordering (or the lack of) of the client list.

I might see if I can hack a solution shortly, (I'm no go/tf-plugin expert) so any guidance on where to look would be appreciated.

**Comment by alexkappa** [comment]
Hi @domg123 thanks for submitting this bug report.

Could you show the terraform config you used? How can we reproduce the problem?

Cheers!

**Comment by domg123** [comment]
Hi, sorry for the delay.  

So, attached is a file you can use to recreate the issue.  

[multiple_client_issue.txt](https://github.com/yieldr/terraform-provider-auth0/files/2324250/multiple_client_issue.txt)

Steps. (assuming valid provider available)
1) rename to a tf file
2) terraform apply
3) terraform plan

At step 3, despite no changes, you will frequently see the output below.  If you don't get it the first time, remove the file, apply again to delete, and try again.


====
`An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ auth0_connection.myconnection
      enabled_clients.0: "7I9NL7cPUoIPXUdJp2xUgEeoVivzRD9y" => "PtQinZ36JAoTebouQ5h339hhP0SqLPqg"
      enabled_clients.1: "PtQinZ36JAoTebouQ5h339hhP0SqLPqg" => "wEQaqNp1rNRyIq107kY4v8wzu2ZN5Hvi"
      enabled_clients.2: "Wn97VIpP5IMpmoeGUyrt9l8hQiU2RMFf" => "7I9NL7cPUoIPXUdJp2xUgEeoVivzRD9y"
      enabled_clients.3: "wEQaqNp1rNRyIq107kY4v8wzu2ZN5Hvi" => "Wn97VIpP5IMpmoeGUyrt9l8hQiU2RMFf"
`

**Comment by alexkappa** [comment]
Hi @domg123, I believe the bug was due to the [ListType](https://www.terraform.io/docs/extend/schemas/schema-types.html#typelist) in terraform being ordered and we were forcing our own ordering on top of it. 

It could be solved by ordering the list of clients differently, but honestly, I find it a bit weird to resort to such a solution.

I will continue to research the topic in hopes to find something better.

**Comment by laurentdutheil** [comment]
might be fixed with #95
