### ISSUE TITLE
Unsupported connection strategy oauth2

### ISSUE THREAD

**Issue by Hangsolow** [alexkappa/terraform-provider-auth0#266]
### Description

The Oauth2 provider is not supported.  When it is used it throws the following error
`Error: 400 Bad Request: Payload validation error: 'Missing required property: options'.`

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

basically just taking the OIDC configuration and just use the fields needed by the generic oauth2 connection
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "auth0_connection" "my_con" {
  name                 = "my_con"
  strategy             = "oauth2"
  realms               = ["my_con"]
  is_domain_connection = false
  enabled_clients      = ["xxx"]
  
  options {
    client_id     = "xxx"
    client_secret = "xxx"
    scopes        = ["openid", "profile", "email"]
    token_endpoint         = "https://xxx.com/oauth2/token",
    authorization_endpoint = "https://xxx.com/oauth2/authorize"
    custom_scripts = {
      fetchUserProfile = "..."
    }
    custom_headers = {
      "x-header" = "xxx"
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Hangsolow** [comment]
I would be happy to help implementing this, I just need someone to point me in the right direction as my Go skills are a bit rusty 🙂

**Comment by mcalster** [comment]
This is a feature that will be very useful for us as well. It seems weird that this is not supported. A bug maybe?

**Comment by mcalster** [comment]
> This is a feature that will be very useful for us as well. It seems weird that this is not supported. A bug maybe?

It seems that the oauth2 connection strategy is not implemented in the auth0 Management Go client.
https://github.com/go-auth0/auth0/blob/master/management/connection.go.

Created issue for that: https://github.com/go-auth0/auth0/issues/139
