### ISSUE TITLE
Add more logging for connection issues

### ISSUE THREAD

**Issue by nirvdrum** [alexkappa/terraform-provider-auth0#269]
### Description

Please add more logging to help debug connection issues. I've been having problems importing a new tenant. Even with `TF_LOG` set to `TRACE` and the Auth0 provider's `debug` setting set to `true`, I couldn't see why I couldn't connect. I just received a 401 message about oauth2 not being able to connect. In this particular case, it turns out my domain was wrong\*, so there weren't any logs in the Auth0 dashboard either.

I was only able to figure out the issue after building the provider myself with several debug statements.

_\* - US-based tenants used to go to "<tenant>.auth0.com", but now go to "<tenant>.us.auth0.com". Some part of our TF config assumed the old naming convention and thus couldn't connect to a newly created tenant._

### New or Affected Resource(s)

Any resource that makes an API call.

### Potential Terraform Configuration

I don't think any new configuration is needed. Reporting the URL on error without any extra configuration would be a big help. If that's too noisy, however, showing connection info when the `debug` flag is set would be very helpful.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @nirvdrum, I believe the reason why authentication requests are not logged as regular requests do, has to do with [golang.org/x/oauth2](https://godoc.org/golang.org/x/oauth2).

This could be an area for improvement.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/21 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
