### ISSUE TITLE
Allow setting Azure AD Email Verification Option

### ISSUE THREAD

**Issue by LavaToaster** [alexkappa/terraform-provider-auth0#273]
### Description

Azure AD connector has an email verification option that allows us to force `email_verified` to be true/false.

The real name of this is actually `should_trust_email_verified_connection` and it'd be nice if this could be set using this provider.

Valid options (taken from ui values):
```
never_set_emails_as_verified (default)
always_set_emails_as_verified
```

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

```hcl
resource "auth0_connection" "upp_azure_ad" {
  name = "azureAD"
  display_name = "azure AD"
  strategy = "waad"

  options {
    domain = "domain.com"
    client_id = ""
    client_secret = ""
    identity_api = ""
    tenant_domain = "domain.ai"
    should_trust_email_verified_connection = "always_set_emails_as_verified"
  }
}
```

### References

Add an Azure AD connector in auth0, you'll find the dropdown for this value at the bottom called `Email Verification`.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by zanitete** [comment]
@LavaToaster did you find a workaround for this?

**Comment by LavaToaster** [comment]
Since the resource is unaware of the parameter, we just enable it manually.

**Comment by mafodev** [comment]
Is there any update on this? With the upcoming [Deprecation of Default to ‘Email Verification’ setting for Azure AD/ADFS](https://community.auth0.com/t/deprecation-of-default-to-email-verification-setting-for-azure-ad-adfs-connections-migration-setting/54316) this would be a nice option to have. 

If no one is on this already I might give it a shot - provided I can figure the go part out ;-)
