### ISSUE TITLE
Universal Login Page Templates

### ISSUE THREAD

**Issue by adamu** [alexkappa/terraform-provider-auth0#274]
### Description

Auth0 has a [Login Page Templates](https://auth0.com/docs/universal-login/new-experience/universal-login-page-templates) feature available on the Management API to customise the "New" Universal Login experience for custom domains.

It would be great if we could get support for this in the provider.

### New or Affected Resource(s)

* Maybe `auth0_custom_domain`?

### Potential Terraform Configuration

```hcl
resource "auth0_custom_domain" "default" {
  domain              = "example.com"
  type                = "auth0_managed_certs"
  verification_method = "txt"
  login_template      = data.http.login_form_template.body
}
```

### References

* #133

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by adamu** [comment]
Nine votes and still valid.

**Comment by gagalago** [comment]
I am on it but I have some trouble to understand why tests are failing

**Comment by adamu** [comment]
@alexkappa with  10 votes and an open PR, maybe your auto-closer was a bit aggressive here :-)

**Comment by o1da** [comment]
I think it can fit more under `auth0_tenant` because there is already the error and redirect page config which is similar.
