### ISSUE TITLE
Support newer releases of Terraform

### ISSUE THREAD

**Issue by rrjohnson85** [alexkappa/terraform-provider-auth0#278]
Is there a timeline for supporting newer versions of Terraform, such as 0.13.x?  It looks as though the provider only supports TF <= 0.12.x, and Terraform is already releasing alphas for 0.14.x.

**Comment by Giaco9** [comment]
Hi! we are starting to use terraform and we are very interested in automatically provision Auth0 resources with it. We would like to start with the newest version of Terraform, 0.14.2. Currently, it seems impossible to install the provider with that version. Are you planning to support any 0.14 Terraform version?

Thank you!

**Comment by kvrhdn** [comment]
This Terraform provider can work fine with Terraform 0.13+. Terraform 0.13+ uses the registry for community-provided provider, check out the documentation here: https://registry.terraform.io/providers/alexkappa/auth0/latest
The _How to use this provider_ button at the top-right lists what you have to do to include the provider in your workspace.

As a quick test, I created a Auth0 rule with Terraform 0.14.2 using this config:

```
terraform {
  required_providers {
    auth0 = {
      source  = "alexkappa/auth0"
      version = "~> 0.16"
    }
  }
}

provider "auth0" {
  domain        = "<snip>"
  client_id     = "<snip>"
  client_secret = "<snip>"
}

resource "auth0_rule" "my_rule" {
  name    = "empty-rule"
  script  = <<EOF
function (user, context, callback) {
  callback(null, user, context);
}
EOF
  enabled = true
}
```

**Comment by Giaco9** [comment]
Hi, thank you for your reply. I better checked my configuration and I found the problem. Really thank you!

**Comment by alexkappa** [comment]
Thank you @kvrhdn for clarifying! You are correct. I'll make sure we update the readme as well so.

**Comment by rrjohnson85** [comment]
My team was able to get this working with Terraform 0.13.x as well, and forgot to update the issue.
