### ISSUE TITLE
Support Terraform data sources

### ISSUE THREAD

**Issue by lebaptiste** [alexkappa/terraform-provider-auth0#279]
### Description

Aside Terraform resources, there is also another [data source](https://www.terraform.io/docs/configuration/data-sources.html) type which is roughly the readonly version of a resource.  

That would be a great enhancement to this provider to include data source support. Since I have already worked on a terraform provider I am happy to submit a PR for it.
 
### New or Affected Resource(s)

Ideally all the existing resources would have their data source counterpart.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by yinzara** [comment]
I have implemented "auth0_client" and "auth0_global_client" data sources and submitted a PR. Please vote!

**Comment by sunnz** [comment]
Can we re-open this? I think the provider doesn't have data sources at this point, the pull request was merged and then reverted, but I like to be able to see the auth0_client and auth0_global_client data sources available.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/22 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
