### ISSUE TITLE
Display Name not being set when creating `auth0_connection` resources.

### ISSUE THREAD

**Issue by kpurdon** [alexkappa/terraform-provider-auth0#288]
### Description

When creating or updating a new or existing auth0_connection resources the value of display name is not being set.

### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/alexkappa/auth0 v0.15.2
```

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "samlp" {
  for_each = var.saml_connections

  name            = each.key
  display_name    = each.value.display_name
  strategy        = "samlp"
  enabled_clients = [auth0_client.payeq.client_id]

  options {
    signing_cert     = each.value.cert
    sign_in_endpoint = each.value.sign_in_endpoint
    tenant_domain    = each.value.domain
    domain_aliases   = [each.value.domain]

    idp_initiated {
      client_id       = auth0_client.payeq.client_id
      client_protocol = "samlp"
    }
  }
  realms = [each.key]
}
```

### Expected Behavior

The display name should not be set.

### Actual Behavior

The display name is not set.

```
  # module.syndio_auth0.auth0_connection.samlp["REDACTED"] will be created
+ resource "auth0_connection" "samlp" {
      + display_name         = "REDACTED"
      ....
```

<img width="699" alt="Screen Shot 2020-11-05 at 12 22 15 PM" src="https://user-images.githubusercontent.com/5130441/98286727-a5ddd700-1f61-11eb-836f-e24c3eae7de1.png">

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @kpurdon thanks for filing this in! It seems `display_name` was missing altogether from connections. I've made a PR to address this. Cheers!

**Comment by kpurdon** [comment]
@alexkappa looks like the PR got marked as stale and closed ... can we please get this merged? https://github.com/alexkappa/terraform-provider-auth0/pull/304
