### ISSUE TITLE
Unable to remove scopes on auth0_resource_server

### ISSUE THREAD

**Issue by multani** [alexkappa/terraform-provider-auth0#289]
### Description

I created a resource server using an `auth0_resource_server`, with a few `scopes` configured.

After removing the `scopes` block, `terraform apply` says it will remove the scopes but they stay configured.

Subsequent `terraform apply` always show a plan where scopes will be removed, until new scopes are added (different plan), or scopes are manually removed from the Auth0 console.

### Terraform Version

```
Terraform 0.13.5
+ provider.auth0 0.15.2
```

### Affected Resource(s)

* `auth0_resource_server`

### Terraform Configuration Files

Initial configuration:

```hcl
resource auth0_resource_server "test" {
  name       = "test123"
  identifier = "https://example.com"

  scopes {
    value       = "foo:bar"
    description = "bar the foo"
  }
}
```

Removing the `scopes` block doesn't delete the last, unique scope configured.

### Expected Behavior

The last scope should be removed and subsequent plan should not show any difference.

### Actual Behavior

The last scope stays configured, and Terraform always shows a difference and says it will remove the last scope.

### Steps to Reproduce

1. Create the a resource server with 1 scope defined
1. `terraform apply`
1. Remove the scope from the configuration
1. `terraform apply` shows it will remove the scope

**Comment by alexkappa** [comment]
Hi @multani, if I'm not mistaken, this is caused by the scopes being tagged as `json:",omitempty"`. This means empty slices don't get marshaled.

With go-auth0 v5 we should be able to finally overcome such limitations by handling the removal of scopes outside of the `Update` method.

**Comment by sergiught** [comment]
This relates to several other issues that are present within the provider and I have captured this along with the others within https://github.com/auth0/terraform-provider-auth0/issues/14. 

As this repo has moved over at https://github.com/auth0/terraform-provider-auth0 please open new issues over there from now on.
