### ISSUE TITLE
Optional and not modified attributes for User cause 400 Bad Request: The following user attributes cannot be updated

### ISSUE THREAD

**Issue by ertanden** [alexkappa/terraform-provider-auth0#292]
### Description

Even though there are no changes in any of the `family_name, given_name, name, nickname, picture` attributes I get the following error, when there's a role change for the user. I would like to keep the `Sync user profile attributes at each login` setting and not really care about all those attributes. Is this a known problem and how can we fix that?

The error:

> 400 Bad Request: The following user attributes cannot be updated: family_name, given_name, name, nickname, picture. The connection (main-tenant-oidc) must either be a database connection (using the Auth0 store), a passwordless connection (email or sms) or has disabled 'Sync user profile attributes at each login'. For more information, see https://auth0.com/docs/dashboard/guides/connections/configure-connection-sync

### Terraform Version

```
Terraform 0.13
+ provider.auth0 0.15.2
```

### Affected Resource(s)

* auth0_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a [Github Gist](https://gist.github.com/) instead.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @ertanden, the issue template would help me track down the root cause of the issue and be able to help you better. If you are still experiencing this problem, please consider updating the issue with what is asked in the template.
