### ISSUE TITLE
Importing auth0_custom_domain resource forces recreation

### ISSUE THREAD

**Issue by joshk0** [alexkappa/terraform-provider-auth0#294]
### Description

I've imported an auth0_custom_domain resource (with some difficulty; the domain ID starting in `cd_` could _only_ be seen using the API explorer and not scummed from the UI.)

Since I had used TXT verification for the domain, I set `verification_method = "txt"` in my resource:

```hcl
resource "auth0_custom_domain" "auth" {
  domain              = "auth.my-cool-domain.org"
  type                = "auth0_managed_certs"
  verification_method = "txt"
}
```

When doing a no-op plan, it wants to recreate the custom domain since verification_method was not set during the import.

There are two workarounds:
1. Remove the `verification_method` from my resource. This is undesirable, because I want a record that I used txt to verify this domain.
2. Hack the state by locating the state entry for this record and changing `"verification_method": null` to `"verification_method": "txt"`

After either workaround, a no-op plan proceeds as expected.

### Terraform Version

```
Terraform v0.12.26
+ provider.auth0 v0.14.0
```

### Affected Resource(s)

* auth0_custom_domain

### Terraform Configuration Files

Included in-line

### Other Boilerplate Sections (Repro, Outputs, Factoids, References)

All are covered in my description above or I do not think are necessary since the issue seems fairly concrete. If you would like it, comment here.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @joshk0, thanks for submitting this issue.

With regards to making importing easier, perhaps there is something we can do - and that is creating a custom importer to allow importing by domain as well / instead.

Regarding the `verification_method`, I believe it is due to the API not returning that field in responses (see below). We could try to infer it based on the contents of `verification.methods[].name` but that value is `cname` for me. I'm not sure if we should be doing that.

```
[
  {
    "custom_domain_id": "cd_...",
    "domain": "...",
    "primary": true,
    "status": "pending_verification",
    "type": "auth0_managed_certs",
    "verification": {
      "methods": [
        {
          "name": "cname",
          "record": "...edge.tenants.eu.auth0.com"
        }
      ]
    },
    "tls_policy": "recommended"
  }
]
```
