### ISSUE TITLE
Please add the ability to define hook dependencies

### ISSUE THREAD

**Issue by rltvty** [alexkappa/terraform-provider-auth0#296]
### Description

Auth0 hooks allow the addition of dependencies which are NPM modules that can be used in the javascript.  It would be great if we could set the dependencies via the `auth0_hook` resource.

### New or Affected Resource(s)

* auth0_hook

### Potential Terraform Configuration

```hcl
resource "auth0_hook" "send_password_reset_email" {
  enabled    = true
  name       = "send-password-reset-email"
  trigger_id = "post-user-registration"

   dependencies = {
       auth0 = "2.30.0"
   }

  script = ....
}
```

### References

The management API supports passing dependencies: https://auth0.com/docs/api/management/v2/#!/Hooks/post_hooks

The json snippit for dependencies should look like: 
```
"dependencies": {
      "auth0": "2.30.0"
    },
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @rltvty, indeed it seems we missed this field from this provider. I notice that go-auth0 [Hooks](https://pkg.go.dev/gopkg.in/auth0.v5@v5.2.2/management#Hook) already supports dependencies so adding it here should be quite straightforward. Would you feel up for a PR?

**Comment by woz5999** [comment]
i also need this. i plan to submit a PR this week.

**Comment by woz5999** [comment]
@alexkappa this issue is marked as stale; however, there's currently an open PR to address it.

**Comment by woz5999** [comment]
@yvovandoorn this got closed due to inactivity even though we're still working to get that PR finalized.

**Comment by yvovandoorn** [comment]
Reopened @woz5999. Thanks for the heads up.
