### ISSUE TITLE
Support to configure Microsoft AD to be on by default

### ISSUE THREAD

**Issue by jonathancychow** [alexkappa/terraform-provider-auth0#297]
### Description

It seems it's not possible to define an argument in this resources so that I can set Microsoft AD under Connection to be on by default. 

### New or Affected Resource(s)

* auth0_client

### Potential Terraform Configuration

```hcl
resource "auth0_client" "services_client" {
name                = "Services Client"
  app_type            = "spa"
  callbacks           = "callbacks"
  allowed_logout_urls = "some_urls"
  oidc_conformant     = true
  grant_types         = [ "implicit", "authorization_code", "refresh_token" ]
  jwt_configuration {
    lifetime_in_seconds = 3600
    secret_encoded      = true
    alg                 = "RS256"
  }
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @jonathancychow, thanks for submitting an issue. Can you elaborate on what you mean by on by default?

**Comment by jonathancychow** [comment]
Hi @alexkappa, I'm referring to the options under Connections as the follow picture, if the resource can specific one of those connections to be available when I apply the deployment that would be great.  
![image](https://user-images.githubusercontent.com/31481322/101249485-2cc6d080-3715-11eb-88fe-4be9c60c0e58.png)

**Comment by alexkappa** [comment]
Perhaps what you need is the [`auth0_client_grant`](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/client_grant)?

**Comment by zanitete** [comment]
I think it's only possible to set the list of enabled clients from the connection resource: https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/connection#enabled_clients
