### ISSUE TITLE
Resource Server RBAC Settings not set ?

### ISSUE THREAD

**Issue by Chanonry** [alexkappa/terraform-provider-auth0#298]
### Description

First pass at creating a Resource Server through Terraform with some scopes. The server is created but Role Based Access Control is Disabled as is Add Permissions in the Access Token which defeats the point of defining scopes. The parameter to enable this is not obvious ?

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/-/aws v3.18.0
+ provider registry.terraform.io/alexkappa/auth0 v0.16.1
+ provider registry.terraform.io/hashicorp/aws v3.18.0

### Affected Resource(s)

Below...

### Terraform Configuration Files

resource "auth0_resource_server" "nk_resource_server" {
  name        = "NK Resource Server stage:${terraform.workspace} (Managed by Terraform)"
  identifier  = "https://nk.api.http.v2-${terraform.workspace}"
  signing_alg = "RS256"

  scopes {
    value       = "test:any"
    description = "admin can make GET requests"
  }

  scopes {
    value       = "data:import"
    description = "admin can make POST requests"
  }

  scopes {
    value       = "analysis:get"
    description = "can get data from a fast running analysis "
  }

  scopes {
    value       = "analysis:start"
    description = "can start a long running analysis process"
  }

  allow_offline_access                            = true
  token_lifetime                                  = var.token_lifetime
  skip_consent_for_verifiable_first_party_clients = true
}
### Expected Behavior

Not sure, but RBAC needs to be enabled. How is this achieved?

### Actual Behavior

Resource configured ok but the console shows all RBAC Settings as disabled

### Steps to Reproduce

1. `terraform apply`

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

N/A

### References

N/A

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
@Chanonry I'm not sure I understand the issue. Can you elaborate on what you are trying to achieve, what is expected, and what is happening instead?

> Resource configured ok but the console shows all RBAC Settings as disabled

The `resource_server` `scopes` (defined in your configuration) should be visible under the resource servers permissions tab. That's Applications > APIs > NK Resource Server ... > Permissions.

Perhaps what you're looking for is the [`client_grant`](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/client_grant) resource?

**Comment by Chanonry** [comment]
On the API settings page I want to ENABLE both the RBAC setting. The attached image shows the settings for the above resource as deployed which has both DISABLED
![output-onlinepngtools-3](https://user-images.githubusercontent.com/20876829/100712456-b0499000-33aa-11eb-9595-6cb57d044086.png)

**Comment by btmcnellis** [comment]
I actually just ran into this myself while using this provider for the first time. There's a disconnect between the language used in the dashboard and the language used in the Management API, on which this provider is based. On your resource server, you need to set `enforce_policies` to `true` and `token_dialect` to either `access_token` or `access_token_authz`.

[This article from the Auth0 docs](https://auth0.com/docs/authorization/rbac/enable-role-based-access-control-for-apis#management-api) explains how to enable RBAC using the management API, and these same settings exist in the Terraform provider as well. Once I enabled those, the RBAC settings in the dashboard were enabled as expected.

My config ended up looking like this:

```
resource "auth0_resource_server" "my_api" {
  # ...
  enforce_policies     = true
  token_dialect        = "access_token_authz"
}
```

This is a pretty easy thing to get tripped up on if you don't know the management API intimately. It might be worth in mention in the resource server docs.

**Comment by Chanonry** [comment]
Spot on, thanks for the steer

**Comment by alexkappa** [comment]
Hi @Chanonry, I believe what you need is to set the `enforce_policies` field. Could you try it and let me know if it works for you?
