### ISSUE TITLE
auth0_client refresh_token configuration not in documentation

### ISSUE THREAD

**Issue by cdb39** [alexkappa/terraform-provider-auth0#299]
### Description
The provider documentation for the auth0_client here https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/client does not describe any mechanism to configure the client's `refresh_token` settings.

However, by looking at the source code here https://github.com/alexkappa/terraform-provider-auth0/blob/v0.16.1/auth0/resource_auth0_client.go#L467-L501 it seems like these settings are in fact already configurable.

### Affected Resource(s)

* auth0_client

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Thanks for reporting @cdb39! Would you be open to a PR?

**Comment by cdb39** [comment]
Done https://github.com/alexkappa/terraform-provider-auth0/compare/master...cdb39:patch-1

**Comment by woz5999** [comment]
@alexkappa any update on this?
