### ISSUE TITLE
TF 0.12 switch auth0 to alexkappa/auth0 GPG error

### ISSUE THREAD

**Issue by alexinthesky** [alexkappa/terraform-provider-auth0#300]
### Description

terraform init throws GPG error :

### Terraform Version

terraform -v
Terraform v0.12.29

### Affected Resource(s)

provider

### Terraform Configuration Files

provider "alexkappa/auth0" {
  alias         = "xxxxx"
  domain        = "https://xxxxx.eu.auth0.com"
  client_id     = "xxxxx"
  client_secret = "xxxxxx"
  version = "=0.16.1"
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a [Github Gist](https://gist.github.com/) instead.
```

### Expected Behavior

init goes though

### Actual Behavior

init fails

### Steps to Reproduce

terraform init

### Debug Output

terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Error verifying GPG signature for provider "alexkappa/auth0"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.

Error: unable to verify signature

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @alexinthesky, the new terraform registry works with terraform 0.13+. You seem to be using 0.12.
