### ISSUE TITLE
Unable to use any version of provider > 0.14.0 with terraform 0.12.x

### ISSUE THREAD

**Issue by jsmitley** [alexkappa/terraform-provider-auth0#301]
### Description

The README file lists supported versions of terraform as 0.11 || 0.12.

However, any time I specify a provider.auth0.version greater than `~> 0.14`, I get a failure of:

```
Error: no suitable version is available
```

**NOTE: I am able to install this provider's latest version on terraform 0.13.5**

### Terraform Version

```
Terraform v0.12.29
+ provider.auth0 v0.14.0
```

### Affected Resource(s)

All

### Terraform Configuration Files

**_main.tf**
```
terraform {
  required_version = "~> 0.12.28"

  backend "remote" {
  }
}

provider "auth0" {
  version       = "~> 0.15"
  domain        = local.auth0_domain
  client_id     = var.auth0_client_id
  client_secret = var.auth0_client_secret
}
```

### Expected Behavior

I should be able to load the most recent plugins

### Actual Behavior

I not able to load the most recent plugins

### Steps to Reproduce

1. `terraform init`

### Debug Output

https://gist.github.com/jsmitley/1eaa7fc65988b8c0655ebef206fe95d1

### Panic Output

N/A

### Important Factoids

On mac with fish shell

### References

Not that I know of

### Community Note

I figured this may just be a README issue, that this is supposed to work with > 0.13 of Terraform.

**Comment by alexkappa** [comment]
Hi @jsmitley, thanks for reporting! The `0.11 || 0.12` requirement is outdated. The new terraform registry requires at least 0.13.

Perhaps we could add a not for people still using 0.12 or earlier that a binary can be downloaded from this providers [releases](https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.16.1) and configured manually by placing into `~/.terraform.d/plugins`.

**Comment by jsmitley** [comment]
Thanks @alexkappa ! We've been successfully using 0.14 using the previous method of specifying providers, I'll make a PR for the doc change you are specifying

**Comment by jsmitley** [comment]
I see the docs are already changed, so I'm going to close this issue.
