### ISSUE TITLE
Support Auth0 Actions

### ISSUE THREAD

**Issue by paulvonallwoerden** [alexkappa/terraform-provider-auth0#302]
### Description

Currently Auth0 has a new feature called **actions** in beta. These actions will "replace" the hooks & rules resources. However, as of now actions may not be managed via the api. This will probably change, when they exit beta.

As this feature will become important in the future, this issue exists to track further developments on the topic.

### New or Affected Resource(s)

* auth0_action

### References

* https://auth0.com/blog/introducing-auth0-actions/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @paulvonallwoerden, thanks for filing this issue. Let's keep track of actions and get to it when they come out of Beta and their API becomes available.

**Comment by austinrivas** [comment]
Great to hear, I've been using them in my dev stacks and they are big improvement over rules.

The TS support alone is enough to make the switch imo.

**Comment by jasonjoneski** [comment]
Hi @alexkappa, we are moving to Auth0, and have been given guidance to use Actions as they will soon replace rules.  From what I've heard they should be going GA extremely soon, and they have just released the API for it, you can find the docs here: https://auth0.com/docs/api/management/v2#!/Actions/get_actions.

**Comment by jasonjoneski** [comment]
Just went GA today.

**Comment by ypicard** [comment]
Would be great to see support for this!

**Comment by leonfs** [comment]
The go library seems to no support the new Actions API. Great news.

**Comment by shouze** [comment]
@leonfs this is ok now  [since v5.18.0](https://github.com/go-auth0/auth0/releases/tag/v5.18.0) :tada:

**Comment by CalebDelbridge** [comment]
@alexkappa, is this going to be implemented? I would love to move from rules and hooks and to actions

**Comment by alexkappa** [comment]
Working on this everyone, thanks for your patience!

**Comment by alexkappa** [comment]
Version [0.23.0](https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.23.0) is released with support for the `auth0_action` resource.  [Check it out!](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/action)
