### ISSUE TITLE
auth0_log_stream resource missing documentaiton

### ISSUE THREAD

**Issue by davidski** [alexkappa/terraform-provider-auth0#306]
### Description

The merge of https://github.com/alexkappa/terraform-provider-auth0/pull/270 brought support for the auth0_log_stream resource. This new resource does not appear on the registry docs at https://registry.terraform.io/providers/alexkappa/auth0/latest nor can I find documentation here in the source repo. I'd love to try out this resource but am not sure how to get started.

### Affected Resource(s)

* auth0_log_stream

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @davidski, thanks for filing an issue for this! Until we have some examples documented, feel free to [have a look at the tests](https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_log_stream_test.go) on how to use log streams.

**Comment by sergiught** [comment]
Docs the for `auth0_log_stream` resource have been introduced since opening this issue, as such we'll be closing this down. 

If needed please reopen an issue at https://github.com/auth0/terraform-provider-auth0
