### ISSUE TITLE
mobile attributes (ios and android) still not working in auth0_client (after new release)

### ISSUE THREAD

**Issue by RLKANG** [alexkappa/terraform-provider-auth0#308]
### Description
I am trying to use the auth0_client, specifically the ios and android parts, however I am not seeing the update in Auth0 after applying the change. I noticed that there was a similiar issue: https://github.com/alexkappa/terraform-provider-auth0/issues/253, which was resolved and was supposed to go into the new release (0.17.0), however for some reason was not included in the new release, as shown here:  https://github.com/alexkappa/terraform-provider-auth0/compare/v0.17.0...master . I have tried the newest release and it's currently not working for me.

### Terraform Version

```
Terraform <0.14>
+ provider.auth0 <0.17.0>
```

### Affected Resource(s)

* auth0_client

### Terraform Configuration Files

```hcl
mobile {
    ios {
      team_id = var.ios_team_id
      app_bundle_identifier = var.ios_app_bundle_identifier
    }
  }
```
```hcl
mobile {
    android {
      app_package_name = var.android_app_package_name
    }
  }
```

### Expected Behavior

The mobile settings (ios and android) should be visible in Auth0 after it is applied.

### Actual Behavior

Not able to see any changes in Auth0 in the ios and android settings after a terraform apply is done.

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/alexkappa/terraform-provider-auth0/issues/253

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @RLKANG, I can see the changes from the PR included in the release. It’s the file `auth0/resource_auth0_client.go` .

 Is it perhaps a different issue you are experiencing?

**Comment by RLKANG** [comment]
Hmm, I was looking at https://github.com/alexkappa/terraform-provider-auth0/compare/v0.17.0...master and see the commit 'fix mobile properties defined badly' (e3c4790), which means that it wasn't included in the release, right? I may be understanding that part incorrectly.

The issue I am experiencing is that running a terraform apply does not cause any changes to made in Auth0, i.e I am not able to update the android and ios fields under mobile.

**Comment by alexkappa** [comment]
Ah, okay I see there was another thing missing to get mobile working properly again. This (rather embarrassing) [commit](https://github.com/alexkappa/terraform-provider-auth0/commit/c1cd3234e4c8cac805b39190d483db8eb8ce6595) should do it :)

I've published with version [0.17.0](https://registry.terraform.io/providers/alexkappa/auth0/0.17.0) again since the change is already in the changelog. Please make sure to remove any copies of the provider before running `terraform init` so it downloads the newly published binaries.

**Comment by RLKANG** [comment]
Great, thanks for looking into it!

I've removed copies of any providers, and ran a 'terraform init'. However, I am getting a checksum error:

Error: Failed to install provider

Error while installing alexkappa/auth0 v0.17.0: checksum list has unexpected
SHA-256 hash d1648189c8b38af982a1ac62f6d01edd0ccf4c2f419e68c6d5a74157494cdb72
(expected 4f15bef1e165a1a97567dd37630b05cd75adfba2abd9d7c6ff154326d8de6796)

**Comment by alexkappa** [comment]
Sorry about this everyone, pushing 0.17.1 to resolve the hash mismatch. Will be ready in a few minutes

**Comment by RLKANG** [comment]
Great, appreciate it. The provider seems to be working for me now. 

Although I am running into another issue now. I see in the docs that the android and ios parameters are labeled as 'Optional'. However, if I exclude one of them (i.e under Android I only have 'app_package_name' and not 'sha256_cert_fingerprints'), it gives me an error of:

400 Bad Request: Payload validation error: 'Expected type array but found type null' on property mobile.android.sha256_cert_fingerprints (The SHA256 fingerprints of your app's signing certificate. Multiple fingerprints can be used to support different versions of your app, such as debug and production builds).

Just wanted to clarify whether this is a bug or if it's intended behaviour. Also, let me know if I should make a seperate bug request for this one. Thanks!

**Comment by alexkappa** [comment]
I think this is a bug, @RLKANG. I will look into it shortly. The values should in fact be optional (so long as one of the two is specified).

**Comment by alexkappa** [comment]
Okay, 0.17.2 should overcome these limitation. Please give it a try and let me know!

**Comment by RLKANG** [comment]
Yeah, it works as expected now. Thanks so much for your support. Happy new year!
