### ISSUE TITLE
Failed to install provider v0.17.0

### ISSUE THREAD

**Issue by chrissng** [alexkappa/terraform-provider-auth0#309]
### Description

Failed to install terraform provider v0.17.0

### Terraform Version

```
Terraform v0.14.2
+ provider registry.terraform.io/alexkappa/auth0 v0.17.0
...
```

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a [Github Gist](https://gist.github.com/) instead.
terraform {
  required_version = ">= 0.13"

  required_providers {
    auth0 = {
      source  = "alexkappa/auth0"
      version = "~> 0.15"
    }
    . . .
  }
}
```

### Expected Behavior

Provider should be installed successfully.

### Actual Behavior

```
Error: Failed to install provider

Error while installing alexkappa/auth0 v0.17.0: checksum list has unexpected
SHA-256 hash aa0661a9b943292e615d922dc931b97a86bc15a63ee92861229b12dced6d9b06
(expected cf71f0ee291bb8079e897c841a998c941a2d1a432d6f1be1160246fd61f0d1c0)
```

### Steps to Reproduce

1. `terraform plan` or
2. `terraform init -upgrade`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @chrissng, thanks for reporting. This was my error, please use 0.17.1 instead.

**Comment by chrissng** [comment]
That's great! Thank you! closing this
