### ISSUE TITLE
Document `auth0_client` `initiate_login_uri`

### ISSUE THREAD

**Issue by cihati** [alexkappa/terraform-provider-auth0#315]
It's added via https://github.com/hashicorp/terraform-provider-auth0/pull/2 but docs were not updated.

**Comment by cihati** [comment]
ping

**Comment by Houndie** [comment]
ping

**Comment by alexkappa** [comment]
Reopening this, apologies for the late reply.

**Comment by sergiught** [comment]
Documentation for this has been added, thus closing this issue down.
