### ISSUE TITLE
Removing all enabled_clients from an auth0_connection not honored

### ISSUE THREAD

**Issue by apamildner** [alexkappa/terraform-provider-auth0#325]
### Description
Removing *all* enabled clients from an auth0_connection resource does not work as expected. Clients are still enabled.

### Provider Version

```
+ provider registry.terraform.io/alexkappa/auth0 v0.18.0
```

### Affected Resource(s)

* auth0_connection

####  Steps to Reproduce
Apply this configuration:
```hcl
resource "auth0_connection" "default" {
  ...
  enabled_clients      = [auth0_client.default.client_id]
}
```
Then apply this:
```hcl
resource "auth0_connection" "default" {
  ...
  enabled_clients      = []
}
```

### Expected Behavior

The connection should have no enabled clients

### Actual Behavior
The connection still has "auth0_client.default.client_id" enabled.
### Probable Cause
After some manual testing, it seems that the Auth0 Management Api doesn't work as documented. Omitting the key `enabled_clients` will not disable all clients. Instead we need to pass `enabled_clients: []`explicitly.
This becomes a problem when marshalling [here](https://github.com/go-auth0/auth0/blob/d250a6c2f997cc18e3d23fa64dc55af3b0d01b61/management/connection.go#L66)
as "omitempty" omits the empty array completely.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by apamildner** [comment]
I created a PR that solves this.

**Comment by sergiught** [comment]
This relates to several other issues that are present within the provider and I have captured this along with the others within https://github.com/auth0/terraform-provider-auth0/issues/14. 

As this repo has moved over at https://github.com/auth0/terraform-provider-auth0 please open new issues over there from now on.
