### ISSUE TITLE
auth0_connection with google-apps strategy

### ISSUE THREAD

**Issue by BilelAouiss** [alexkappa/terraform-provider-auth0#328]
resource "auth0_connection" "my_connection" {
  name                 = "my_connection"
  strategy             = "google-apps"
  is_domain_connection = false
   
  options {
    allowed_audiences = ["myDomain.com"]
    scopes            = ["email", "profile"]
    api_enable_users  = true
    domain = "myDomain.com"
    tenant_domain ="myDomain.com"
  }
}

But i get : 400 Bad Request: undefined is not a valid google apps domain.

Here domain and tenant_domain are ignored!

**Comment by vandevusse** [comment]
Hopefully this is fixed with PR at https://github.com/alexkappa/terraform-provider-auth0/pull/398 🙏

**Comment by sergiught** [comment]
This should now be fixed, closing this PR as such. Feel free to reopen in case of need.
