### ISSUE TITLE
Add enable_sign_in_with_apple

### ISSUE THREAD

**Issue by mattmillen888** [alexkappa/terraform-provider-auth0#336]
### Description
Is there any plan to add enable_sign_in_with_apple & enable_sign_in_with_facebook under:

native_client > Advanced Settings > Device Settings > Enable Sign In with Apple
native_client > Advanced Settings > Device Settings > Enable Sign In with Facebook

So i guess it would be something like:

  mobile {
    ios {
      enable_sign_in_with_apple    = true
      enable_sign_in_with_facebook = true
      team_id                      = local.yfl_apple_ios_team
      app_bundle_identifier        = local.yfl_apple_ios_app_id
    }
  }

I can do it manually for now, but it would be great if we could add this setting with terraform as its the sort of thing that gets forgotten especially when its hidden in advanced settings

**Comment by sergiught** [comment]
Hey @mattmillen888, thanks for your inquiry. This is currently supported through the client's `native_social_login`: https://github.com/alexkappa/terraform-provider-auth0/blob/master/docs/resources/client.md. 

I'll be closing this issue down but feel free to reopen if needed.
