### ISSUE TITLE
infinite_idle_token_lifetime/infinite_token_lifetime/idle_token_lifetime not longer work?

### ISSUE THREAD

**Issue by mattmillen888** [alexkappa/terraform-provider-auth0#337]
Have these features been deprecated?

  refresh_token {
    infinite_idle_token_lifetime = true
    infinite_token_lifetime = false
    idle_token_lifetime = 1296000
  }

as i now get:
An argument named "infinite_token_lifetime" is not expected here.
An argument named "idle_token_lifetime" is not expected here.
An argument named "infinite_idle_token_lifetime" is not expected here.

when i do terraform plan

**Comment by kpurdon** [comment]
Maybe related, though I do have the ability to use the fields. On 0.19.0 I'm now seeing the following when not specifying either of these values:

```
          - idle_token_lifetime          = 2591999 -> null
          - infinite_idle_token_lifetime = true -> null
```

I'm able to set the values to their defaults (0, true) and see no diff, but I'd expect these to be optional.

My replication path:

- do not have them set in terraform
- plan, see the output above
- set them to output above, see `2591999 -> 0`
- set to 0, true ... plan, no diff

Unfortunately even after this I now get a permanent diff of

```
          ~ idle_token_lifetime          = 2591999 -> 0
```

**Comment by kpurdon** [comment]
@alexkappa I'm going to start looking into this, but does anything recent spark your memory on the terraform or go side?

**Comment by woz5999** [comment]
@kpurdon the minimum value for token lifetime is 1, not 0. the API is probably silently rejecting the update to 0

https://auth0.com/docs/tokens/refresh-tokens/configure-refresh-token-expiration

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/24 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
