### ISSUE TITLE
Deploy the Twitter connection via Terraform 

### ISSUE THREAD

**Issue by sureshkrishnan-mr** [alexkappa/terraform-provider-auth0#339]
Deploy the Twitter connection via Terraform  (twitter social registration).

It looks like terraform for auth0 twitter details is not working as intended (I can see google-oauth2 and facebook working fine though). It always reports that terraform plan will update the twitter connection, the terraform apply tries to update it but no changes go through.

The terraform config is set correctly from our side, it looks like a bug in the Auth0 terraform, or doesn't have any implementation for it yet?

resource "auth0_connection" twitter {
  name     = "${module.default_label.id}-twitter"
  strategy = "twitter"
  options {
    client_id     = var.social_twitter_id
    client_secret = var.social_twitter_secret
    scopes        = var.social_twitter_scopes
  }
  enabled_clients = [auth0_client.default.id]
}

**Comment by yvovandoorn** [comment]
Hi @sureshkrishnan-mr! The support is there, but I am curious to know which particular setting its continually updating. If you did a [GET](https://auth0.com/docs/api/management/v2#!/Connections/get_connections_by_id) on the connection object after a Terraform run, is there a mismatch in what you're sending to your Auth0 tenant and is in your plan?

**Comment by sergiught** [comment]
Closing this due to inability to replicate and further info missing from the issue.
