### ISSUE TITLE
Request scopes in provider configuration

### ISSUE THREAD

**Issue by btilford** [alexkappa/terraform-provider-auth0#343]
### Description

In the case permissions aren't automatically added for the management api the provider needs to be configured to request the scopes it needs.

### Potential Terraform Configuration

```hcl
provider "auth0" {
  domain = "<domain>"
  client_id = "<client-id>"
  client_secret = "<client-secret>"
  debug = "<debug>"
  scopes = [
    "read:client_grants",
    "delete:client_grants",
    "create:client_grants",    
  ]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/25 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
