### ISSUE TITLE
Unsupported Connection Strategy ADFS

### ISSUE THREAD

**Issue by ScottBouloutian** [alexkappa/terraform-provider-auth0#344]
Hi, I am trying to use the adfs strategy for the auth0_connection resource. The documentation lists this as a valid strategy, however when I try to use it there is a warning that reads "Unsupported connection strategy adfs". I have narrowed this down to the expandConnection function in structure_auth0_connection.go. Is this an issue or is there something that I am missing?

**Comment by sergiught** [comment]
Hey @ScottBouloutian, thanks for reporting this issue and apologies for the late reply. Is this still happening? And could you provide a reproducible terraform config for us? 🙏🏻

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/26 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
