### ISSUE TITLE
'email' connection options are in the wrong location

### ISSUE THREAD

**Issue by rosebui** [alexkappa/terraform-provider-auth0#346]
### Description

The `auth0_connection` configuration for the `email` connection is expecting the wrong shape, which ultimately leads to the creation of passwordless connections to fail.

The Management API expects `email` options in the following nested shape:

```
resource "auth0_connection" "my_passwordless_connection" {
  strategy = "email"
  ...

  options {
    email {
      template = "<html>...</html>"
      from = "Example <example@example.com>"
      syntax = "liquid"
      subject = "Welcome to Example"
    }
  }
}
```

But this flattened shape is what is accepted by this repository:
```
resource "auth0_connection" "my_passwordless_connection" {
  strategy = "email"
  ...

  options {
    template = "<html>...</html>"
    from = "Example <example@example.com>"
    syntax = "liquid"
    subject = "Welcome to Example"
  }
}
```

### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/alexkappa/auth0 v0.19.0
```

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "my_passwordless_connection" {
  name                 = "Magic Link"
  strategy             = "email"
  enabled_clients      = []
  is_domain_connection = false
  options {
    scopes = ["openid profile"]
    name   = "email"
    disable_signup         = false
    brute_force_protection = true
    totp {
      length    = 6
      time_step = 180
    }
    email {
      template = "<html>...</html>"
      from     = "Example <example@example.com>"
      syntax   = "liquid"
      subject  = "Welcome to Example"
    }
  }
}
```

### Expected Behavior

Given the following configuration, an email connection is created via the Management API
```
resource "auth0_connection" "my_passwordless_connection" {
  strategy = "email"
  ...

  options {
    email {
      template = "<html>...</html>"
      from = "Example <example@example.com>"
      syntax = "liquid"
      subject = "Welcome to Example"
    }
  }
}
```

### Actual Behavior

Errors:
`An argument named "email" is not expected here.`
`Blocks of type "email" are not expected here.`

On the other hand, given the currently supported syntax, there is no way to pass in the email template.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Josh-a-e** [comment]
Yeah, I'd just like to point out that I ran into this issue and found it super confusing.
