### ISSUE TITLE
Support setting Company Logo for Universal Login

### ISSUE THREAD

**Issue by toshi1127** [alexkappa/terraform-provider-auth0#347]
### Description

Is it possible to set the Company Logo for Universal Login?
I thought it would be useful to be able to set this in addition to Primary Color and Page Background Color.

![image](https://user-images.githubusercontent.com/32378535/111036770-425e3b80-8464-11eb-896a-7f8362915b91.png)

Also, is it possible for me to attempt to implement this feature?

### New or Affected Resource(s)

* auth0_tenant

### Potential Terraform Configuration

```hcl
resource "auth0_tenant" "example" {
  universal_login {
    logo_uri = "https://example.com/image.png"
    colors {
      page_background = "#000000"
      primary         = "#0059d6"
    }
  }
}
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by yvovandoorn** [comment]
Hi @toshi1127. Thank you for the enhancement request! It looks very similar to #354. As the support for the upstream SDK already exposes the endpoint, do you mind submitting a PR with the first attempt? I and others can guide you along the way!

**Comment by toshi1127** [comment]
@yvovandoorn 
I can implement this!
I will create a PR as soon as the implementation is complete.
