### ISSUE TITLE
Getting auth0 domain attribute from auth0_client resource?

### ISSUE THREAD

**Issue by jleclanche** [alexkappa/terraform-provider-auth0#352]
Is there a way to retrieve the auth0 domain set for a particular client, if no custom domain is set? It doesn't look like there is any `domain` attribute exposed in `auth0_client` resources.

**Comment by galkin** [comment]
`auth0` provider configuration is:
```
provider "auth0" {
  domain = "<domain>"
  client_id = "<client-id>"
  client_secret = "<client-secret>"
  debug = "<debug>"
}
```

Every client has the same domain as at the provider config.

@jleclanche, could you reuse domain value?

**Comment by jleclanche** [comment]
Reusing domain value is not ideal. In my case it's what I'm doing but it's
not the correct dependency chain.
This is similar to the need of retrieving aws region from an aws provider.
The awd Terraform module solved this by having an aws_region data provider.
My suggestion would be to simply expose the domain as an attribute of
auth0_client.

**Comment by galkin** [comment]
@jleclanche it looks like we need feature request.

**Comment by jleclanche** [comment]
Right, I wasn't sure whether to file this as a feature request in case it already was possible somehow.

**Comment by yvovandoorn** [comment]
Just to understand the request. You want to get the complete domain name of your auth0 tenant (e.g. tenant.eu.auth0.com) from inside your Auth0 tenant?

**Comment by jleclanche** [comment]
Correct.

**Comment by yvovandoorn** [comment]
I think the only public API inside of the tenant where publish the domain name is of the `Auth0 Management API` resource server that every tenant must have. It's a guaranteed resource to be present in all tenants. 

Besides that its encoded in the JWT itself it is using to talk to the tenant.

**Comment by sergiught** [comment]
Closing this down as the Auth0 Management API does not directly return this within the response when retrieving a client, https://auth0.com/docs/api/management/v2#!/Clients/get_clients_by_id, and we are already knowing the full domain when setting up the provider.

If needed please reopen an issue at https://github.com/auth0/terraform-provider-auth0.
