### ISSUE TITLE
Universal login Branding Settings

### ISSUE THREAD

**Issue by thisarattr** [alexkappa/terraform-provider-auth0#354]
Hi Everyone,
I think it will be nice to have the ability to configure the auth0 branding setting via the TF provider. That helps to set up branding settings and upload/crud universal login liquid template. Refer to below api.
https://auth0.com/docs/api/management/v2/#!/Branding/get_branding

This could not be  updated via console, it's only available via api.

Thanks!

**Comment by yvovandoorn** [comment]
Hi @thisarattr the support for this is available in https://github.com/go-auth0/auth0/. Would you be open to taking the first PR at floating this support in the provider?

**Comment by kpurdon** [comment]
@yvovandoorn @alexkappa looks like this was merged, but a new release has not been cut yet. Can we get a new release?

**Comment by sergiught** [comment]
Closing this down as support was replicated within the provider as well. :)
