### ISSUE TITLE
Upon applying any changes getting "oauth2: cannot fetch token"

### ISSUE THREAD

**Issue by art-i-svsg** [alexkappa/terraform-provider-auth0#358]
### Description

When running initial terraform apply - resources are created normally. When running apply again after successful first run, getting following on all resources: 

Error: Get "https://smth.us.auth0.com/api/v2/hooks/id": oauth2: cannot fetch token: 500 Internal Server Error
Response: {"error":"server_error","error_description":"Script generated an unhandled asynchronous exception."}

And this error appears for every Auth0 resource previously created. 

### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/alexkappa/auth0 v0.19.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

Tried v0.14.7 of TF as well - same result. 

### Affected Resource(s)

* auth0_resource_server
* auth0_tenant
* auth0_hook
* auth0_connection
* auth0_custom_domain

### Terraform Configuration Files

Here is how provider is configured:

```hcl
terraform {
    backend "s3" {
      bucket = "***"
      key = "auth0/***"
      region = "us-east-1"
      encrypt = true
    }
}

provider "auth0" {
  domain = var.domain
  client_id = var.client_id
  client_secret = var.client_secret
}

```

### Expected Behavior

Any new changes should be applied. 

### Actual Behavior

Errors appear all the time and unable to apply any changes. 

### Steps to Reproduce

1. `terraform apply`

**Comment by noahgary** [comment]
I think you also need to reference your provider in a `required_providers` object like this:
```
terraform {
  required_providers {
    auth0 = {
      source = "alexkappa/auth0"
      version = "0.21.0"
    }
  }
}
```

Not sure that's your problem but it may be a part of it.

**Comment by sergiught** [comment]
Hello @art-i-svsg, is this issue still present?

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/27 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
