### ISSUE TITLE
Permanent Diff - Auth0 Client - Custom Login Page Preview

### ISSUE THREAD

**Issue by kpurdon** [alexkappa/terraform-provider-auth0#360]
Having an odd issue that I think may ultimately be an Auth0 API bug. In my terraform `auth0_client` resources I do not specify any custom login page settings (as they are optional). I have this configured under `Branding -> Universal Login` in the Auth0 Management UI. Until today this was working perfectly, but I'm now seeing a permanent terraform diff for my clients on the `custom_login_page_preview` field only.

These are the fields from the API:

<img width="718" alt="Screen Shot 2021-03-30 at 5 26 44 PM" src="https://user-images.githubusercontent.com/5130441/113069343-581a7300-917d-11eb-92ed-2e9e05b7180d.png">

When I make the API request directly I do not see `custom_login_page` returned but I do end up seeing `custom_login_page_preview` always returned now. I suspect this is the bug.

Any thoughts? Can I provide additional helpful information?

**Comment by gubbin** [comment]
I'm seeing the same behaviour on some of my clients as well, and that field is present when I call the Auth0 API with https://auth0.com/docs/api/management/v2#!/Clients/get_clients
I suspect that field is just informational and shouldn't be managed by TF.  I have a ticket open with Auth0 asking about it.

**Comment by gubbin** [comment]
For now, I'm adding `lifecycle { ignore_changes = [custom_login_page_preview] }` to make TF ignore it.

**Comment by gubbin** [comment]
In my env, it was because the HTML in Auth0 does not have a trailing newline, but my local copies do.  Removed the trailing EOL and TF stopped showing a difference.

**Comment by gubbin** [comment]
Auth0 confirmed to me that the `custom_login_page` params are informational and can be ignored:

> The custom login page and page preview attributes for each application are part of a legacy feature that we no longer use. 
> In the future, they may be removed from the management API responses. You can safely ignore those properties.

**Comment by kpurdon** [comment]
@gubbin thanks for the investigation? Are you up for opening a PR here to remove that field? If not I can find sometime later this week to do it.

**Comment by gubbin** [comment]
I'll take a look at the code and see if I'm up to it.
