### ISSUE TITLE
`upstream_params` in connection options

### ISSUE THREAD

**Issue by larryboymi** [alexkappa/terraform-provider-auth0#362]
### Description

It would be helpful if `upstream_params` were exposed in the `options` block for a connection, to help in the case of desired extra parameters, or modifying existing parameters, such as `login_hint`. We have some integrations with Auth0 where the `login_hint` is actually somewhat harmful to the user experience, and aliasing it to a different parameter has helped us get around it. Unfortunately, the option isn't present in this provider yet, but having it would help greatly in these cases.

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

Please see the bottom of this resource for the proposed `upstream_params` option.

```hcl
resource "auth0_connection" "saml" {
  for_each = {
    for conn in var.saml_connections : conn.name => conn
  }
  name         = each.value.name
  display_name = each.value.display_name
  strategy     = "samlp"
  enabled_clients = local.enabled_clients[each.value.enabled_app_env]

  options {
    sign_in_endpoint    = each.value.sign_in_endpoint
    sign_out_endpoint   = each.value.sign_out_endpoint
    signing_cert        = each.value.signing_cert != null ? filebase64("${path.module}/${each.value.signing_cert}") : null
    sign_saml_request   = true
    signature_algorithm = "rsa-sha256"
    digest_algorithm    = "sha256"
    protocol_binding    = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    domain_aliases      = each.value.domain_aliases
    fields_map          = each.value.fields_map
    upstream_params     = {
      alt_username      = {
        alias           = "login_hint"
      }
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by toshi1127** [comment]
May I work on this?

**Comment by larryboymi** [comment]
Please do @toshi1127 ... not sure who gives permission here but I bet @alexkappa welcomes PR's

**Comment by abbaspour** [comment]
How did you go @toshi1127 ? I also need this.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/29 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
