### ISSUE TITLE
"authParams" for SMS and Email Passwordless connection options

### ISSUE THREAD

**Issue by yinzara** [alexkappa/terraform-provider-auth0#365]
### Description

The Auth0 Passwordless Email and SMS connection options both support an "authParams" attribute that's a key value pair map of string->string.   It is currently implemented in the auth0 go library, but not in the terraform provider

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

```hcl
resource auth0_connection "sms" {
     name = "sms"
     strategy = "sms"
     options {
        auth_params = {
           scope = "openid profile mycustomscope"
        }
     }
}
```

### References

I could not find any reference to this configuration parameter in Auth0 Documentation but it is definitely available via the Management API.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gardarik** [comment]
Was looking for that too. Couldn't find it.

**Comment by gardarik** [comment]
I also receive this error on `terraform plan`
I don't pass `authParams`, but I have `email` connection with `authParams` filled manually.

```
Error: json: cannot unmarshal string into Go struct field ConnectionOptionsEmail.authParams of type map[string]string
```

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/31 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
