### ISSUE TITLE
Setting allowed_logout_urls to an empty list does not clear allowed logout URLs

### ISSUE THREAD

**Issue by mikehfaber** [alexkappa/terraform-provider-auth0#372]
### Description

If I set allowed_logout_urls to an empty list for an auth0_client, that doesn't change the Allowed Logout URLs in the Auth0 application when there were URLs allowed before.

### Terraform Version

```
Terraform 0.14.7
+ provider.auth0 0.19.0
```

### Affected Resource(s)

* auth0_client

### Terraform Configuration Files

Before:

```hcl
resource "auth0_client" "SomeApp" {
  name                        = "Some App"
  allowed_logout_urls         = ["https://localhost:4200/", "https://localhost:8888/"]
}
```

After:

```hcl
resource "auth0_client" "SomeApp" {
  name                        = "Some App"
  allowed_logout_urls         = []
}
```

### Expected Behavior

The Allowed Logout URLs field for the Auth0 application should be cleared so that there are no longer any allowed logout URLs.

### Actual Behavior

The Allowed Logout URLs field was unchanged, and kept the URLs that were set before.

### Steps to Reproduce

1. `terraform apply`

### Debug Output

https://gist.github.com/mikehfaber/e9608347c800f95aebae6c96d04e778a

### Panic Output

None

### Important Factoids

None

### References

None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by apamildner** [comment]
It probably have the same root problem as described here https://github.com/alexkappa/terraform-provider-auth0/issues/325. It's an unfortunate marshalling issue.

**Comment by sergiught** [comment]
This relates to several other issues that are present within the provider and I have captured this along with the others within https://github.com/auth0/terraform-provider-auth0/issues/14. 

As this repo has moved over at https://github.com/auth0/terraform-provider-auth0 please open new issues over there from now on.
