### ISSUE TITLE
Recent changes to hook.md to describe secrets have been reverted

### ISSUE THREAD

**Issue by WesleySSmith** [alexkappa/terraform-provider-auth0#377]
I'm trying to using the new ability for the hook resource to include secrets.  When I looked in the documentation file https://github.com/alexkappa/terraform-provider-auth0/blob/master/docs/resources/hook.md I found that secrets aren't mentioned. 

But when I looked at the history of that file, it appears that the documentation for secrets was added on April 12th via 77a86d1cd78c4, but then reverted on April 14th by 094cf06dd.  From what I can see, the changes to hook.md weren't related to the commit that was being reverted, and it seems like reverting that file was not correct.  

Should the documentation changes in 77a86d1cd78c4 be reapplied to hook.md?  Or was that documentation removed for some good reason?

**Comment by yvovandoorn** [comment]
@WesleySSmith there is no good reason this was removed other then that the undoing of that PR, took those changes with it (likely as it branched during that commit). 

I'll put it back in today!
