### ISSUE TITLE
auth0_branding fails with an error 

### ISSUE THREAD

**Issue by RishikeshDarandale** [alexkappa/terraform-provider-auth0#380]
### Description

When added `auth0_branding` resource, got an error saying `Error: 404 Not Found: Template does not exist.`

### Terraform Version

```
Terraform v0.14.9
+ provider registry.terraform.io/alexkappa/auth0 v0.21.0
+ provider registry.terraform.io/hashicorp/local v2.0.0

Your version of Terraform is out of date! The latest version
is 0.15.0. You can update by downloading from https://www.terraform.io/downloads.html

```

### Affected Resource(s)

* auth0_branding

### Terraform Configuration Files

```hcl
# This was already existing with 0.20.0 version and imported using terraform import
resource "auth0_tenant" "tenant" {
  friendly_name   = "My Tenant"
  enabled_locales = ["en"]
  flags {
    enable_public_signup_user_exists_error = true
    enable_custom_domain_in_emails         = true
  }
  universal_login {
    colors {
      primary         = "#0059d6"
      page_background = "#000000"
    }
  }
}

# this is also an existing resource
resource "auth0_prompt" "prompt" {
  universal_login_experience = "new"
}

resource "auth0_branding" "my-brand" {
  logo_url = "<my_image_link>"
  colors {
    primary = "#0059d6"
    page_background = "#000000"
  }
}
```

terraform plan showed below changes

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # auth0_branding.transformco-brand will be created
  + resource "auth0_branding" "my-brand" {
      + favicon_url = (known after apply)
      + id          = (known after apply)
      + logo_url    = "<my_image_url>"

      + colors {
          + page_background = "#000000"
          + primary         = "#0059d6"
        }
    }

```

Once applied above changes, the changes got reflected in tenant. But, failed with error mentioned above.

### Expected Behavior

Resource should be created without any error.

### Actual Behavior

The resource got created and I see the updated values under my tenant! But, failed with below error

```
Error: 404 Not Found: Template does not exist.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- Using custom domain with tenant
- As shown colors were already defined under `auth0_tenant` resource.
- Using new universal login

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kpurdon** [comment]
As a workaround we were able to manually delete the branding resource from state and re-plan/apply. That seems to have resolved the issue.

The API for the branding universal login template was returning:

```
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "Template does not exist.",
  "errorCode": "inexistent_templates_universal_login"
}
```

**Comment by RishikeshDarandale** [comment]
> As a workaround we were able to manually delete the branding resource from state and re-plan/apply. That seems to have resolved the issue.
> 
> The API for the branding universal login template was returning:
> 
> ```
> {
>   "statusCode": 404,
>   "error": "Not Found",
>   "message": "Template does not exist.",
>   "errorCode": "inexistent_templates_universal_login"
> }
> ```

I removed the branding resource from state manually, then reapplied the changes. I still get the same error!

**Comment by jackton1** [comment]
Any updates on this getting a similar error.

**Comment by sunnz** [comment]
This is my workaround to add or apply any changes to the resource `auth0_branding.this`:

  - turn off `enable_custom_domain_in_emails` and apply changes
  - add / uncomment the `auth0_branding` resource and apply changes
  - comment out the `auth0_branding` resource (again) and remove it from the state: `terraform state rm auth0_branding.this`
  - turn `enable_custom_domain_in_emails` back on again and apply changes

**Comment by davidski** [comment]
It's been terrific seeing the uptick in releases lately. Is there anything we in the community could do to prioritize getting this fix merged? This currently hard stops applies in our environment, forcing us to do janky `--target` workarounds. Would ❤️  the heck out of a fix for this!

**Comment by sergiughf** [comment]
Hey @davidski, thanks for raising visibility on this! I'm gonna start diving into the issue ASAP.

**Comment by sergiughf** [comment]
Hey folks, appreciate you raising this issue. This is now fixed within https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.26.1.
