### ISSUE TITLE
auth0_branding resource requires font all time

### ISSUE THREAD

**Issue by galkin** [alexkappa/terraform-provider-auth0#381]
### Description

auth0_branding 

### Terraform Version

```
Terraform 0.14.10
+ provider.auth0 0.21.0
```

### Affected Resource(s)

* auth0_branding

### Terraform Configuration Files

```hcl
resource "auth0_branding" "my_brand" {
    logo_url = "https://mycompany.org/logo.png"
    favicon_url = "https://mycompany.org/favicon.ico"
    colors {
        primary = "#0059d6"
        page_background = "#000000"
    }
}
```

### Expected Behavior

The second `terraform apply` will not affect resource

### Actual Behavior

Every `terraform apply` update resource by deleting `font`.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by yvovandoorn** [comment]
Hi @galkin, what is the value it is deleting for `font`? Is/was there a URL set but now not anymore?

I know the `branding` endpoint requires the sending of `null` in order to remove something. If you were to do a GET request on the end point (https://auth0.com/docs/api/management/v2#!/Branding/get_branding), what is the output.

Thanks.

**Comment by kpurdon** [comment]
I just ran into this as well. Here is the API response:

```
{
  "colors": {
    "primary": "#0D8B7F",
    "page_background": "#F8F8F8"
  },
  "favicon_url": "https://storage.googleapis.com/syndio-global-logos/syndio-favicon.png",
  "logo_url": "https://storage.googleapis.com/syndio-global-logos/syndio-logo-dark.png"
}
```

In terraform I've tried excluding font, including `font {}`, lifecycle ingoring it and nothing seems to work.

The underlying error seems to be:

```
Error: 400 Bad Request: Payload validation error: 'Too few properties defined (0), minimum 1' on property font (Custom font settings).
```

**Comment by CalebDelbridge** [comment]
Setting this seems to suppress the bug
```
  font {
    url = null
  }
```

**Comment by ClaudiaJ** [comment]
The payload to API is including a field `"font":{}`, and the API is rejecting it with the HTTP 400 error mentioned.

I wasn't able to get `font { url = null }` to work, it looked like it might but any updates to the Branding resource (e.g. favicon, colors, logo URL) would just trip the error again.

In the payload to api/v2/branding, `"font":null` is fine, `"font":{"url":null}` also is fine, or omitting font field altogether is fine, but `"font":{}` that is emitted when provider tries to update the resource will result in the same error.

The functionality to adjust this font doesn't seem to be exposed anywhere in the UI, and I'm not yet too clear what it affects in the resulting Login pages without more experimenting.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/32 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
