### ISSUE TITLE
Missing `options` when importing a `connection` object

### ISSUE THREAD

**Issue by atellezr** [alexkappa/terraform-provider-auth0#385]
### Description

When importing a `connection` object, the `options` are not imported.

I had a database connection defined in the Auth0 tenant, and I wanted to import it in Terraform. The database has custom scripts defined in the tenant, and what I wanted is to import everything related to that object into my local terraform configuration.

If I use the nodejs CLI (`auth0-deploy-cli`) I can get the connection configuration, including the `options` and, among others, the custom scripts.

And if I invoke directly the API `/api/v2/connections/con_AAAAAAAAAAAAAAAA` I can see the `options` with its attributes as well.

### Terraform Version

```
$ terraform -v
Terraform v0.14.4
+ provider registry.terraform.io/alexkappa/auth0 v0.20.0
```

(although there's a newer version, the v0.21.0, checking the code there are no significant differences related to the `options` object itself)

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

At the moment of executing the import, the configuration that I have in Terraform related to the connection is only this one:

```hcl
resource "auth0_connection" "my_connection" {}
```

### Expected Behavior

I expect to import the `options` attribute with all its attributes (`mfa`, `customScripts`, ...), as part of the import process of the whole object.

### Actual Behavior

The `options` attribute is imported as an empty array. No child attributes are imported

### Steps to Reproduce

1. Prepare the Terraform configuration object (see _Terraform Configuration Files_ section)

2. Executed the import command:

```
$ terraform import auth0_connection.my_connection con_AAAAAAAAAAAAAAAA
auth0_connection.my_connection: Importing from ID "con_AAAAAAAAAAAAAAAA"...
auth0_connection.my_connection: Import prepared!
  Prepared auth0_connection for import
auth0_connection.lp_users: Refreshing state... [id=con_AAAAAAAAAAAAAAAA]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

3. Verify the state of the imported object: it seems that the import went well, but when I have a look into the state (`terraform state show auth0_connection.my_connection`), I don't see the `options` attribute. In the Terraform state file I see the object as an empty array:

```
    {
      "mode": "managed",
      "type": "auth0_connection",
      "name": "my_connection",
      "provider": "provider[\"registry.terraform.io/alexkappa/auth0\"]",
      "instances": [
        {
          "schema_version": 2,
          "attributes": {
            "display_name": null,
            "enabled_clients": [
...
            ],
            "id": "con_AAAAAAAAAAAAAAAA",
            "is_domain_connection": false,
            "name": "MyConnection",
            "options": [],
...
```

### Debug Output

https://gist.github.com/atellezr/c8e336df73e3575ebf58e87f8ab4c676

### Panic Output

Not applicable

### Important Factoids

No, nothing remarkable

### References

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/33 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
