### ISSUE TITLE
Add include_email_in_redirect to auth0_email_template

### ISSUE THREAD

**Issue by galkin** [alexkappa/terraform-provider-auth0#388]
### Description

This is quote from [documentation](https://auth0.com/docs/email/customize-email-templates/email-template-descriptions#redirect-to-results-for-verification-email-template
):
> You can prevent sending the email addresses on the redirect links by updating the email templates using the Management API. For example:
> 
> PATCH /api/v2/email-templates/reset_email { "includeEmailInRedirect": false } or,
> 
> PATCH /api/v2/email-templates/verify_email { "includeEmailInRedirect": false }
> 

We have this feature at `gopkg.in/auth0.v5` from go-auth0/auth0 [5.8.0](https://github.com/go-auth0/auth0/blob/master/CHANGELOG.md#v580), but we don't have the provider

### New or Affected Resource(s)

* auth0_email_template

### Potential Terraform Configuration

```hcl
resource "auth0_email_template" "my_email_template" {
  template = "welcome_email"
  body = "<html><body><h1>Welcome!</h1></body></html>"
  from = "welcome@example.com"
  result_url = "https://example.com/welcome"
  subject = "Welcome"
  syntax = "liquid"
  url_lifetime_in_seconds = 3600
  enabled = true

  depends_on = [ "${auth0_email.my_email_provider}" ]
  // added
  include_email_in_redirect = true
}
```

### References

N/A 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/34 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
