### ISSUE TITLE
Infinite plan: user_metadata

### ISSUE THREAD

**Issue by mwarkentin** [alexkappa/terraform-provider-auth0#392]
### Description

We have some users in auth0 which we've imported into terraform using this provider. There are some changes in `user_metadata` that are showing in the plan, but after applying, they show up again.

```
# auth0_user.money_admin_users["***+neb1@***.com"] will be updated in-place
  ~ resource "auth0_user" "money_admin_users" {
        email           = "***@***.com"
        name            = "***@***.com"
        nickname        = "***+neb1"
      ~ user_metadata   = jsonencode(
          ~ {
              - pw              = "" -> null
              - test-pw         = "" -> null
```

### Terraform Version

```
Terraform 0.13.7
+ provider.auth0 v0.21.0
```

### Affected Resource(s)

* `auth0_user`

### Terraform Configuration Files

```hcl
resource "auth0_user" "admin_users" {
  for_each        = local.admin_users
  connection_name = "Username-Password-Authentication"
  email           = each.key
  roles           = each.value.roles

  password = random_password.money_admin_initial_passwords[each.key].result
  user_metadata = jsonencode({
    "user-management" : "Terraform"
  })

  lifecycle {
    ignore_changes = [password, email_verified]
  }
}
```

### Expected Behavior

After apply, the user_metadata should be in sync between terraform and auth0, resulting in a no-op on next plan.

### Actual Behavior

There is always a change showing in the plan.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by multani** [comment]
To add further information: once something has been set by the Terraform provider, it's not possible *unset* it.

For example:

* I set the `user_metadata` to:
  ```hcl
  jsonencode({
    foo = "bar"
  })
  ```

* Then, if I updated the `user_metadata` with:
  ```hcl
  jsonencode({
    some = "thing"
  })
  ```

This results in the following being stored in Auth0:

```json
{
  "foo": "bar",
  "some": "thing"
}
```

However, if I set instead:

```hcl
jsonencode({
  foo = null
  some = "thing"
})
```

Then, this results in:

```json
{
  "some": "thing"
}
```

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/35 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
