### ISSUE TITLE
Tf Plan Error : invalid character '<' looking for beginning of value_

### ISSUE THREAD

**Issue by rajdeeprspl** [alexkappa/terraform-provider-auth0#393]
Hi There,

Can you please help me on the below described issue ?

I am getting this error while applying terraform plan or trying to import resources.

`**_Error: invalid character '<' looking for beginning of value_**`

But executing terraform validate its showing validation success .

Same code with different credentials working for a tenant but not to other one.

Is it something that I am missing ?

```Terraform version : 0.14.6

auth0_connection.google: Importing from ID "con_xxxxxxxxxxxxx"...
auth0_connection.google: Import prepared!
  Prepared auth0_connection for import
auth0_connection.google: Refreshing state... [id=con_xxxxxxxxxx]

Error: invalid character '<' looking for beginning of value

```

[terraform.txt](https://github.com/alexkappa/terraform-provider-auth0/files/6473513/terraform.txt)

I am also attaching terraform trace log in here.

Many Thanks.

rajdeep

**Comment by sergiught** [comment]
Hey @rajdeeprspl apologies for the late reply over here, is this issue still happening?

**Comment by rajdeeprspl** [comment]
> Hey @rajdeeprspl apologies for the late reply over here, is this issue still happening?

Hi @sergiughf,  thanks for reply. yes we still getting this error .

**Comment by sergiught** [comment]
Would you be able to provide us with a reproducible terraform config we can test @rajdeeprspl?

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/36 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
