### ISSUE TITLE
Is this the official repo of the auth0 provider?

### ISSUE THREAD

**Issue by red8888** [alexkappa/terraform-provider-auth0#395]
Little confused because I saw this, which seems to be outdated: https://github.com/hashicorp/terraform-provider-auth0

And it seemed like you also work on that one too? 

is this source like the community version of the provider or something? "alexkappa/auth0"

Thanks!

**Comment by ForsakenHarmony** [comment]
It does appear to be, hashicorp transitioned some providers to the community members who maintained them the most (in the old repo @alexkappa was also the primary contributor)

There's also the redirect from https://www.terraform.io/docs/providers/auth0/index.html

**Comment by red8888** [comment]
Ah that makes sense to me. "official" wasn't the proper word I suppose. I'll close this but super curious if auth0 has reached out to @alexkappa at all to officially support this? I've seen their official IaC thing and it kinda stinks lol.

Thanks!
