### ISSUE TITLE
Can I use this to terrform an auth0 "application"?

### ISSUE THREAD

**Issue by red8888** [alexkappa/terraform-provider-auth0#396]
Im a little new to auth0 so I'm wondering if maybe an auth0 "application" isn't a single resource but a bunch of them tied together or something because I see no **auth0_application** in the [docs](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs)
![image](https://user-images.githubusercontent.com/6265399/118193368-8e524000-b415-11eb-95a8-622a6417b88a.png)

Can I use this to create/configure all the "application" I create in my auth0 tenant? 

thanks!

**Comment by hoppalotta** [comment]
The terminology used in the provider is [auth0_client](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/client), a look at the documentation there should help point you in the right direction.
