### ISSUE TITLE
Support sso_integration app_type for auth0_client resource

### ISSUE THREAD

**Issue by hoppalotta** [alexkappa/terraform-provider-auth0#397]
### Description

Auth0 clients of the "SSO Integration" type don't appear to be supported at this time. The specific case I'm trying to solve for is an integration with Tableau Server, see links below.  Thanks for publishing and maintaining this provider and also for your consideration on this issue!

### New or Affected Resource(s)

auth0_client

### Potential Terraform Configuration

```hcl
resource "auth0_client" "tableau" {
  name     = "Tableau Server"
  app_type = "sso_integration"
  ...
}

```

### References

* https://auth0.com/docs/sso
* https://auth0.com/docs/integrations/sso/tableau-server

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/37 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
