### ISSUE TITLE
Is there a way to not store client_secret in terraform state?

### ISSUE THREAD

**Issue by red8888** [alexkappa/terraform-provider-auth0#399]
I keep secrets out of my terraform state files, but I see (even though its marked sensitive) this provider is storing `client_secret` in the resource's state. Is there a way to not have it store the secret in state?

**Comment by alekc** [comment]
https://www.terraform.io/docs/language/state/sensitive-data.html

**Comment by sergiught** [comment]
Hey @red8888 thanks for the inquiry. The link provided by @alekc is quite useful and are recommendations coming directly from Hashicorp regarding dealing with sensitive data (secrets) inside the state. 

Currently the `client_secret` is marked as a `Sensitive` attribute and will not get displayed in logs or regular output. Future versions of Terraform may encrypt these in the future. 

Will be closing this issue down, but if needed please reopen at https://github.com/auth0/terraform-provider-auth0 as this repo has been moved over there.
