### ISSUE TITLE
Universal Login: Customize Text Prompts

### ISSUE THREAD

**Issue by nitrag** [alexkappa/terraform-provider-auth0#401]
### Description

Universal Login now has a custom text API to override the text. This is needed so I don't have to run cURL commands outside of terraform to customize our environment.

https://auth0.com/docs/universal-login/new-experience/text-customization-new-universal-login

### New or Affected Resource(s)

* auth0_branding?

Potentially?

```
resource "auth0_branding" "custom" {
    logo_url = xxxxx
    universal_login  {
        prompt {
            login {
                title       = "Hello, Welcome"
                description = "Log in to ${companyName} to continue to ${clientName}."
            }
            signup {
                 invalid-username = "Username can only contain characters: '${characters}' with a minumum length of ${min}."
            }
        }
    }
}
```

**Comment by GuiSim** [comment]
I would totally use this today.

Does anyone have an alternative mechanism they used to configure prompts?

**Comment by hoppalotta** [comment]
I'm new terraform provider development this but I did add [wip pr 474](https://github.com/alexkappa/terraform-provider-auth0/pull/474) that illustrates a possible approach for this issue. Happy to adjust the approach as needed but I am search for some feedback if anyone has a chance. Thanks!

**Comment by sergiughf** [comment]
Hey @nitrag, thanks for raising this issue! This is now supported under the latest release https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.26.0. Please take a look at it and let us know if you encounter any issues 🙏🏻 

I'll be closing this but feel free to reopen in case of need.
