### ISSUE TITLE
auth0_client_grants to manage all grants for an app or api authoritatively

### ISSUE THREAD

**Issue by red8888** [alexkappa/terraform-provider-auth0#403]
`auth0_client_grant` allows us to create a specific grant, but I want to fully control and track all grants made for an app or api. It makes sense to have a resource named like `auth0_client_grants` that takes a map/list of all grants configured for an application (or maybe api or make it configurable).

So if a user manually adds a grant terraform would see that change against the list of grants in the diff. Also, we could import an `auth0_client_grants` resource and it would find and reconcile all grants.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/39 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
