### ISSUE TITLE
Publishing a release for latest auth0 version bump

### ISSUE THREAD

**Issue by icrustandi** [alexkappa/terraform-provider-auth0#405]
I noticed that the change to bump the auth0 dependency from 5.15 to 5.17 has been merged, but we'd like to be able to use the auth0 tf provider to use this dependency, which I believe requires this repo to publish a new release. Could you please publish a new release?

The change we're interested in is mostly around the Google Apps enterprise connection.
https://github.com/go-auth0/auth0/releases/tag/v5.16.0

**Comment by vandevusse** [comment]
+1 on this, could we get eyes on releasing these changes?

**Comment by yvovandoorn** [comment]
#409 will address this.

**Comment by alexkappa** [comment]
Several versions have been published since this issue was reported. Please reopen if needed.
