### ISSUE TITLE
Better to provide a way to set `Auth0 Management API` permission.

### ISSUE THREAD

**Issue by zhaoyi0113** [alexkappa/terraform-provider-auth0#411]
### Description

There is API permission under `Applications -> API` tab. But this plugin doesn't support setting the `scopes` for `Auth0 Management API`.  Better to add that feature since it is kind of in-complete.

The configuration in auth0 console looks like below screenshot

![image](https://user-images.githubusercontent.com/3355579/123424615-6e14c400-d604-11eb-939a-c4c843cf717c.png)

**Comment by alexkappa** [comment]
Hi @zhaoyi0113, perhaps what you are looking for is the client grant?

https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/client_grant

**Comment by zhaoyi0113** [comment]
Hi @alexkappa , this is for client grant. But what I am looking for is the grant for `Auth0 Management API` under application. For example, if you open `Applications -> APIs`, you should be able to see two APIs on the list. One is the application itself, the other one is `Auth0 Management API`. 

The one you are saying is to configure the grant for the application itself. But I can't find a way to configure the `Auth0 Management API` grant for each application.

**Comment by alexkappa** [comment]
Let me try to clarify if we're both referring to the same thing.

`Auth0 Management API` can mean two things: an `API` (aka [`Resource Server`](https://auth0.com/docs/api/management/v2#!/Resource_Servers/get_resource_servers)) and an `Application` (aka [`Client`](https://auth0.com/docs/api/management/v2#!/Clients/get_clients)).  One of each is created for you for each tenant.

APIs can have scopes, these are all the permissions that an API supports. You can define those with a [`resource_server`](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/resource_server) using the `scopes` attribute.

Each [client](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/client) can be granted a subset (or all) of the scopes an API supports. This is done using [client grants](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/client_grant).

If what you want to achieve it so modify the _existing_ `Auth0 Management API` resource server, client, or client grant, you probably need to [import it](https://www.terraform.io/docs/cli/import/index.html) first.

**Comment by zhaoyi0113** [comment]
I think you mixed the concept of `application API` and `application API under auth0 management API`. They are two different scropts. I created an application `account-management-service` by using `auth0_client` and `auth0_resource_server`.

Below screenshot is the API page under the application. You can see that there are two application marked as selected, `account-management-service` itself and another one is `Auth0 Management API`. 

All the infomration you mentioned in the previous post is about configuration the application itself not `Auth0 Management API`.

The `Auth0 Management API` in the screenshot is selected manually in the Auth0 console rather than this terraform plugin. And this is what I am looking for.  This management API appears in every application I created in this account. And they can have different scope for each application.

What is the configuration I can use the configure the `Auth0 Management API` scope for each application?

![image](https://user-images.githubusercontent.com/3355579/123581297-ef47a300-d81e-11eb-866f-c370dd1b7cf6.png)

**Comment by alexkappa** [comment]
> What is the configuration I can use the configure the `Auth0 Management API` scope for each application?
> 
> ![image](https://user-images.githubusercontent.com/3355579/123581297-ef47a300-d81e-11eb-866f-c370dd1b7cf6.png)

The only way that I'm aware of is by using client grants. Perhaps I am not getting what you are trying to do, but you can verify yourself by examining the network requests when switching the Authorized/Unauthorized toggle.

<img width="1792" alt="Screen Shot 2021-06-29 at 11 20 53" src="https://user-images.githubusercontent.com/1204095/123772937-8a4a8680-d8cc-11eb-8f18-cd9abdf85a6f.png">

**Comment by zhaoyi0113** [comment]
Does this mean I have to manually toggle it on/off? I am looking for an automatic way to achieve this. Otherwise, it is hard to maintain the IaC.

**Comment by alexkappa** [comment]
Nope. I suggested it so it can point you to which API operation is used for the action you wish to take. If it is supported by the Auth0 Management API, chances are it will be supported by this provider.

From your description, I can only think of client grants. If I am misunderstanding your intentions, better check yourself what kind of operation you would like to perform and with that I can help you further.

**Comment by zhaoyi0113** [comment]
Yes you are right. I have checked, 

- when I turn it off, it sends DELETE to https://manage.auth0.com/api/client-grants/cgr_2Jeto864DcRO9yni
- when I turn it on, it sends POST to https://manage.auth0.com/api/client-grants

I compared with the other one and the different when turn it on is the audience is different.
