### ISSUE TITLE
Creating client under tenant

### ISSUE THREAD

**Issue by kuritonasu** [alexkappa/terraform-provider-auth0#412]
I hope that I'm not missing something obvious here, but how can a client/application be created under a specific tenant?

**Comment by paullalonde** [comment]
The auth0 API appears to only expose the default tenant. Presumably resources such as clients are created under it. That explains why there isn't an "id" attribute or equivalent on the `auth0_tenant` resource.

**Comment by alexkappa** [comment]
@kuritonasu unless I am missing something, the tenant is designated with your auth0 subdomain (e.g. <tenant>.eu.auth0.com) Perhaps you mean [organizations](https://auth0.com/docs/api/management/v2/#!/Organizations/get_organizations)?

**Comment by kuritonasu** [comment]
@alexkappa so if we're using multiple tenants we should be defining one _provider_ clause for each tenant, since the domain is declared in the provider?

**Comment by alexkappa** [comment]
I believe so @kuritonasu. To use multiple tenants (different domains) I'd look into the [`alias`](https://www.terraform.io/docs/language/providers/configuration.html#alias-multiple-provider-configurations) argument to your provider configuration/

**Comment by kuritonasu** [comment]
Thank you! Proceeding to close this issue.
