### ISSUE TITLE
user_id case sensitivity issues

### ISSUE THREAD

**Issue by ertanden** [alexkappa/terraform-provider-auth0#413]
We are using this module to configure roles etc for users which are imported (so not created by this plugin). Our users are created in Auth0 automatically from another identity provider connection.

However we are facing issues with the case sensitivity of the user_id. 

I think the root cause is the `StateFunction` in the User resource which always converts the `user_id` to lowercase.

https://github.com/alexkappa/terraform-provider-auth0/blob/2c67c32943e06042131250a350d8fbf791639c3a/auth0/resource_auth0_user.go#L35-L37

So this for us results in change detection for our user resources even though there's no change actually. 

Is there a specific reason why the StateFunc is defined to always convert user_id's to lowercase?

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/41 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
