### ISSUE TITLE
Add support for LogStream filters

### ISSUE THREAD

**Issue by epintos** [alexkappa/terraform-provider-auth0#427]
### Description

I'd like to request support for Log Stream filters parameters

### New or Affected Resource(s)

* auth0_log_stream
* The Go SDK will also require some updates

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/42 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
