### ISSUE TITLE
Environment tag?

### ISSUE THREAD

**Issue by sunnz** [alexkappa/terraform-provider-auth0#428]
Is it possible to set an environment tag like development, staging, and production in terraform?

When logging in to auth0 through the web it is under tenant settings, general.

**Comment by sergiught** [comment]
Hey @sunnz apologies for the late reply, however this feature is not currently available. We will be looking into adding this very soon. It will be available in the future at https://github.com/auth0/terraform-provider-auth0 as the repo has been moved.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/43 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
