### ISSUE TITLE
auth0 connection with samlp - Missing `signing_key` object in options

### ISSUE THREAD

**Issue by dev-usa** [alexkappa/terraform-provider-auth0#430]
### Description

When setting up Auth0 connection of type SAML, it does not seem possible to specify the `signing_key` object.

This is supported by the API as explained here - https://auth0.com/docs/protocols/saml-protocol/saml-sso-integrations/sign-and-encrypt-saml-requests#use-custom-certificate-to-sign-requests

```json
"signing_key": {
      "key": "",
      "cert": ""
}
```

### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

```hcl
resource "auth0_connection" "test_connection" {
  name      = "enterprise-saml-connection"
  strategy  = "samlp"
  options {
    signing_key = {
      key = file("${path.module}/x509.pem")
      cert = file("${path.module}/x509.pem")
    }
}
```

I am new to golang and also open source contribution. 

I did some digging and found some places where things need to change, like in `connection.go`, there is a struct `ConnectionOptionsSAML` that needs to be updated in the repo git@github.com:go-auth0/auth0.git with the `signing_key` attribute. However, I am not sure how to create a PR for that repo. (not seeing any instructions / markdown pages in there)

Also, given I am a new, I am not sure how to open a PR with the changes to this repo itself. 
Appreciate suggestions. 

Thank you

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dev-usa** [comment]
Created a PR - https://github.com/alexkappa/terraform-provider-auth0/pull/437/files?diff=unified&w=1

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/44 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
