### ISSUE TITLE
Add support for `metadataXml` and `metadataUrl` for creating `samlp` connections

### ISSUE THREAD

**Issue by tarfeef102** [alexkappa/terraform-provider-auth0#436]
### Description
Currently, `samlp` configurations have to be specced-out by field, which is tedious and painful. However, `auth0` has an answer for this: [metadata importing](https://auth0.com/docs/connections/enterprise/saml#create-a-connection-using-saml-metadata). If we could use this API and provide an XML or URL for the provider to fetch and compare to state, then configurations could be much simpler. This is especially helpful if you're working with third parties who may change their metadata configuration and expect you to pick up the changes and act on them without active collaboration.

### New or Affected Resource(s)
* auth0_connection

### Potential Terraform Configuration
```hcl
resource "auth0_connection" "example" {
  name = "Example-Connection"
  strategy = "samlp"
  options {
    metadataUrl = "https://some_site.com/some_doc.xml"
  }
```
or
```hcl
resource "auth0_connection" "example" {
  name = "Example-Connection"
  strategy = "samlp"
  options {
    metadataXml = data.local_file.xml.content
  }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alekc** [comment]
@tarfeef102 do you have a valid xml or url?

I've played around and I am getting this from the auth0
```
{"name":"Acceptance-Test-SAML-um6cij","strategy":"samlp","options":{"metadataXml":"\u003cxml\u003e...\u003c/xml\u003e"}}
{"statusCode":400,"error":"Bad Request","message":"The SAML Identity Provider URL is required","errorCode":"invalid_body"}

---
{"name":"Acceptance-Test-SAML-7ifkxp","strategy":"samlp","options":{"metadataUrl":"https://auth0-provider-test.eu.auth0.com/samlp/metadata?connection=Username-Password-Authentication"}}
{"statusCode":400,"error":"Bad Request","message":"The SAML Identity Provider URL is required","errorCode":"invalid_body"}
```

not sure if it's the case of the feature not working (since it's not even documented in their apis), or my data being invalid.

**Comment by tarfeef102** [comment]
> @tarfeef102 do you have a valid xml or url?
> 
> I've played around and I am getting this from the auth0
> 
> ```
> {"name":"Acceptance-Test-SAML-um6cij","strategy":"samlp","options":{"metadataXml":"\u003cxml\u003e...\u003c/xml\u003e"}}
> {"statusCode":400,"error":"Bad Request","message":"The SAML Identity Provider URL is required","errorCode":"invalid_body"}
> 
> ---
> {"name":"Acceptance-Test-SAML-7ifkxp","strategy":"samlp","options":{"metadataUrl":"https://auth0-provider-test.eu.auth0.com/samlp/metadata?connection=Username-Password-Authentication"}}
> {"statusCode":400,"error":"Bad Request","message":"The SAML Identity Provider URL is required","errorCode":"invalid_body"}
> ```
> 
> not sure if it's the case of the feature not working (since it's not even documented in their apis), or my data being invalid.

I can't provide a URL since those I've used are for partners at work, but I can say I've used this successfully . It'd look like the `metadataUrl` option in the linked docs, with a URL such as https://documentation.commvault.com/commvault/v11/others/products/web_console/external_authentication/saml_idp_metadata.xml.

**Comment by alekc** [comment]
Thx. So, Auth0 (as always) doesn't want to make this easy. In their docs they show that you can simply just pass one field (either xml or uri), in reality...

Request
```
{"name":"Acceptance-Test-SAML-lgsqi2","strategy":"samlp","options":{"metadataUrl":"https://documentation.commvault.com/commvault/v11/others/products/web_console/external_authentication/saml_idp_metadata.xml"}}
```
Response
```
{"statusCode":400,"error":"Bad Request","message":"The signing certificate is not valid. Please provide a .pem or .cer certificate base64 encoded public key","errorCode":"invalid_body"}
```

I've tried with 
```
{"name":"Acceptance-Test-SAML-f142vg","strategy":"samlp","options":{"signingCert":"-----BEGIN CERTIFICATE-----\nMIID6TCCA1ICAQEwDQYJKoZIhvcNAQEFBQAwgYsxCzAJBgNVBAYTAlVTMRMwEQYD\nVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRQwEgYDVQQK\nEwtHb29nbGUgSW5jLjEMMAoGA1UECxMDRW5nMQwwCgYDVQQDEwNhZ2wxHTAbBgkq\nhkiG9w0BCQEWDmFnbEBnb29nbGUuY29tMB4XDTA5MDkwOTIyMDU0M1oXDTEwMDkw\nOTIyMDU0M1owajELMAkGA1UEBhMCQVUxEzARBgNVBAgTClNvbWUtU3RhdGUxITAf\nBgNVBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEjMCEGA1UEAxMaZXVyb3Bh\nLnNmby5jb3JwLmdvb2dsZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK\nAoICAQC6pgYt7/EibBDumASF+S0qvqdL/f+nouJw2T1Qc8GmXF/iiUcrsgzh/Fd8\npDhz/T96Qg9IyR4ztuc2MXrmPra+zAuSf5bevFReSqvpIt8Duv0HbDbcqs/XKPfB\nuMDe+of7a9GCywvAZ4ZUJcp0thqD9fKTTjUWOBzHY1uNE4RitrhmJCrbBGXbJ249\nbvgmb7jgdInH2PU7PT55hujvOoIsQW2osXBFRur4pF1wmVh4W4lTLD6pjfIMUcML\nICHEXEN73PDic8KS3EtNYCwoIld+tpIBjE1QOb1KOyuJBNW6Esw9ALZn7stWdYcE\nqAwvv20egN2tEXqj7Q4/1ccyPZc3PQgC3FJ8Be2mtllM+80qf4dAaQ/fWvCtOrQ5\npnfe9juQvCo8Y0VGlFcrSys/MzSg9LJ/24jZVgzQved/Qupsp89wVidwIzjt+WdS\nfyWfH0/v1aQLvu5cMYuW//C0W2nlYziL5blETntM8My2ybNARy3ICHxCBv2RNtPI\nWQVm+E9/W5rwh2IJR4DHn2LHwUVmT/hHNTdBLl5Uhwr4Wc7JhE7AVqb14pVNz1lr\n5jxsp//ncIwftb7mZQ3DF03Yna+jJhpzx8CQoeLT6aQCHyzmH68MrHHT4MALPyUs\nPomjn71GNTtDeWAXibjCgdL6iHACCF6Htbl0zGlG0OAK+bdn0QIDAQABMA0GCSqG\nSIb3DQEBBQUAA4GBAOKnQDtqBV24vVqvesL5dnmyFpFPXBn3WdFfwD6DzEb21UVG\n5krmJiu+ViipORJPGMkgoL6BjU21XI95VQbun5P8vvg8Z+FnFsvRFY3e1CCzAVQY\nZsUkLw2I7zI/dNlWdB8Xp7v+3w9sX5N3J/WuJ1KOO5m26kRlHQo7EzT3974g\n-----END CERTIFICATE-----\n","metadataUrl":"https://documentation.commvault.com/commvault/v11/others/products/web_console/external_authentication/saml_idp_metadata.xml"}}
```

But got the 
```
{"statusCode":400,"error":"Bad Request","message":"The signing certificate is not valid. Please provide a .pem or .cer certificate base64 encoded public key","errorCode":"invalid_body"}
```

God knows what exactly they want. Best course of action would probably be opening a ticket and ask them which fields do they want.

**Comment by tarfeef102** [comment]
> Thx. So, Auth0 (as always) doesn't want to make this easy. In their docs they show that you can simply just pass one field (either xml or uri), in reality...
> - Snip - 
> God knows what exactly they want. Best course of action would probably be opening a ticket and ask them which fields do they want.

Right now, to get the certs into terraform (since we don't have url/xml support yet), I tend to take them, run em through [here](https://www.samltool.com/format_x509cert.php), copy it with headers, run that through `base64 -w 0`, and use that in my terraform config. That works reliably. If you decode with `base64 -di` it should give you back the cert as formatted by that online tool. Hopefully that helps

**Comment by alekc** [comment]
@tarfeef102 Ive added. support for those two fields in 1.1.1 (on my fork), could you try them out?

**Comment by tarfeef102** [comment]
> @tarfeef102 Ive added. support for those two fields in 1.1.1 (on my fork), could you try them out?

Based on that PR linked above, it doesn't seem like they actually do anything, though? Also I'm not sure I really have the ability to justify bringing something like this into a work environment, and I don't have a personal one I could do testing in.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/46 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
