### ISSUE TITLE
Add support for tenant members

### ISSUE THREAD

**Issue by ForsakenHarmony** [alexkappa/terraform-provider-auth0#440]
### Description

Would be nice to be able to configure auth0 tenant members, currently have to add admins to every tenant individually by going through the settings

### New or Affected Resource(s)

* auth0_member / auth0_tenant

### Potential Terraform Configuration

```hcl
resource "auth0_member" "member" {
	email = "hello@example.com"
	role = "admin"
}
```
or something like
```hcl
resource "auth0_tenant" "tenant" {
	member {
		email = "hello@example.com"
		role = "admin"
	}
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
Hello folks, apologies for the late reply on this issue. As @mnylen mentions unfortunately this is not yet available under the Management API and as such we aren't able to add support for this yet. 

Furthermore this repository has moved under the Auth0 org at https://github.com/auth0/terraform-provider-auth0 and we will continue to maintain it over there and add this feature as soon as it's available in the Management API.

For now I'll be closing this down.

**Comment by ForsakenHarmony** [comment]
Oh, was it not possible to transfer the repo directly?
