### ISSUE TITLE
Support flag "disable_management_api_sms_obfuscation" on tenant

### ISSUE THREAD

**Issue by brandonbirdj** [alexkappa/terraform-provider-auth0#442]
### Description

Please add support for the flag `disable_management_api_sms_obfuscation` to the auth0_tenant
### New or Affected Resource(s)

* auth0_tenant

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- http://auth0.github.io/auth0.net/api/Auth0.ManagementApi.Models.TenantFlags.html#Auth0_ManagementApi_Models_TenantFlags_DisableManagementApiSmsObfuscation

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alekc** [comment]
Support for this flag (and several others) first must be implemented in go sdk.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/47 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
