### ISSUE TITLE
Unable to create Datadog log stream

### ISSUE THREAD

**Issue by paweusz** [alexkappa/terraform-provider-auth0#444]
### Description

Creating Auth0 log stream for Datadog results in error while applying terraform plan.

### Terraform Version

Terraform v1.0.5
+ provider registry.terraform.io/alexkappa/auth0 v0.21.0

### Affected Resource(s)

* resource "auth0_log_stream"

### Terraform Configuration Files

```hcl
resource "auth0_log_stream" "datadog_stream" {
  name = "Datadog_log_stream"
  type = "datadog"
  sink {
    datadog_region = "US"
    datadog_api_key = "xxx"
  }
}
```

### Expected Behavior

Terraform should create log stream in auth0.

### Actual Behavior

While executing terraform apply there's: Error: 400 Bad Request: Payload validation error: 'Data does not match any schemas from 'oneOf''.

### Steps to Reproduce

1. `terraform apply`

### Debug Output

https://gist.github.com/paweusz/1a777d8a83c317394d340d69fbae35ce

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alekc** [comment]
Use lower case 

```
resource "auth0_log_stream" "datadog_stream" {
  name = "Datadog_log_stream"
  type = "datadog"
  sink {
    datadog_region = "us"
    datadog_api_key = "xxx"
  }
}
```

See https://github.com/alekc/terraform-provider-auth0/pull/8 for full explanation

**Comment by alexkappa** [comment]
@paweusz does @alekc's suggestion solve your issue? @alekc would you be willing to submit a PR?

**Comment by paweusz** [comment]
Yes, it does. Thank you very much.
