### ISSUE TITLE
email template change_password not updating

### ISSUE THREAD

**Issue by palatisampath** [alexkappa/terraform-provider-auth0#450]
I am trying to update the email template change_password, but its not getting updated when viewed in auth0, whereas blocked_email_template is getting updated and can see the changes in auth0. So not sure whats the issue

Here is my resource config file:
resource "auth0_email_template" "change_password_email_template" {
        template = "change_password"
        from = var.NO_REPLY_EMAIL
        subject = "{% if user.email_verified %} Reset your org account {% else %} Verify your email address {% endif %} in {{tenant}}"
        body = file("./change_password_email_template.html")
        result_url = ""
        url_lifetime_in_seconds = 86400
        syntax = "liquid"
        enabled = true
        depends_on = [auth0_email.aws_email_provider]
}

**Comment by louisa-ba** [comment]
I had the same issue and I found setting template to "reset_email" worked.

**Comment by sergiught** [comment]
Hey @palatisampath apologies for the late reply on this issue. As @louisa-ba mentions setting the template to `reset_email` should help. 

I'll be closing this issue down but in case of encountering another one please open a new issuer at https://github.com/auth0/terraform-provider-auth0 as this provider has been moved under the Auth0 Org.
