### ISSUE TITLE
Build for darwin_arm64

### ISSUE THREAD

**Issue by jodok** [alexkappa/terraform-provider-auth0#452]
### Description

When trying to `terraform init` on an M1 Silicon based Apple Computer the download fails

```
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/alexkappa/auth0 v0.17.1 does not have a package available for your current platform,
│ darwin_arm64.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by brandonbyskov** [comment]
The master branch already contains an update to support `darwin_arm64`, but a new version of this provider needs to be released for the update to be available.

I'm not sure when that will happen.

**Comment by alekc** [comment]
@jodok if you are in a hurry you can try my fork, it's released on terraform registry and has `terraform-provider-auth0_1.1.0_darwin_arm64.zip` (although note, that there are some breaking changes described in 1.0.0 release)

**Comment by jodok** [comment]
thanks a lot @alekc !

**Comment by alexkappa** [comment]
Closing as the last couple of releases included arm binaries
