### ISSUE TITLE
Add support for management of organizations

### ISSUE THREAD

**Issue by jketcham** [alexkappa/terraform-provider-auth0#454]
### Description

Add the ability for the auth0 terraform provider to create/update/delete [organizations](https://auth0.com/docs/organizations) within an auth0 tenant.

### New or Affected Resource(s)

* auth0_organization

### Potential Terraform Configuration

```hcl
resource "auth0_organization" "my_org" {
  name         = "my_org"
  display_name = "My Organization"

  branding {
    logo_url = "https://cdn.my.org/public/logo.png"

    colors {
      primary         = "#0059d6"
      page_background = "#000000"
    }
  }

  organization_metadata = {
    my_custom_metadata = 42
  }
}
```

### References

* #394
* https://github.com/go-auth0/auth0/pull/216

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Released with v0.22.0. [Get it while its hot](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/organization) :)
