### ISSUE TITLE
Can't create a ADFS connection

### ISSUE THREAD

**Issue by HebosHebbe** [alexkappa/terraform-provider-auth0#457]
### Description

Unable to create a ADFS connection, getting the error:
`Error: 400 Bad Request: missing federation metadata url`

This is the same error I get from Auth0 management API when omitting the option `adfs_server`. However, the terraform configuration clearly contains the option (see below).

### Terraform Version
```
Terraform v0.13.7
+ provider.auth0 v0.21.0
```

### Affected Resource(s)

* auth0_connection

### Terraform Configuration Files

```hcl
resource "auth0_connection" "connection" {
  name = var.name
  strategy = "adfs"
  enabled_clients = var.enabled_clients
  display_name = var.display_name

  options {
    adfs_server = var.adfs_server
  }
}
```

### Expected Behavior

Expected to be able to create a new ADFS connection

### Actual Behavior

Connection not created

### Steps to Reproduce

1. `terraform apply`

### Debug Output
```
Terraform will perform the following actions:

  # auth0_connection.connection will be created
  + resource "auth0_connection" "connection" {
      + enabled_clients      = (known after apply)
      + id                   = (known after apply)
      + is_domain_connection = (known after apply)
      + name                 = "testadfs"
      + realms               = (known after apply)
      + strategy             = "adfs"
      + strategy_version     = (known after apply)

      + options {
          + adfs_server              = "CENCORED_SECRET_VALID_METADATA_URL"
          + non_persistent_attrs     = (known after apply)
          + password_policy          = (known after apply)
          + set_user_root_attributes = (known after apply)
          + strategy_version         = (known after apply)

          + password_history {
              + enable = (known after apply)
              + size   = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

auth0_connection.connection: Creating...

Error: 400 Bad Request: missing federation metadata url

  on main.tf line 1, in resource "auth0_connection" "connection":
   1: resource "auth0_connection" "connection" {
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by HebosHebbe** [comment]
Yes, it works with the Management API as well.

**Comment by alexkappa** [comment]
Hi @HebosHebbe, I believe this is a bug. Thanks for reporting

**Comment by alexkappa** [comment]
@HebosHebbe the latest release should resolve this bug. Please reopen this issue otherwise.
