### ISSUE TITLE
In auth0_client default for jwt_configuration.alg should be RS256

### ISSUE THREAD

**Issue by abbaspour** [alexkappa/terraform-provider-auth0#459]
In auth0_client, default for jwt_configuration.alg is HS256 which is not best practice. appreciate if you can change the default to RS256 is future.

**Comment by alexkappa** [comment]
Hi @abbaspour,

I checked the provider implementation and there doesn't seem to be a setting that defaults to HS256 specifically. I believe this behavior is coming from the Auth0 Management API.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/48 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
