### ISSUE TITLE
Add support for 'Fixed Length of Access Token & Authorization Code' flag in Tenant Settings

### ISSUE THREAD

**Issue by L-Sypniewski** [alexkappa/terraform-provider-auth0#461]
### Description

Add the ability to set 'Fixed Length of Access Token & Authorization Code' flag in Tenant Settings

### New or Affected Resource(s)

* auth0_tenant

### Potential Terraform Configuration

```hcl
resource "auth0_tenant" "my_org" {
  name         = "my_org"
  display_name = "My Organization"

  fixed_length_access_token_and_authorization_code = true
}
```

### References

* https://auth0.com/docs/product-lifecycle/deprecations-and-migrations#opaque-access-token-and-authorization-code-fixed-length-

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/50 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
