### ISSUE TITLE
Organization ID as output

### ISSUE THREAD

**Issue by jowparks** [alexkappa/terraform-provider-auth0#462]
### Description

Support for organizations was added in 0.22.0, but there are no attribute references. On creation of the organization, there should be an organization_id output.

### New or Affected Resource(s)

* auth0_organization

### Potential Terraform Configuration

Expected 
```hcl
resource "auth0_organization" "organization" {
  name         = var.org_name
  display_name = var.display_name
  branding {
    logo_url = var.logo_url
    colors {
      primary         = var.primary_color
      page_background = var.page_background
    }
    dynamic "connections" {
      for_each = [lookup(connections.value, "connection", {})]
      content {
        connection_id              = lookup(connection.value, "connection_id")
        assign_membership_on_login = lookup(connection.value, "assign_membership_on_login", true)
      }
    }
  }
}
```

```hcl
output "id" {
  description = "ID of the organization."
  value       = auth0_organization.organization.organization_id
}
```

### References
As seen in Auth0 UI, organization ID is populated
<img width="1079" alt="Screen Shot 2021-11-02 at 9 55 15 AM" src="https://user-images.githubusercontent.com/26990067/139910675-44796c94-a276-43f1-9a0e-6b93a024ef80.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @jowparks, have you tried `auth0_organization.organization.id`?

**Comment by jowparks** [comment]
I have no @alexkappa, I will give it a shot though and see if the output makes sense!

**Comment by jowparks** [comment]
@alexkappa doesn't seem to work:

```
[2021-11-03T20:17:06.312Z] │   on ../../../../../../../providers/auth0/modules/organization/outputs.tf line 14, in output "id":

[2021-11-03T20:17:06.312Z] │   14:   value       = auth0_organization.organization.id

[2021-11-03T20:17:06.312Z] │ 

[2021-11-03T20:17:06.312Z] │ A managed resource "auth0_organization" "organization" has not been declared in module.auth0_organization_invitae.
```

**Comment by Fred-MabS** [comment]
Hi @jowparks,
the resource `auth0_organization.organization` has the `id` property, as suggested by @alexkappa.
I currently use it the way he said previously.

I guess your problem is somewhere else in your code.

Best regards,
Fred

**Comment by alexkappa** [comment]
Hi @jowparks, I tried an example just to make sure.

```tf
terraform {
  required_providers {
    auth0 = {
      source  = "alexkappa/auth0"
      version = "0.22.0"
    }
  }
}

provider "auth0" {}

resource "auth0_organization" "organization" {
  name         = "alex-inc"
  display_name = "Alex Inc."
  connections {
    connection_id = "con_XXXxxxxxXXXXxxxx"
  }
}

output "auth0_organization_id" {
  value = auth0_organization.organization.id
}
```
This outputs

```sh
$ terraform apply -auto-approve                                                                                                                                                                                                                             [17:07:58]
auth0_organization.organization: Creating...
auth0_organization.organization: Creation complete after 1s [id=org_YYYyyyYYYyYYYyyy]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

auth0_organization_id = "org_YYYyyyYYYyYYYyyy"
```

As @Fred-MabS suggested you may need to double check that the values you are referencing in the output block are in line with your resource.

**Comment by jowparks** [comment]
Thanks for the heads up and testing guys!  I will triage my error and see if I can get it working. I think we will just need to update documentation though, otherwise this is a hidden feature!

**Comment by alexkappa** [comment]
Indeed, I'm afraid none of the resources document id's as they are usually implicit. But its definitely worth pursuing.

**Comment by alexkappa** [comment]
Lets continue this in #465

**Comment by jowparks** [comment]
FWIW to anyone reading, I had defined an `organization.tf` file, the build was failing because it was looking for it, but I never checked in the file 😅
