### ISSUE TITLE
Grant type 'client_credentials' not allowed for the client

### ISSUE THREAD

**Issue by remmelt** [alexkappa/terraform-provider-auth0#466]
### Description

I have created a Single Page Application in auth0, which by default does not support the `client_credentials` grant type because it's deemed to be a public application.

Now I cannot use this provider because the only way to pass credentials is to use the `client_credentials` flow, using `client_id`, and `client_secret`.

This results in the following error message:

```
Grant type 'client_credentials' not allowed for the client
```

Is there a way for this provider to authenticate with auth0 using implicit, auth code, or refresh token flows?

### Terraform Version
 

```
Terraform v1.0.10
on darwin_arm64
+ provider registry.terraform.io/alexkappa/auth0 v0.23.0
+ provider registry.terraform.io/hashicorp/google v4.0.0
+ provider registry.terraform.io/hashicorp/google-beta v4.0.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)
 

* auth0_connection
but probably all of them

### Terraform Configuration Files

```hcl
provider "auth0" {
  domain    = var.auth0_tenant_domain
  client_id = var.auth0_web_dashboard_client
  debug     = true
}

resource "auth0_connection" "connections" {
  name = "chain"
  strategy = "auth0"

  options {
    password_policy = "excellent"
    password_history {
      enable = true
      size = 3
    }
    brute_force_protection = "true"
  }
}

```

### Expected Behavior

The resources should be created

### Actual Behavior

An error was thrown

### Steps to Reproduce

1. `export TF_VAR_auth0_client_secret=$AUTH0_CLIENT_SECRET`
1. `terraform apply`

### Important Factoids

Apple M1

### References

https://community.auth0.com/t/error-grant-type-client-credentials-not-allowed-for-the-client/7606

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @remmelt,

You would need a machine-to-machine client to use the terraform provider. Afaik Auth0 tenants come with a default _Auth0 Management API_ Application and an API with the same name. These are more suitable for anything that manipulates the Auth0 Management API (which is what this provider uses behind the scenes). You can always define your own application / API pair for the specific needs you have.

More info:
- https://auth0.com/docs/security/tokens/access-tokens/management-api-access-tokens
- https://auth0.com/docs/security/tokens/access-tokens/get-management-api-access-tokens-for-production

**Comment by remmelt** [comment]
Ah, I understand. Thanks for explaining. In other words, there does need to be some manual setup before terraform can happen, right?

**Comment by alexkappa** [comment]
Indeed, you need a client that can communicate with the auth0 management api. From then on you can do everything in terraform. 

It may be possible to use the import functionality to manage that client/resource_server with terraform, but I haven't tried that myself 🤔
