### ISSUE TITLE
auth0_action: secrets are not getting added while new/update action call

### ISSUE THREAD

**Issue by RishikeshDarandale** [alexkappa/terraform-provider-auth0#477]
### Description

`auth0_action` secrets **most** probably do not support the update/delete of existing secrets. But, adding new is supported and this functionality is not working at this moment with resource `auth0_action`.

### Terraform Version

```console
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/alexkappa/auth0 v0.24.2
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

### Affected Resource(s)

* auth0_action

### Terraform Configuration Files

```hcl
resource "auth0_action" "test-action" {
  name = "test"
  supported_triggers {
    id      = "pre-user-registration"
    version = "v2"
  }

  code    = file("test.js")
  runtime = "node16"

  dependencies {
    name    = "Dep1"
    version = "v1"
  }
  dependencies {
    name    = "Dep2"
    version = "v2"
  }

  secrets {
    name  = "SOME_KEY"
     value = "SOME_VALUE"
  }

  deploy = true
}
```

### Expected Behavior

- `terraform import` should get the secret key read into the state file
- `terraform apply` should add the new secret to the action

#### Use Cases

- import existing `action` having one secret
- create a new `action` with one secret
- update a existing `action` to add a new secret

> Note: In all cases, `terraform` (internally auth0 mgmt API) should not be deleting/updating existing secrets.

Above observation is based on the events that were recorded #470 as below. 
- Import action resource with secret and code does not have secret
- later resource has secret added, shown in plan; 
- PATCH api body does not have secret added. 
- PATCH call successful
- The existing secret is still there, thus above observation holds true.

### Actual Behavior

- `terraform import` is not importing the secret with only key into terraform state
- `terraform apply` is not passing the new secrets to HTTP PATCH call for action update.

### Steps to Reproduce

1. `terraform apply`

### Debug Output

Please refer #470 and #472 for more debug details!

### References

- #470 
- #472

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by RishikeshDarandale** [comment]
@alexkappa , Any comments/questions on above description?

**Comment by alexkappa** [comment]
Hi @RishikeshDarandale, thanks for filing this issue. The bug report is quite clear, with the only note I'd like to emphasize is that secrets are not importable. Secrets are known only during POST/PATCH requests and are never present in GET requests (which import relies on).

That being said, I think I found the issue and will send a PR with a fix soon.

**Comment by RishikeshDarandale** [comment]
@alexkappa , as per mgmt [api](https://auth0.com/docs/api/management/v2#!/Actions/get_actions) call, `secrets` name with added date is available. can we not import secret name with added date into state for import case?

**Comment by alexkappa** [comment]
I can give it a look for sure. Will update again as I know more.

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/52 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
