### ISSUE TITLE
Error: 400 Bad Request: runtime is not supported

### ISSUE THREAD

**Issue by vlade-symphony** [alexkappa/terraform-provider-auth0#485]
I created auth0 actions using this provider and when I run terraform apply I get an error "Apply errored: Error: 400 Bad Request: runtime is not supported"

This is my code:

```
resource auth0_action set_token_type {
  name = "Set-Token-Type"
  supported_triggers {
    id      = "post-login"
    version = "v1"
  }
  runtime = "node16"
  deploy  = true
  code    = <<-EOT
    /**
    * Handler that will be called during the execution of a PostLogin flow.
    *
    * @param {Event} event - Details about the user and the context in which they are logging in.
    * @param {PostLoginAPI} api - Interface whose methods can be used to change the behavior of the login.
    */
    exports.onExecutePostLogin = async (event, api) => {
    };
    EOT
}
```

I removed `runtime` from the code and terraform applied successfully.

But in Auth0 UI when I check Actions that were created, I see this:

"This Action was built during the beta period of Auth0 Actions. As the transition from Beta to General Availability (GA) for Actions begins, there is a one-time step you need to take to update your Actions to the GA version. To do this, you will need to create a new Action, which will use the latest version of the programming model. For more information on the latest programming model - especially for Actions triggers - you can reference our documentation."

Is this a provider issue or I am doing something wrong?

**Comment by alexkappa** [comment]
Hi @vlade-symphony, this seems like the API  is rejecting the request. The provider doesn't perform any validation regarding the runtime, so I doubt its provider related. 

Might it be related to the version of the post-login trigger in combination with node16 runtime?

**Comment by vlade-symphony** [comment]
Hi @alexkappa. When I changed the "post-login" version from v1 to v2, everything works fine. Thanks
