### ISSUE TITLE
Add native_social_login option to auth0_client

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [alexkappa/terraform-provider-auth0#488]
### Description

Auth0 has 2 toggles that enable the native social login for Apple and Facebook social login. These toggles can't be managed atm with the Terraform provider

This is how should be configured via Auth0 APIs
```
  "native_social_login": {
    "apple": {
      "enabled": true
    },
    "facebook": {
      "enabled": true
    }
  },
```

### New or Affected Resource(s)

* auth0_client

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://auth0.com/docs/connections/social/facebook-native

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiughf** [comment]
Hey @ca-simone-chiorazzo ! Thanks for reporting this! This is now available under https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.25.1. 

As such we'll be closing this issue. Please feel free to reopen in case of need!
