### ISSUE TITLE
auth0_tenant flags not working as expected

### ISSUE THREAD

**Issue by ccogan-lh** [alexkappa/terraform-provider-auth0#491]
### Description

When defining a tenant, I provide the flags.enable_client_connections parameter and have it be false.  Terraform applies with no issue, but within the Auth0 console I see this is toggled to true.  Terraform does not see the delta and says no issue.  I can manually flip the state on Auth0 and Terraform still does not see the issue.

### Terraform Version

```
╰─ terraform -v
Terraform v1.1.2
on darwin_amd64
```

### Affected Resource(s)

* auth0_tenant

### Terraform Configuration Files

```hcl
resource "auth0_tenant" "project" {
  picture_url   = "https://project.com/images/main-logo.png"
  support_email = "engineering@project.com"
  flags {
    enable_client_connections = false
  }
}
```

### Expected Behavior

New tenant should exist with client_connections = disabled

### Actual Behavior

New tenant exists client_connections = true and does not properly track deltas

### Steps to Reproduce

1. `terraform apply`
2. Inspect Auth0 UI tenant settings to see flag is still true

### Debug Output

N/A ? 

### Panic Output

N/A

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/54 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
