### ISSUE TITLE
Support for `session_cookie` argument in `auth0_tenant` resource

### ISSUE THREAD

**Issue by wcislo-taxy-io** [alexkappa/terraform-provider-auth0#492]
### Description

Support for `session_cookie` argument in `auth0_tenant` resource.

As of right now management API allows for controlling this setting.

### New or Affected Resource(s)

* auth0_tenant

### References

* https://auth0.com/docs/api/management/v2#!/Tenants/tenant_settings_route
* https://auth0.com/docs/api/management/v2#!/Tenants/patch_settings

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/55 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
