### ISSUE TITLE
`auth0_connection`: add `show_as_button` option

### ISSUE THREAD

**Issue by mdreizin** [alexkappa/terraform-provider-auth0#493]
### New or Affected Resource(s)

* auth0_connection

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "auth0_connection" "test" {
  name                 = "test"
  display_name         = "Test"
  strategy             = "oidc"
  show_as_button       = true
  options {
    client_id     = "client-id"
    discovery_url = "https://example.com/.well-known/openid-configuration"
    icon_url      = "https://example.com/icon.png"
  }
}
```

### References

I have already contacted Auth0 support and asked them to add that options.

For now you can try to go https://auth0.com/docs/api/management/v2/#!/Connections/post_connections and use the following `body` to test it:

```json
{
  "strategy": "oidc",
  "options": {
    "client_id": "client-id",
    "discovery_url": "https://example.com/.well-known/openid-configuration",
    "icon_url": "https://example.com/icon.png"
  },
  "name": "test",
  "display_name": "Test",
  "show_as_button": true
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mdreizin** [comment]
`icon_url` is supported. It will require to add `show_as_button`.

**Comment by mdreizin** [comment]
It looks that if `display_name` is set then Auth0 Management API sets `show_as_button` to `true`.

**Comment by mdreizin** [comment]
@alexkappa Do you have any updates on this?

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/56 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
