### ISSUE TITLE
Allow enabling "Connection button" for Azure Active Directory enterprise connection (waad)

### ISSUE THREAD

**Issue by smhamza24** [alexkappa/terraform-provider-auth0#495]
### Description

When creating auth0_connection with strategy waad the login button doesn't appear on login page until we go to auth0 dashboard and manually set "Display connection as a button" checkbox. 

### New or Affected Resource(s)

* auth0_connection 

### Potential Terraform Configuration

```hcl
resource "auth0_connection" "aad" {
  name     = "microsoft-azure-AD"
  strategy = "waad"
  options {
    waad_common_endpoint = false
    tenant_domain = "test.com"
    identity_api = "microsoft-identity-platform-v2.0"
    client_id = "asdfasdfafsd"
    client_secret = "asfasdf"
    //something like following could be helpful
    display_connection_as_button = true
    display_connection_as_button_label = "Login with AD"
    display_connection_as_button_logo = "https://my.domain/logo.png"
  }
  enabled_clients = [auth0_client.my_new_app.id]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/57 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
