### ISSUE TITLE
`auth0_action` for `post-user-registration` trigger is created as Post Login in Auth0

### ISSUE THREAD

**Issue by WellBloud** [alexkappa/terraform-provider-auth0#503]
### Description
If I create an `action` with `post-user-registration` trigger, it will get created as an action with `Login / Post login` trigger.

```
resource "auth0_action" "post_reg_action" {
  name   = "Post registration action"
  supported_triggers {
    id      = "post-user-registration"
    version = "v2"
  }
  deploy = true
  code = ""
}
```
When deployed, it looks like this:
![image](https://user-images.githubusercontent.com/15383787/151186594-06a27e6d-73ca-4cb2-bc14-8b28f8b23ca7.png)

It shouldn't say `Login / Post login`, but rather `Post User Registration`. 

Also, if you try to bind this into a Flow, it will fail with following error:
```
╷
│ Error: 400 Bad Request: Trying to create a binding between an incompatible action and trigger.
│ 
│   with auth0_trigger_binding.post_user_registration_flow,
│   on flowPostRegistration.tf line 2, in resource "auth0_trigger_binding" "post_user_registration_flow":
│    2: resource "auth0_trigger_binding" "post_user_registration_flow" {
│ 

```
The code for the binding:

```
resource "auth0_trigger_binding" "post_user_registration_flow" {
  trigger = "post-user-registration"
  actions {
    id           = auth0_action.post_reg_assign_roles_action.id
    display_name = auth0_action.post_reg_assign_roles_action.name
  }
}
```

### Terraform Version

```
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/alexkappa/auth0 v0.26.1

```

### Expected Behavior

It should create an Action ready to be used in **Post-registration flow**

### Actual Behavior

It creates an Action in **Login flow**

### Steps to Reproduce

1. `terraform apply`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/59 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
