### ISSUE TITLE
User data source

### ISSUE THREAD

**Issue by willvedd** [alexkappa/terraform-provider-auth0#505]
### Description

Implement a user data source in the provider to allow for easier management of Auth0 users when unable to manage through Terraform directly. This ticket stems from the closure of #429.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by willvedd** [comment]
Data sources are something that we're actively looking into, stay tuned!

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/60 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
