### ISSUE TITLE
Error when creation Auth) connection with strategy = "auth0-adldap".

### ISSUE THREAD

**Issue by vincentchentx** [alexkappa/terraform-provider-auth0#508]
I tried to create an LDAP connection with the following:
resource "auth0_connection" "terraform-express-ldap" {
  name     = "terraform-express-ldap"
  strategy = "auth0-adldap"
  options {
    password_policy        = "good"
    brute_force_protection = true
	import_mode = true
	mfa {
		active = true
		return_enroll_settings = true
	}
  }
  enabled_clients = [auth0_client.terraform-secure-express.id, var.auth0_client_id]
}

And I received this error:
auth0_connection.terraform-express-ldap: Creating...
╷
│ Error: 400 Bad Request: Payload validation error: 'Invalid value "auth0-adldap"' on property strategy (The identity provider identifier for the connection).
│
│   with auth0_connection.terraform-express-ldap,
│   on main.tf line 51, in resource "auth0_connection" "terraform-express-ldap":
│   51: resource "auth0_connection" "terraform-express-ldap" {
│

I do not see the options documented for strategy = "auth0-adldap". Can you share more details how to create LDAP connection?

Thanks,
Vincent

**Comment by vincentchentx** [comment]
I found the problem. It should be ad instead of auth0-adldap:
strategy = "ad"

**Comment by sergiughf** [comment]
Hey @vincentchentx thanks for raising this issue and great that you found the problem already! I'll be closing this issue, but if anything else pops up please feel free to reopen.
