### ISSUE TITLE
Multiple tenants

### ISSUE THREAD

**Issue by bourbonfgiles** [alexkappa/terraform-provider-auth0#509]
Hello, 

I was looking at your provider.tf and I see you specify the tenant. Could I specify multiple tenants in separate provider blocks or is only one per repo supported? 

Thanks,
Ben.

**Comment by Jno21** [comment]
Hello,

You can totally specify multiple tenants in separate provider blocks, it is a Terraform feature so it is not link to the provider itself.

For example:
```hcl
provider "auth0" {
  domain = "<domain_one>"
  client_id = "<client_id_one>"
  client_secret = "<client_secret_one>"
}

provider "auth0" {
  alias = "second"

  domain = "<domain_two>"
  client_id = "<client_id_two>"
  client_secret = "<client_secret_two>"
}

resource "auth0_prompt" "this" {
  universal_login_experience = "classic"
  identifier_first                        = false
}

resource "auth0_prompt" "this" {
  provider = auth0.second

  universal_login_experience = "new"
  identifier_first                        = false
}
```

But I think it is important to think about how you want to do things.
If your different tenant should have the same configuration I will advice against this method since it implies to duplicate resources.

**Comment by bourbonfgiles** [comment]
Thanks @Jno21 ! The reason I ask is I'm trying to write a module write now to encompass two domains, each referenced in its own tfvars file.

**Comment by bourbonfgiles** [comment]
@Jno21 As for the above, is it possible to not specify the domain in the provider, so as to accommodate multiple domains inside one terraform module?

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/62 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
