### ISSUE TITLE
Add version to end of provider name

### ISSUE THREAD

**Issue by dancrumb** [alexkappa/terraform-provider-auth0#51]
Terraform uses the provider name to determine version information.

Thus, instead of 

`terraform-provider-auth0`

the provider should be

`terraform-provider-auth0_vX.Y.Z`

**Comment by alexkappa** [comment]
Hi @dancrumb, the version is already part of the archive.

From terraform’s [documentation](https://www.terraform.io/docs/extend/writing-custom-providers.html):

> The output name (-o) is very important. 
> Terraform searches for plugins in the format of:
>
> terraform-<TYPE>-<NAME>

**Comment by alexkappa** [comment]
My apologies, as described [here](https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions) it is the right way to version providers.
