### ISSUE TITLE
Only send tenant configuration if changed

### ISSUE THREAD

**Issue by willvedd** [alexkappa/terraform-provider-auth0#513]
### Description

Originally spurring from #351 which was closed due to the project migration. 

From the OP:

>This modification makes it such that tenant setting flags will only be included in the PATCH /api/v2/tenants/settings call if they have changed. This proposed change addresses use cases for Auth0 private cloud and enterprise customers whose tenants do not allow updates of certain tenant settings flags. Even the mere presence of these flags in the API call, irrespective of the values changing or not, will cause the API to return an error response. With these proposed changes, the tenant setting flags will simply be omitted from the API call if unchanged, thus bypassing the issue altogether.

This issue, while appearing to be straightforward, is non-trivial to holistically address. I defer to the comments in #351 for explanation. 

This would also fix #160 .

### References

- #351 
- [PATCH tenant settings](https://auth0.com/docs/api/management/v2#!/Tenants/patch_settings)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/63 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
