### ISSUE TITLE
Where can I find the ID of a tenant?

### ISSUE THREAD

**Issue by bourbonfgiles** [alexkappa/terraform-provider-auth0#514]
I'm importing an existing auth0 tenant. Is there an easy way to find the ID of the tenant so as to import into state? 

Thank you.

**Comment by sergiughf** [comment]
Hey @bourbonfgiles, thanks for the question. To import tenant settings into state you can use the name. You can find it under the settings. Example: 
![image](https://user-images.githubusercontent.com/28300158/153207666-fea9ce9a-484a-4942-8782-56da6a81622e.png)

**Comment by bourbonfgiles** [comment]
Thank you, I'd just assumed it would be an ID rather than the name :)
