### ISSUE TITLE
Dependency didn't resolved between trigger binding and action when we want to delete an action.

### ISSUE THREAD

**Issue by hknerts** [alexkappa/terraform-provider-auth0#515]
### Description

Dependency didn't resolved between trigger binding and action when we want to delete an action.

First we deleted trigger binding resource then we delete action. We had to do it this way for now.

### Terraform Version
**v0.12.20**

```
Terraform <TERRAFORM_VERSION>
+ provider.auth0 <TERRAFORM_PROVIDER_VERSION>
```
TERRAFORM_VERSION = **0.12.20**
TERRAFORM_PROVIDER_VERSION = **0.26.1**

### Affected Resource(s)

* auth0_action
* auth0_trigger_binding

### Terraform Configuration Files

```hcl

https://gist.github.com/hknerts/39b1d03a2d244cd811bf08df9f8580ba
```

### Expected Behavior

resolve dependency between action and trigger binding

### Actual Behavior

didnt resolved dependency between action and trigger binding

### Steps to Reproduce

1. `terraform apply`

### Debug Output
![image](https://user-images.githubusercontent.com/11432786/153407313-636c092c-891b-4be8-b528-1b90ca6fee6a.png)

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/64 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
