### ISSUE TITLE
How do I find the ID of various resources in the portal?

### ISSUE THREAD

**Issue by bourbonfgiles** [alexkappa/terraform-provider-auth0#517]
For instance, while the tenant is imported by name, the branding resource doesn't list how to import it, is it by ID or name?
Where can I find either of these in the portal? I'll need to import a lot of these resources into state.

I would have tried to create some to see what they output, but a lot of resources don't output a name or ID on the documentation on terraform registry. 

https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/branding

Thanks!

**Comment by sergiughf** [comment]
Hey @bourbonfgiles, thanks for your question. It's a really good one and we can definitely do a better job explaining within the docs how to import each resource. This is something we will work on very shortly. 

For now the heuristics I can give when it comes to resource importing are the following:

- Some resources like e.g. branding don't exactly have an Auth0 associated ID with them. Within the code when we create a branding resource we just set the ID to a random uniquely generated one (https://github.com/alexkappa/terraform-provider-auth0/blob/master/auth0/resource_auth0_branding.go#L84) so we correctly store it within the terraform state. For importing these kind of resources you could use any kind of ID e.g. `terraform import auth0_branding.my_branding branding-for-auth0`.
- On resources that do have an Auth0 associated ID with them for example clients https://auth0.com/docs/api/management/v2#!/Clients/get_clients the ID within the management dashboard or the one fetched from the API Explorer Page needs to be used. 

I hope this helps and please let me know if you have any follow up questions on this or if something's not clear.

**Comment by bourbonfgiles** [comment]
@sergiughf Thank you! I'll work from what you've said here and check back in.

**Comment by sergiught** [comment]
As we've already answered this and because we are preparing to move all the issues over at https://github.com/auth0/terraform-provider-auth0 I'll be closing this down. Please reopen an issue over there if needed.
