### ISSUE TITLE
Allow to update Node Runtime Extensibility on Tenant settings  

### ISSUE THREAD

**Issue by zyhou** [alexkappa/terraform-provider-auth0#518]
Hello,

### Description

Can we add the possibility to update the Extensibility on the tenant settings? Node 8 will be deprecated pretty soon.

Tenant settings -> Advance -> Scroll down
![image](https://user-images.githubusercontent.com/2212144/153574527-85316c55-7f8d-43cf-817f-bf6d2b4fc57f.png)
 
### Affected Resource(s)

* auth0_tenant

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiughf** [comment]
Hey @zyhou, thanks for the question. Admittedly we can do a better job at documenting this and we will do so soon, however this functionality is already present within the provider and it's mapped to the `sandbox_version` field e.g.

```tf
resource "auth0_tenant" "tenant" {
  sandbox_version  = "8"
}
```

You can set this to 12 to use Node 12.

Hope this helps and please let me know if you have any further questions.

**Comment by zyhou** [comment]
Oh, I don't see this option... I will try this. I searched for "node" in the tenant section in the documentation.

Thanks, I can close the issue :+1:
