### ISSUE TITLE
Organization connection does not get updated

### ISSUE THREAD

**Issue by roijokr** [alexkappa/terraform-provider-auth0#521]
### Description
The provider is unable to refresh some resources or update them

### Terraform Version

```
Terraform v1.1.6
+ provider.auth0 v0.26.2
```

### Affected Resource(s)

auth0_organization

### Terraform Configuration Files

```hcl

resource auth0_organization team {
    for_each   = auth0_client.hart_platform
    name = "${each.key}-region"
    display_name = "${each.key}-region"

  connections {
        connection_id = auth0_connection.google-connection.id
        assign_membership_on_login = false
    }

}

```

### Expected Behavior
terraform will apply the changes to those configurations or refresh the state based on the changes in auth0

### Actual Behavior

updating assign_membership_on_login value does not show any changes made after plan
### Steps to Reproduce

1. `terraform plan`

### Debug Output

https://gist.github.com/roijokr/445e4431309eb5cdbe056f3a50184dab

### References

https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/organization#connections
* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
We have moved this issue over at https://github.com/auth0/terraform-provider-auth0/issues/65 as this repo is now maintained at https://github.com/auth0/terraform-provider-auth0.
