### ISSUE TITLE
Publish provider to the official Terraform registry

### ISSUE THREAD

**Issue by danielepolencic** [alexkappa/terraform-provider-auth0#57]
The provider doesn't cover all resources for Auth0, but it's usable in its current form (I can't say the same for official providers such as the Kubernetes provider).

I think you should publish it to the official registry. If this is not in your interest, feel free to close this issue.

**Comment by alexkappa** [comment]
You are right, publishing this would make it way easier for users to install/upgrade. I engaged with hashicorp earlier on the development of this project, maybe its good time to finalize that.

> I can't say the same for official providers such as the Kubernetes provider

I'll take that as a compliment 😄

**Comment by mbelang** [comment]
Is there a follow up on that? It would be (a lot) more convenient to have it part of the official repo :joy:

**Comment by alexkappa** [comment]
@mbelang yes, I've contacted Hashicorp they let me know that someone will be looking into the project and leave their remarks in the form of Github issues. I haven't heard back since that time, I can send them a reminder.

**Comment by mbelang** [comment]
It's a shame that we need to go through them for that... So much for Open Source. BTW, your provider is working well for us!

**Comment by alexkappa** [comment]
Well, if this provider does get approved, it becomes part of the hashicorp.io documentation and such which gives shifts some responsibility to Hashicorp themselves as it gets their stamp of approval, so I can understand their motives in this sense :)

Thanks, @mbelang, much appreciated, and I'm glad you find it useful!

**Comment by Sytten** [comment]
Any update?

**Comment by stanhordiyenko** [comment]
Hi @alexkappa is there any update on this?

**Comment by alexkappa** [comment]
No update yet, please follow along the progress of the review here: #70. 

If you want to help make this provider official, you can contribute by writing some documentation here: #87.

**Comment by alexkappa** [comment]
Provider is available from the terraform registry at: https://registry.terraform.io/providers/alexkappa/auth0/latest
