### ISSUE TITLE
Disabling google-auth2

### ISSUE THREAD

**Issue by danielepolencic** [alexkappa/terraform-provider-auth0#59]
google-auth2 is enabled by default with each new client.
I tried to read the code, but I can't seem to find any way to force *not* creating the connection.

Is there any known workaround to not have google-auth2 as part of every client?

**Comment by alexkappa** [comment]
Hi @danielepolencic, I am unable to reproduce this issue. Running the client example from the [`example/`](/blob/master/example/client/main.tf) directory enables the `Username-Password-Authentication` connection by default (also not ideal).

Perhaps Auth0 chooses a default connection depending on the existing settings? I don't know if this is documented somewhere.

**Comment by kevinohara80** [comment]
I think the issue is that if the google-oauth2 connection is enabled at all, it's default-on when creating a new connection.

**Comment by andyhd** [comment]
I think that when you create a new client/application in Auth0, all existing connections are enabled by default.

Specifying which connections are enabled/disabled for a new client is controlled by adding/removing the client ID to each connections `enabled_clients` list (this seems backwards to me).

At the moment, I think the only way of controlling this is to create the connection with the list of clients, eg:
```
resource "auth0_client" "my-client" {
  ...
}
resource "auth0_connection" "google-oauth2" {
  ...
  enabled_clients = [
    "${auth0_client.my-client.id}",
    ...
  ]
}
```

I think it might be a good idea (feature request warning!) to have a virtual `auth0_client_connection` resource, similar to the `aws_volume_attachment` resource, which could insert the client ID into the connections `enabled_clients` list.

**Comment by nickmelis** [comment]
Any progress on this one? I just had the very same problem described here.

**Comment by alexkappa** [comment]
Hi @nickmelis, the [Google OAuth2 connection documentation](https://registry.terraform.io/providers/alexkappa/auth0/latest/docs/resources/connection#google-oauth2) has been updated to mention a workaround for this issue. At this time, you'll need to import the connection in order to manage it through terraform.
