### ISSUE TITLE
Create terraform.io provider documentation

### ISSUE THREAD

**Issue by alexkappa** [alexkappa/terraform-provider-auth0#87]
In order to participate in the provider developer program, each Terraform provider must have its own terraform.io website documentation that should reside under a website/ directory. There should be a page for each resource and data source as well as an index page for the provider. Along with with must be a ruby layout file to represent the side bar directory.

**Comment by rkhoriander** [comment]
Hi, @alexkappa. Just FYI, I'm working on docs for this now, so I'll have something for you very shortly.

**Comment by alexkappa** [comment]
Wonderful @rkhoriander, looking forward to it. Let me know if I can help in the meantime.

**Comment by vidarw** [comment]
@rkhoriander Do you have a fork with the basic setup where I can contribute?

**Comment by dijitali** [comment]
Has the [move to the new Terraform Registry](https://www.hashicorp.com/blog/announcing-providers-in-the-new-terraform-registry/) for provider documentation changed the requirements here?  Are there guidelines yet on the format the docs need to be in?

**Comment by alexkappa** [comment]
Hi @dijitali, the format is still the older one as advised by our contact at HashiCorp. It is largely compatible though so the switch should be relatively easy for this provider.

I will reach out to our contact again regarding this announcement and make sure we’ll be available there too.

**Comment by sergiughf** [comment]
Hello everyone, it seems that this issue has been already solved and as such I'll be closing it down over here. In case there are new updates please feel free to reopen it.
