### ISSUE TITLE
grant scopes empty array sent as null leading to 400 response

### ISSUE THREAD

**Issue by jasonkuhrt** [alexkappa/terraform-provider-auth0#94]
```tf
resource "auth0_client_grant" "telephone_client_grant" {
  client_id = "${auth0_client.telephone.id}"
  audience  = "${auth0_resource_server.dialogue_api.identifier}"
  scope     = []
}
```
```
Error: Error applying plan:

1 error(s) occurred:

* module.auth0-infra.auth0_client_grant.telephone_client_grant: 1 error(s) occurred:

* auth0_client_grant.telephone_client_grant: 400 Bad Request: Payload validation error: 'Expected type array but found type null' on property scope.

```

It seems that the changes in https://github.com/yieldr/go-auth0/pull/29 were not enough 🤔

**Comment by oderby** [comment]
I can also confirm - seeing the exact same behavior here as well, both when creating (POST) or updating (PATCH) client_grants.

Workaround of putting in a bogus scope string (suggested at https://github.com/yieldr/terraform-provider-auth0/issues/50#issuecomment-437546429) works for me for now.
